// IW8 DBG GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

stoppingpower_beginuse()
{
    var_0 = self.lastnormalweaponobj;
    var_1 = nullweapon();

    if ( scripts\mp\utility\weapon::isknifeonly( var_0 ) || scripts\mp\utility\weapon::issuperweapon( var_0 ) || scripts\mp\utility\weapon::iskillstreakweapon( var_0 ) || scripts\mp\utility\weapon::isgamemodeweapon( var_0 ) || scripts\mp\riotshield::isriotshield( var_0.basename ) || scripts\mp\utility\weapon::issinglehitweapon( var_0.basename ) || !stoppingpower_isvalidprimaryoralt( var_0 ) || var_0.basename == "iw8_lm_dblmg_mp" || var_0.basename == "iw8_fists_mp" )
    {
        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "hud", "showErrorMessage" ) )
            self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "hud", "showErrorMessage" ) ]]( "MP/SUPPORT_BOX_INCOMPAT" );

        return 0;
    }

    var_2 = stoppingpower_cancelreload();

    if ( !istrue( var_2 ) )
        return 0;

    if ( self isalternatemode( var_0 ) )
    {
        var_1 = var_0;
        var_0 = var_0 getnoaltweapon();
    }
    else
        var_1 = var_0 getaltweapon();

    var_3 = [];
    var_4 = 0;
    var_5 = 0;

    if ( !isnullweapon( var_1 ) )
        var_3[var_3.size] = var_1;

    var_3[var_3.size] = var_0;

    foreach ( var_7 in var_3 )
    {
        var_8 = 0;

        if ( var_7 hasattachment( "akimbo", 1 ) )
            var_8 = 1;

        if ( issameweapon( var_7, var_0, 0 ) )
        {
            var_9 = scripts\mp\weapons::getammooverride( var_7 );
            var_10 = var_9 * 1;

            if ( var_8 )
                var_10 = var_10 * 2;

            thread stoppingpower_givehcr( self, var_7, var_10 );

            if ( 1 )
            {
                if ( var_8 )
                {
                    var_9 = self getweaponammoclip( var_7, "left" ) + self getweaponammoclip( var_7, "right" );
                    var_4 = self getweaponammostock( var_7 );
                    var_11 = var_9 + var_4;
                    var_12 = int( min( weaponmaxammo( var_7 ), var_11 + var_10 ) );
                    self setweaponammostock( var_7, var_12 );
                    self setweaponammoclip( var_7, 0, "left" );
                    self setweaponammoclip( var_7, 0, "right" );
                }
                else
                {
                    var_9 = self getweaponammoclip( var_7 );
                    var_4 = self getweaponammostock( var_7 );
                    var_11 = var_9 + var_4;
                    var_13 = weaponmaxammo( var_7 );
                    var_14 = var_11 + var_10;
                    var_5 = int( var_14 - var_13 );
                    var_15 = int( min( var_13, var_14 ) );

                    if ( var_7.basename == "iw8_lm_dblmg_mp" )
                        self setweaponammoclip( var_7, var_9 + var_10 );
                    else
                    {
                        self setweaponammostock( var_7, var_15 );
                        self setweaponammoclip( var_7, 0 );
                    }
                }
            }
        }
    }

    thread stoppingpower_waitforreload( var_0, var_4, var_5 );
    return 1;
}

stoppingpower_isvalidprimaryoralt( var_0 )
{
    if ( !self isalternatemode( var_0 ) )
        return 1;

    var_1 = var_0.underbarrel;
    return scripts\mp\weapons::isattachmentselectfire( var_1 );
}

stoppingpower_waitforreload( var_0, var_1, var_2 )
{
    level endon( "game_ended" );
    self endon( "death_or_disconnect" );

    for (;;)
    {
        if ( self getcurrentprimaryweapon() != var_0 )
            break;

        var_3 = self getweaponammoclip( var_0 );

        if ( var_3 > 0 )
        {
            thread scripts\mp\hud_message::showsplash( "stopping_power_loaded" );

            if ( var_2 > 0 )
                self setweaponammostock( var_0, var_1 + var_2 );

            break;
        }

        waitframe();
    }

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "supers", "superUseFinished" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "supers", "superUseFinished" ) ]]();
}

stoppingpower_givehcr( var_0, var_1, var_2 )
{
    if ( !isdefined( var_0.hcrdata ) )
        var_0.hcrdata = [];
    else
    {
        var_3 = var_0.hcrdata[var_1.basename];

        if ( isdefined( var_3 ) )
            var_3 thread stoppingpower_removehcr();
    }

    var_4 = spawnstruct();
    var_4.player = var_0;
    var_4.objweapon = var_1;
    var_4.rounds = var_2;
    var_4.gavehcr = 0;
    var_4.kills = 0;
    var_0.hcrdata[var_1.basename] = var_4;
    var_4 thread stoppingpower_clearhcrondeath();
    var_4 thread stoppingpower_clearhcrongameended();
    var_4 thread stoppingpower_clearhcronperkscleared();
    var_4 thread stoppingpower_givefastreload();
    var_0 thread stoppingpower_breaksprint();
    var_4 thread stoppingpower_watchhcrweaponchange();
    var_4 thread stoppingpower_watchhcrweaponfire();
    return var_4;
}

stoppingpower_cancelreload()
{
    self endon( "death_or_disconnect" );
    self cancelreload();
    wait 0.05;
    return 1;
}

stoppingpower_watchhcrweaponchange()
{
    self endon( "stoppingPower_removeHCR" );
    self.player endon( "disconnect" );

    while ( self.player hasweapon( self.objweapon ) )
    {
        if ( stoppingpower_ishcrweapon( self.player getcurrentweapon() ) )
        {
            if ( !self.gavehcr )
            {
                self.player scripts\mp\utility\perk::giveperk( "specialty_bulletdamage" );
                self.gavehcr = 1;
            }
        }
        else if ( self.gavehcr )
        {
            self.player scripts\mp\utility\perk::removeperk( "specialty_bulletdamage" );
            self.gavehcr = 0;
        }

        self.player waittill( "weapon_change" );
    }

    thread stoppingpower_removehcr();
}

stoppingpower_watchhcrweaponfire()
{
    self endon( "stoppingPower_removeHCR" );
    self.player endon( "disconnect" );

    while ( self.player hasweapon( self.objweapon ) )
    {
        self.player waittill( "weapon_fired", var_0 );

        if ( stoppingpower_ishcrweapon( var_0 ) )
        {
            self.rounds--;

            if ( self.rounds <= 0 )
                break;
        }
    }

    self.player thread stoppingpower_tracklastcrossbowshot( self.objweapon );
    thread stoppingpower_removehcr();
}

stoppingpower_tracklastcrossbowshot( var_0 )
{
    self endon( "disconnect" );

    if ( !isdefined( self ) )
        return;

    var_1 = scripts\mp\utility\weapon::getweaponrootname( var_0 );

    if ( var_1 != "iw8_sn_crossbow" )
        return;

    self.lastcrossbowhadstoppingpower = 1;
    scripts\engine\utility::waittill_any_timeout_no_endon_death_2( 2, "weapon_fired", "weapon_change" );
    self.lastcrossbowhadstoppingpower = undefined;
}

stoppingpower_removehcr()
{
    self notify( "stoppingPower_removeHCR" );

    if ( isdefined( self.player ) )
    {
        if ( self.gavehcr )
            self.player scripts\mp\utility\perk::removeperk( "specialty_bulletdamage" );

        stoppingpower_clearhcrdata();
    }
}

stoppingpower_loadoutchangeremovehcr()
{
    self notify( "stoppingPower_removeHCR" );

    if ( isdefined( self.player ) )
        stoppingpower_clearhcrdata();
}

stoppingpower_clearhcrdata()
{
    if ( isdefined( self.player.hcrdata ) )
    {
        var_0 = self.objweapon.basename;
        var_1 = self.player.hcrdata[var_0];

        if ( var_1 == self )
            self.player.hcrdata[var_0] = undefined;

        self.player scripts\cp_mp\challenges::onfieldupgradeend( "super_support_box", self.kills );
        scripts\mp\analyticslog::logevent_fieldupgradeexpired( self.player, level.superglobals.staticsuperdata["super_support_box"].id, self.kills, 0 );
    }
}

stoppingpower_onkill( var_0 )
{
    if ( isdefined( var_0 ) )
    {
        var_1 = var_0.basename;
        var_2 = self.hcrdata[var_1];

        if ( isdefined( var_2 ) )
        {
            scripts\mp\utility\stats::incpersstat( "stoppingPowerKills", 1 );
            scripts\mp\supers::combatrecordsuperkill( "super_support_box" );
            var_2.kills++;
        }
    }
}

stoppingpower_ishcrweapon( var_0 )
{
    var_1 = self.player getammotype( self.objweapon );
    var_2 = self.player getammotype( var_0 );
    var_3 = var_1 == var_2;
    return issameweapon( var_0, self.objweapon, 1 ) && var_3;
}

stoppingpower_clearhcrondeath()
{
    self.player endon( "disconnect" );
    self endon( "stoppingPower_removeHCR" );
    self.player waittill( "death" );
    thread stoppingpower_removehcr();
}

stoppingpower_clearhcrongameended()
{
    self.player endon( "disconnect" );
    self endon( "stoppingPower_removeHCR" );
    level waittill( "game_ended" );
    thread stoppingpower_removehcr();
}

stoppingpower_clearhcronperkscleared()
{
    self.player endon( "disconnect" );
    self endon( "stoppingPower_removeHCR" );
    self.player waittill( "all_perks_cleared" );
    thread stoppingpower_loadoutchangeremovehcr();
}

stoppingpower_givefastreload()
{
    self.player endon( "death_or_disconnect" );
    self.player scripts\mp\utility\perk::giveperk( "specialty_fastreload" );
    self.player scripts\engine\utility::waittill_any_3( "weapon_fired", "weapon_change", "stoppingPower_removeHCR" );
    self.player scripts\mp\utility\perk::removeperk( "specialty_fastreload" );
}

stoppingpower_breaksprint()
{
    self endon( "death_or_disconnect" );
    scripts\common\utility::allow_sprint( 0 );
    wait 0.4;
    scripts\common\utility::allow_sprint( 1 );
}
