// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    setup_callbacks();
    setup_bot_war();
}

setup_callbacks()
{
    level.bot_funcs["_encstr_9B610FCEC26B2B3AF20756BE3A435ADC5B"] = ::bot_war_think;
}

setup_bot_war()
{

}

bot_war_think()
{
    self notify( "_encstr_9C590ED9C543E7AB0BA02FFBAB1A1523" );
    self endon( "_encstr_9C590ED9C543E7AB0BA02FFBAB1A1523" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );

    for (;;)
    {
        self [[ self.personality_update_function ]]();
        wait 0.05;
    }
}
