// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

main()
{
    setdvar( "_encstr_81D20BF36960208CD93C7AB214", 1 );
    setdvar( "_encstr_944D0BCCD6B43322D911D079C1", 1 );
    setdvar( "_encstr_BC400A1BD360010D991FBA75", 0 );
    setdvar( "_encstr_80060B30A96FFDA30CF88A9E6F", 1000 );
    setdvar( "_encstr_AFD50A0121DB6D073F897B6B", 1 );
    setdvar( "_encstr_A1070BECB5E1DFE78B2531BC69", 8 );
    waitframe();
    setdvar( "_encstr_BE360B7D0FDFBD8F4FC7A9F88F", 2 );
}
