// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

baitedbydecoy()
{
    var_0 = scripts\cp_mp\vehicles\vehicle::vehicle_getleveldataforvehicle( "veh_a10fd", 1 );
    var_0.destroycallback = ::backtruck;
    var_0._id_12CA3 = "tur_gun_fd_mp";
    balloon_deposit_cash_vo_explanation();
    balloon_deposit();
    balloon_deposit_monitor();
    ballistsglobalsettings();
    ballistics_weaponswitchmonitor();
    ballon_deposit_nag_stopper();

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "veh_a10fd", "init" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "veh_a10fd", "init" ) ]]();

    balloon_hint_logic();
    level.bhadriotshield = getdvarint( "scr_br_dauntless_start_in_the_air", 0 );
    level.bdiedonce = getdvarint( "scr_br_dauntless_drop_bomb_ammo", 1 );
    level.bbeingelectrocuted = getdvarint( "scr_br_dauntless_auto_refill_drop_bomb_time", 15 );
    level.bettermissiontierbonuses = getdvarint( "scr_br_dauntless_speed_no_damage", 75 );
    level.besttimestate = getdvarint( "scr_br_dauntless_speed_little_damage", 115 );
    level.bearwatch = getdvarint( "scr_br_dauntless_drop_bomb_cooldown_ms", 6000 );
    level.airplanedropbombvehiclehppercdmg = getdvarfloat( "scr_br_dauntless_drop_bomb_vehicle_dmg", 0.85 );
    level.beaker_end_time = getdvarfloat( "scr_br_dauntless_gunner_time_between_bullets", 0.1 );
    level.bdroppingshield = getdvarint( "scr_br_dauntless_enable_sonar", 1 );
    level.bestplayer = getdvarint( "scr_br_dauntless_sonar_scan_angle", 30 );
    level.besttime = getdvarint( "scr_br_dauntless_sonar_scan_range", 8000 );
    level.being_hacked = getdvarfloat( "scr_br_dauntless_sonar_scan_accuracy", 0.9 );
    level.bearsred = getdvarfloat( "scr_br_dauntless_pitch_collision_value", 20 );
    level.begin_spectate = getdvarfloat( "scr_br_dauntless_roll_collision_value", 20 );
    level.airplaneminspeedshowcontrail = getdvarint( "scr_br_dauntless_contrails_min_speed", 70 );
    level.ispointnearsoloascenderline = getdvarfloat( "scr_fd_dmg_factor_fuselage", 1.0 );
    level.isprogressionmismatch = getdvarfloat( "scr_fd_dmg_factor_tail_stabilizer", 1.0 );
    level.ispresstofirstspawnmode = getdvarfloat( "scr_fd_dmg_factor_main_rotor", 1.2 );
    level.isprogressionlevel = getdvarfloat( "scr_fd_dmg_factor_tail_rotor", 1.0 );
    level.ispointpaststart2d = getdvarfloat( "scr_fd_dmg_factor_landing_gear", 0.5 );
    level.ispointnearcurrentsafecircle = getdvarfloat( "scr_fd_dmg_factor_driverless_collision", 10.0 );
    level.israndomarloadouts = getdvarfloat( "scr_fd_impulse_dmg_threshold_high", 0.9 );
    level.isquesttablet = getdvarfloat( "scr_fd_impulse_dmg_threshold_mid", 0.9 );
    level.isquestinstancealocale = getdvarfloat( "scr_fd_impulse_dmg_threshold_low", 0.1 );
    level.isprophunt = getdvarfloat( "scr_fd_impulse_dmg_factor_low", 0.1 );
    level.ispubliceventoftypeactive = getdvarfloat( "scr_fd_impulse_dmg_factor_mid_low", 0.2 );
    level.isprophuntgametype = getdvarfloat( "scr_fd_impulse_dmg_factor_mid_high", 0.75 );
    level.israndomcustomblueprintsloadouts = getdvarfloat( "scr_fd_dmg_pitch_roll_threshold", 55.0 );
    level.israndomblueprintsloadouts = getdvarfloat( "scr_fd_dmg_pitch_roll_factor", 10.0 );
    level.israndomlmgloadouts = getdvarfloat( "scr_fd_wood_surf_dmg_scalar", 0.6 );
    balloon_deposit_cash_nags();
}

balloon_deposit_cash_nags()
{
    thread _id_12216();

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "veh_a10fd", "initLate" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "veh_a10fd", "initLate" ) ]]();

    level._effect["aircraft_bomb_explode"] = loadfx( "vfx/iw8_br/island/veh/vfx_br3_bomber_exp.vfx" );
    battle_tracks_getplayerdataenum();
}

balloon_deposit_cash_vo_explanation()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforvehicle( "veh_a10fd", 1 );
    var_0.enterstartcallback = ::backfire;
    var_0.enterendcallback = ::back_vector;
    var_0.exitstartcallback = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_exitstartcallback;
    var_0.exitendcallback = ::backhatch_delayshow;
    var_0.reentercallback = ::base_angles;
    var_0.restrictions = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getdriverrestrictions();
    var_0.exitextents["front"] = 175;
    var_0.exitextents["back"] = 180;
    var_0.exitextents["left"] = 68;
    var_0.exitextents["right"] = 68;
    var_0.exitextents["top"] = 138;
    var_0.exitextents["bottom"] = 0;
    var_0.allowairexit = 1;
    var_1 = "back_left";
    var_0.exitoffsets[var_1] = ( -130, 70, -45 );
    var_0.exitdirections[var_1] = "left";
    var_1 = "back_right";
    var_0.exitoffsets[var_1] = ( -130, -70, -45 );
    var_0.exitdirections[var_1] = "right";
    var_1 = "back";
    var_0.exitoffsets[var_1] = ( -255, 0, -45 );
    var_0.exitdirections[var_1] = "back";
    var_2 = [ "pilot", "gunner" ];
    var_3 = "pilot";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "veh_a10fd", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ "back_left", "back_right", "back" ];
    var_4.restrictions = scripts\cp_mp\vehicles\vehicle_occupancy::_id_12F8A();
    var_4._id_12C9C = getcompleteweaponname( "tur_gun_fd_mp" );
    var_4.animtag = "tag_seat_0";
    var_4.tomastrike_watchgameend = "ping_vehicle_pilot";
    var_3 = "gunner";
    var_4 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getleveldataforseat( "veh_a10fd", var_3, 1 );
    var_4.seatswitcharray = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_generateseatswitcharray( var_3, var_2 );
    var_4.exitids = [ "back_left", "back_right", "back" ];
    var_4.restrictions = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getpassivepassengerrestrictions();
    var_4.animtag = "tag_seat_2";
    var_4.tomastrike_watchgameend = "ping_vehicle_gunner";
}

balloon_deposit()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_interact::vehicle_interact_getleveldataforvehicle( "veh_a10fd", 1 );
    scripts\cp_mp\vehicles\vehicle_interact::_id_12F53( "veh_a10fd", "single", [ "pilot", "gunner" ] );
}

balloon_deposit_monitor()
{
    var_0 = scripts\cp_mp\utility\vehicle_omnvar_utility::_id_1301F( "veh_a10fd", 1 );
    var_0.id = 19;
    var_0.seatids["pilot"] = 0;
    var_0.seatids["gunner"] = 1;
    var_0._id_11DF2[0] = 0;
    var_0._id_11DF2[1] = 1;
    var_0._id_11DF3["pilot"]["little_bird_mp"] = 0;
    var_0._id_11DF3["pilot"]["tur_gun_fd_mp"] = 1;
    var_0._id_11DF3["gunner"]["little_bird_mp"] = 0;
    var_0._id_11DF3["gunner"]["tur_gun_fd_mp"] = 1;
}

ballistsglobalsettings()
{
    level.bears = getdvarfloat( "scr_br_dauntless_health_override", 3950 );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F23( "veh_a10fd", level.bears, undefined, undefined, undefined, 8 );
    var_0 = scripts\cp_mp\vehicles\vehicle_damage::vehicle_damage_getleveldataforvehicle( "veh_a10fd" );
    var_0.class = "heavy";
    var_1 = scripts\cp_mp\vehicles\vehicle_damage::_id_12F06( "veh_a10fd", "heavy" );
    var_1.too_far_dist = ::barkov_execution_path;
    var_1.total_killed = ::barkov_shooting_path_nostab;
    scripts\cp_mp\vehicles\vehicle_damage::_id_12EF7( "veh_a10fd" );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F2F( "veh_a10fd", 17 );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F2C( "veh_a10fd", ::barrel_think );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F28( "veh_a10fd", ::back_field_clip );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F2A( "veh_a10fd", "pilot", getdvarfloat( "armor_truck_damage_scale", 0.7 ) );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F29( "veh_a10fd", "pilot", getdvarfloat( "armor_truck_damage_clamp", 15 ) );
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F32( "little_bird_mp", 5 );
}

ballistics_weaponswitchmonitor()
{
    var_0 = _applydvarstosettings::_id_12EC9( "veh_a10fd", 1 );
    var_0.brc130airdropcratedestroycallback = 2;
    var_0.getignoreprops = 0.75;
    var_0.get_next_open_stop = 350;
    var_0.get_next_rein_group = 525;
    var_0.get_next_cypher_id_from_pool = 875;
    var_0.get_node_closest_to_target_loc = 5;
    var_0.get_num_dogtag_in_kill_zone_or_under_bridge_zone = 20;
    var_0.get_next_track_index = 40;
    var_0.get_other_active_zone = 0;
    var_0.get_paired_bombvest_chair = 0;
    var_0.get_omnvar_value_based_on_bomb_label = 0;
}

ballon_deposit_nag_stopper()
{
    level._effect["aircraft_explode"] = loadfx( "vfx/iw8_br/island/veh/vfx_br3_dauntless_death_exp.vfx" );
}

badpathnodes()
{
    var_0 = scripts\cp_mp\vehicles\vehicle::vehicle_getleveldataforvehicle( "veh_a10fd" );
    return var_0._id_12CA3;
}

awardstadiumblueprint( var_0, var_1 )
{
    if ( !isdefined( var_0.angles ) )
        var_0.angles = ( 0, 0, 0 );

    var_0.modelname = "veh_s4_mil_air_dalpha_wz";
    var_0.targetname = "veh_a10fd";

    if ( !isdefined( var_0.vehicletype ) )
        var_0.vehicletype = "a10_warthog_fd";

    var_2 = scripts\cp_mp\vehicles\vehicle_tracking::_spawnvehicle( var_0, var_1 );

    if ( !isdefined( var_2 ) )
        return undefined;

    var_3 = badpathnodes();
    var_4 = backwallkeypad();
    var_5 = back_door_enemy_watcher( var_2, var_3, "veh_s4_mil_air_dalpha_wz_turret_attach", var_4.tag, var_4.tagoffset );
    scripts\cp_mp\vehicles\vehicle::_id_12FB5( var_2, var_5, getcompleteweaponname( var_3 ) );
    scripts\cp_mp\vehicles\vehicle::_id_12EF2( var_2, "veh_a10fd", var_0 );
    var_2.objweapon = getcompleteweaponname( "little_bird_mp" );
    var_2._id_12CA3 = var_3;
    var_2.sound_distraction_mechanic_init = 3;
    var_2.hoverpos = level.bdiedonce;
    var_2.payload = 0;
    var_2 thread aircrafthastakenoff();
    _applysalesdiscount::_id_12EE5( var_2 );
    scripts\cp_mp\vehicles\vehicle::_id_12EF3( var_2, var_0 );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "veh_a10fd", "create" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "veh_a10fd", "create" ) ]]( var_2 );

    var_2 thread fadeoverlay();
    return var_2;
}

fadeoverlay()
{
    self endon( "death" );
    self vehphys_enablecollisioncallback( 1 );

    if ( getdvarint( "scr_br_fd_invincible", 0 ) )
        return;

    for (;;)
    {
        self waittill( "collision", var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 );

        if ( isdefined( var_7 ) && isdefined( var_7.helperdronetype ) && var_7.helperdronetype == "radar_drone_recon" )
            continue;

        if ( !istrue( self.payload ) )
            continue;

        var_9 = abs( angleclamp180( self.angles[0] ) );

        if ( var_9 < level.bearsred && abs( self.angles[2] ) < level.begin_spectate && var_7.origin[2] < self.origin[2] )
            continue;

        var_10 = 1.0;

        switch ( var_8 )
        {
            case 0:
                var_10 = level.ispointnearsoloascenderline;
                break;
            case 1:
                var_10 = level.isprogressionmismatch;
                break;
            case 2:
                var_10 = level.ispresstofirstspawnmode;
                break;
            case 3:
                var_10 = level.isprogressionlevel;
                break;
            case 4:
                var_10 = level.ispointpaststart2d;
                break;
        }

        var_11 = var_6 * var_10;
        var_12 = self.angles[0];

        if ( var_12 > 180 )
            var_12 = var_12 - 360;

        if ( abs( var_12 > level.israndomcustomblueprintsloadouts ) )
            var_11 = var_11 * level.israndomblueprintsloadouts;

        var_13 = self.angles[2];

        if ( var_13 > 180 )
            var_13 = var_13 - 360;

        if ( abs( var_13 > level.israndomcustomblueprintsloadouts ) )
            var_11 = var_11 * level.israndomblueprintsloadouts;

        var_14 = 0;

        if ( var_11 > level.israndomarloadouts )
            var_14 = self.maxhealth;
        else if ( var_11 > level.isquesttablet )
        {
            var_15 = level.israndomarloadouts - level.isquesttablet;
            var_16 = ( var_11 - level.isquesttablet ) / var_15;
            var_17 = self.maxhealth * level.ispubliceventoftypeactive;
            var_18 = self.maxhealth * level.isprophuntgametype;
            var_14 = scripts\engine\math::lerp( var_17, var_18, var_16 );
        }
        else if ( var_11 > level.isquestinstancealocale )
            var_14 = self.maxhealth * level.isprophunt;

        var_19 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_getdriver( self );

        if ( !isdefined( var_19 ) )
            var_14 = var_14 * level.ispointnearcurrentsafecircle;
        else if ( self vehicle_getspeed() < level.bettermissiontierbonuses )
            var_14 = 0;
        else if ( self vehicle_getspeed() < level.besttimestate )
            var_14 = 100;

        if ( var_14 > 0 )
        {
            if ( isdefined( var_19 ) && var_3 == 11534336 )
                var_14 = var_14 * level.israndomlmgloadouts;

            scripts\cp_mp\vehicles\vehicle_damage::_id_12EFD( 1 );
            self dodamage( var_14, var_4, undefined, undefined, "MOD_CRUSH" );
            scripts\cp_mp\vehicles\vehicle_damage::_id_12EFD( 0 );
        }

        wait 0.5;
    }
}

backwallkeypad()
{
    var_0 = spawnstruct();

    if ( getdvarint( "aircraft_turret_tag_animate", 0 ) == 1 )
    {
        iprintlnbold( "=== tag_body_animate ===" );
        var_0.tag = "tag_body_animate";
        var_0.tagoffset = ( 58.87, 0, 60.052 );
    }
    else
    {
        var_0.tag = "tag_turret";
        var_0.tagoffset = ( 0, 0, 0 );
    }

    return var_0;
}

back_door_enemy_watcher( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = spawnturret( "misc_turret", var_0 gettagorigin( var_3 ), var_1, 0 );
    var_5 linkto( var_0, var_3, var_4, ( 0, 0, 0 ) );
    var_5 setmodel( var_2 );
    var_5 setmode( "sentry_offline" );
    var_5 setsentryowner( undefined );
    var_5 makeunusable();
    var_5 setdefaultdroppitch( 0 );
    var_5 setturretmodechangewait( 1 );
    var_5.angles = var_0.angles;
    var_5.vehicle = var_0;
    var_5.maxhealth = 999999;
    var_5.health = var_5.maxhealth;
    return var_5;
}

backtruck( var_0, var_1 )
{
    if ( !isdefined( var_0 ) )
    {
        var_0 = spawnstruct();
        var_0.inflictor = self;
        var_0.objweapon = "little_bird_mp";
        var_0.meansofdeath = "MOD_EXPLOSIVE";
    }

    if ( !istrue( level.suppressvehicleexplosion ) )
    {
        self notify( "predeath" );
        wait 0.2;
    }

    scripts\cp_mp\vehicles\vehicle_damage::_id_12F1B( var_0 );

    if ( !istrue( level.suppressvehicleexplosion ) )
        waitframe();

    self setscriptablepartstate( "fx", "base" );
    scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_killoccupants( self, var_0 );
    scripts\cp_mp\vehicles\vehicle_damage::vehicle_damage_clearvisuals( undefined, undefined, 1 );
    thread back_struct();

    if ( !istrue( level.suppressvehicleexplosion ) )
    {
        var_2 = self gettagorigin( "tag_origin" );
        var_3 = scripts\engine\utility::ter_op( isdefined( var_0.attacker ), var_0.attacker, self );
        self radiusdamage( var_2, 256, 200, 80, var_3, "MOD_EXPLOSIVE", "little_bird_mp" );
        playfx( scripts\engine\utility::getfx( "aircraft_explode" ), var_2, anglestoforward( self.angles ), anglestoup( self.angles ) );
        playsoundatpos( var_2, "car_explode" );
        earthquake( 0.4, 800, var_2, 0.7 );
        playrumbleonposition( "grenade_rumble", var_2 );
        physicsexplosionsphere( var_2, 500, 200, 1 );
    }
}

aircrafthastakenoff()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "death" );
    var_0.pbexploitstarttime = 0;

    for (;;)
    {
        var_1 = scripts\engine\trace::create_contents( 0, 1, 1, 1, 0, 0, 0 );
        var_2 = [ var_0 ];
        var_3 = scripts\engine\trace::ray_trace( var_0.origin, var_0.origin - ( 0, 0, 250 ), var_2, var_1, 0 );

        if ( isdefined( var_3 ) )
        {
            if ( var_3["hittype"] == "hittype_none" )
                var_0.payload = 1;
        }

        if ( self vehicle_getspeed() < 35 )
        {
            var_0.payload = 0;
            var_0.pbexploitstarttime = 0;
        }

        if ( self vehicle_getspeed() > 35 && var_0.pbexploitstarttime == 0 )
        {
            var_0 playsoundonmovingent( "s4_dalpha_takeoff_rev" );
            var_0.pbexploitstarttime = 1;
        }

        wait 1.5;
    }
}

back_struct()
{
    scripts\cp_mp\vehicles\vehicle::_id_12F3B( self );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "veh_a10fd", "delete" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "veh_a10fd", "delete" ) ]]( self );

    waitframe();
    scripts\cp_mp\vehicles\vehicle::_id_12F3C( self );
}

barrel_think( var_0 )
{
    if ( scripts\cp_mp\vehicles\vehicle_interact::_id_12F62( self, "armor" ) )
        var_0.damage = var_0.damage * backup_deposit();

    if ( isdefined( var_0.damage ) && var_0.damage > 0 )
        self notify( "damage_taken", var_0 );

    return 1;
}

backup_deposit()
{
    return 0.8333;
}

back_field_clip( var_0 )
{
    thread backtruck( var_0 );
    return 1;
}

barkov_execution_path( var_0, var_1 )
{
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F1C( var_0, var_1 );
}

barkov_shooting_path_nostab( var_0, var_1 )
{
    scripts\cp_mp\vehicles\vehicle_damage::_id_12F20( var_0, var_1 );
}

_id_12216()
{
    level.battle_station_combat_logic = spawnstruct();
    level.battle_station_combat_logic.powers = [];
    antennae( level.battle_station_combat_logic, "dropbomb", "+smoke", ::battle_tracks_createexternallisteningzone );
    antennae( level.battle_station_combat_logic, "pilotgunner", "+attack", ::battle_tracks_hasemptybattletracks );
    antennae( level.battle_station_combat_logic, "lookback", "+melee_zoom", ::battle_tracks_isbattletracksowner );
    antennae( level.battle_station_combat_logic, "airplaneping", "+breath_sprint", ::battle_tracks_monitorstandingonvehicles );
}

_id_12FDE( var_0 )
{
    if ( isbot( self ) )
        return;

    foreach ( var_6, var_2 in var_0.powers )
    {
        foreach ( var_4 in var_2.calculate_zone_node_extents )
            self notifyonplayercommand( var_6, var_4 );
    }
}

_id_12FDD( var_0 )
{
    if ( isbot( self ) )
        return;

    foreach ( var_6, var_2 in var_0.powers )
    {
        foreach ( var_4 in var_2.calculate_zone_node_extents )
            self notifyonplayercommandremove( var_6, var_4 );
    }
}

antennae( var_0, var_1, var_2, var_3 )
{
    if ( isstring( var_2 ) )
        var_2 = [ var_2 ];

    var_0.powers[var_1] = spawnstruct();
    var_0.powers[var_1].calculate_zone_node_extents = var_2;
    var_0.powers[var_1].func = var_3;
}

battle_tracks_isbattletracksowner( var_0, var_1 )
{
    var_2 = self;

    if ( !isdefined( var_2.beardone ) )
        var_2.beardone = 0;

    if ( istrue( var_2.beardone ) )
    {
        var_2 cameraunlink();
        var_2.vehicle setentityowner( var_2 );
        var_2 controlslinkto( var_2.vehicle );
        var_2.beardone = 0;
    }
    else
    {
        var_2 controlsunlink();
        var_2.vehicle setentityowner( undefined );
        var_2 cameralinkto( var_2.vehicle, "tag_camera_front" );
        var_2.beardone = 1;
    }
}

battle_tracks_monitorstandingonvehicles( var_0, var_1 )
{
    var_2 = self;
    level endon( "game_ended" );
    var_2 endon( "disconnect" );
    var_2 setperk( "specialty_radarblip", 1 );
    var_2._id_12345 = 1;
    var_2.radarmode = "normal_radar";
    var_2.hasradar = 1;
    waitframe();
    var_2._id_12345 = undefined;
    var_2.hasradar = 0;
    var_2 unsetperk( "specialty_radarblip", 1 );
}

battle_tracks_hasemptybattletracks( var_0, var_1 )
{
    var_2 = self;

    if ( !isdefined( var_2.vehicle ) )
        return;

    var_2.vehicle.turret.turreton = 1;
    var_2.vehicle.turret setmode( "manual" );
    var_2 thread battle_tracks_hidetogglewidget();
}

battle_tracks_hidetogglewidget()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "disconnect" );
    var_0 endon( "exiting_pilot_seat_aircraft" );
    var_0.vehicle endon( "death" );
    var_1 = var_0.vehicle.turret;
    var_2 = 6;

    for (;;)
    {
        var_1 shootturret( "tag_flash", var_2 );
        wait( level.beaker_end_time );

        if ( !var_0 attackbuttonpressed() )
            return;
    }
}

battle_tracks_createexternallisteningzone( var_0, var_1 )
{
    var_2 = self;

    if ( !isdefined( var_2.vehicle.hoverpos ) )
        var_2.vehicle.hoverpos = 1;

    if ( var_2.vehicle.hoverpos < 1 )
    {
        if ( isdefined( level._id_122C7 ) )
            [[ level._id_122C7 ]]( "MP_WZ_ISLAND/DROP_BOMB_NO_AMMO" );

        var_2 playlocalsound( "br_pickup_deny" );
        return;
    }

    var_3 = scripts\engine\trace::create_contents( 0, 1, 1, 1, 0, 0, 0 );
    var_4 = [];
    var_5 = scripts\engine\trace::ray_trace( var_2.vehicle.origin, var_2.vehicle.origin - ( 0, 0, 475 ), var_4, var_3, 0 );

    if ( isdefined( var_5 ) )
    {
        if ( var_5["hittype"] != "hittype_none" )
        {
            if ( isdefined( level._id_122C7 ) )
                [[ level._id_122C7 ]]( "MP_WZ_ISLAND/DROP_BOMB_GROUND_TOO_CLOSE" );

            var_2 playlocalsound( "br_pickup_deny" );
            return;
        }
    }

    if ( istrue( var_2.vehicle.ref_anim ) )
        return;
    else
        var_2.vehicle.ref_anim = 1;

    var_2 thread battle_tracks_getsfxalias();
}

battle_tracks_getsfxalias()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "disconnect" );
    var_1 = var_0.vehicle;
    var_0 battle_tracks_playbattletrackswhenstandingonvehicle( var_1.hoverpos - 1 );
    var_0 thread battle_tracks_gettrackindex( var_1 );

    if ( isdefined( level.airplaneshowsplash ) )
    {
        foreach ( var_3 in level.players )
        {
            if ( var_0 == var_3 )
                continue;

            var_4 = distance2dsquared( var_3.origin, var_1.origin );

            if ( var_4 < 2250000 )
            {
                if ( var_0.team == var_3.team )
                {
                    var_3 thread [[ level.airplaneshowsplash ]]( "br_fd_bomb_alert_ally" );
                    continue;
                }

                var_3 thread [[ level.airplaneshowsplash ]]( "br_fd_bomb_alert_enemy" );
            }
        }
    }

    wait 0.5;

    if ( !isdefined( var_1 ) )
        return;

    var_1.hoverpos = var_1.hoverpos - 1;
    var_1.secondaryweaponbackup = gettime();
    var_1.ref_anim = 0;
    var_0 thread battle_tracks_clearbattletracks();
}

battle_tracks_clearbattletracks()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "disconnect" );
    var_0 endon( "fd_bomb_refill" );
    wait( level.bbeingelectrocuted );
    var_0 battle_tracks_getbattletracksid();
}

battle_tracks_gettrackindex( var_0 )
{
    var_1 = self;
    level endon( "game_ended" );
    var_1 endon( "disconnect" );

    if ( !isdefined( var_0 ) )
        return;

    var_2 = "veh8_mil_air_alfa10_db";
    var_3 = easepower( var_2, var_0.origin - ( 0, 0, 100 ), var_0.angles );
    var_3 setscriptablepartstate( "db", "db" );
    var_3.owner = var_1;
    var_1 playsoundtoplayer( "s4_dalpha_bomb_release", var_1 );
    var_4 = 0;

    while ( !var_4 )
    {
        var_5 = scripts\engine\trace::create_contents( 0, 1, 1, 1, 0, 0, 0 );
        var_6 = [];
        var_7 = scripts\engine\trace::ray_trace( var_3.origin, var_3.origin - ( 0, 0, 35 ), var_6, var_5, 0 );

        if ( isdefined( var_7 ) )
        {
            if ( var_7["hittype"] == "hittype_none" )
                var_3.origin = var_3.origin - ( 0, 0, 35 );
            else
            {
                var_3 aircraftexplodedropbomb();
                var_4 = 1;
            }
        }

        wait 0.05;
    }
}

aircraftexplodedropbomb()
{
    var_0 = self;

    if ( !isdefined( var_0.owner ) )
    {
        var_0 freescriptable();
        return;
    }

    var_1 = var_0.origin;
    playsoundatpos( var_1, "car_explode" );
    earthquake( 0.4, 800, var_1, 0.7 );
    playrumbleonposition( "grenade_rumble", var_1 );
    physicsexplosionsphere( var_1, 500, 200, 1 );
    var_2 = spawnfx( scripts\engine\utility::getfx( "aircraft_bomb_explode" ), var_1, anglestoforward( var_0.angles ), anglestoup( var_0.angles ) );
    var_2 forcenetfieldhighlod( 1 );
    triggerfx( var_2 );
    var_3 = [];

    if ( isdefined( level.mousetraps ) )
        var_3 = [[ level.mousetraps ]]( var_1, 700 );

    foreach ( var_5 in var_3 )
    {
        if ( var_5.team != var_0.owner.team )
            var_5 dodamage( 700, var_1, var_0.owner, var_0.owner, "MOD_EXPLOSIVE", "little_bird_mp" );
    }

    var_3 = [];

    if ( isdefined( level.mousetraps ) )
        var_3 = [[ level.mousetraps ]]( var_1, 1250 );

    foreach ( var_5 in var_3 )
    {
        var_5 earthquakeforplayer( 0.35, 2.0, var_1, 1250 );
        var_5 thread scripts\cp_mp\utility\shellshock_utility::_shellshock( "flash_grenade_mp", "top", 2.5, 1 );

        if ( var_5.team != var_0.owner.team )
            var_5 dodamage( 90, var_1, var_0.owner, var_0.owner, "MOD_EXPLOSIVE", "little_bird_mp" );
    }

    foreach ( var_10 in level.br_pickups.crates )
    {
        var_11 = distance( var_1, var_10.origin );

        if ( var_11 < 1250 )
            var_10 thread scripts\cp_mp\killstreaks\airdrop::destroycrate();
    }

    foreach ( var_14 in level.br_armory_kiosk.scriptables )
    {
        var_15 = distance( var_1, var_14.origin );

        if ( var_15 < 1250 )
        {
            if ( isdefined( var_14.visible ) )
            {
                if ( isdefined( level.hacking_vo ) )
                    [[ level.hacking_vo ]]( var_14 );
            }
        }
    }

    var_17 = canceljoins( undefined, undefined, var_1, 1250 );

    if ( isdefined( var_17 ) )
    {
        foreach ( var_19 in var_17 )
        {
            if ( !isdefined( var_19.courtyard_intel_sequence ) || var_19 == var_0 || var_19.type == "brloot_escape_radio" || var_19.type == "br_cargotrain" || var_19.type == "br_cargotrain_engine" )
                continue;

            if ( isdefined( level.sg_removequestinstance ) )
                [[ level.sg_removequestinstance ]]( var_19 );
        }
    }

    if ( isdefined( level.vehicle ) && isdefined( level.vehicle.instances ) )
    {
        foreach ( var_22 in level.vehicle.instances )
        {
            foreach ( var_24 in var_22 )
            {
                var_25 = distance( var_1, var_24.origin );

                if ( var_25 > 1250 )
                    continue;

                var_26 = int( var_24.maxhealth * level.airplanedropbombvehiclehppercdmg );
                var_24 dodamage( var_26, var_1, var_0.owner, var_0.owner, "MOD_EXPLOSIVE", "little_bird_mp" );
            }
        }
    }

    var_0 freescriptable();
}

battle_tracks_getplayerdataenum()
{
    level.battle_tracks_getnewtogglestate = getentarray( "veh_a10fd_reload_drop_bomb", "targetname" );

    foreach ( var_1 in level.battle_tracks_getnewtogglestate )
        level thread battle_tracks_getmusicstate( var_1 );
}

battle_tracks_getmusicstate( var_0 )
{
    level endon( "game_ended" );

    for (;;)
    {
        var_0 waittill( "trigger", var_1 );

        if ( isbot( var_1 ) || !isalive( var_1 ) )
            continue;

        if ( !isdefined( var_1.vehicle ) || !isdefined( var_1.vehicle.model ) || !isdefined( var_1.vehicle.hoverpos ) || var_1.vehicle.model != "veh_s4_mil_air_alfa_test_wz" || var_1.vehicle.hoverpos >= level.bdiedonce )
            continue;

        if ( isdefined( var_1.vehicle.secondaryweaponbackup ) )
        {
            var_2 = var_1.vehicle.secondaryweaponbackup + level.bearwatch;

            if ( var_2 > gettime() )
                continue;
        }

        if ( isdefined( level.beacon ) )
            var_1 thread [[ level.beacon ]]( "br_fd_restock_bombs", 150 );

        if ( isdefined( level.begin_vo ) )
            var_1 thread [[ level.begin_vo ]]( "br_fd_restock_bombs" );

        var_1 battle_tracks_getbattletracksid();
    }
}

battle_tracks_getbattletracksid()
{
    var_0 = self;

    if ( !isdefined( var_0.vehicle ) )
        return;

    if ( var_0.vehicle.hoverpos == level.bdiedonce )
        return;

    var_0.vehicle.hoverpos = level.bdiedonce;
    var_0 battle_tracks_playbattletrackswhenstandingonvehicle( level.bdiedonce );
    var_1 = soundexists( "plane_ch3_bomb_reload" );

    if ( var_1 )
        var_0 playsoundtoplayer( "plane_ch3_bomb_reload", var_0 );

    var_0 notify( "fd_bomb_refill" );
}

waitthensetvisibleteam( var_0, var_1 )
{
    var_2 = self;
    level endon( "game_ended" );
    var_2 endon( "death_or_disconnect" );
    var_2 endon( "exiting_aircraft" );
    var_2 endon( "exiting_pilot_seat_aircraft" );

    for (;;)
    {
        var_2 waittill( var_1 );
        waittillframeend;
        var_2 thread [[ var_0.powers[var_1].func ]]( var_0, var_1 );
    }
}

waitthensetgendersoundcontext( var_0 )
{
    var_1 = self;
    level endon( "game_ended" );
    var_1 endon( "death_or_disconnect" );
    var_1 endon( "exiting_aircraft" );
    var_1 endon( "exiting_pilot_seat_aircraft" );

    if ( isbot( var_1 ) )
        return;

    foreach ( var_4, var_3 in var_0.powers )
        var_1 thread waitthensetvisibleteam( var_0, var_4 );
}

backfire( var_0, var_1, var_2, var_3, var_4 )
{
    if ( isdefined( level.bhadriotshield ) && level.bhadriotshield > 0 )
        var_0.origin = var_0.origin + ( 0, 0, level.bhadriotshield );

    if ( istrue( level.bdroppingshield ) )
    {
        var_3 fulton_repositorycountdownendcallback();
        var_3 thread _id_12121();
    }

    var_0 thread aircraft_contrailthink();
    var_0 playsound( "s4_dalpha_startup_rev" );

    if ( var_1 == "pilot" )
    {
        var_3 thread _id_12FDE( level.battle_station_combat_logic );
        var_3 thread waitthensetgendersoundcontext( level.battle_station_combat_logic );
        var_3 thread battle_tracks_playbattletrackstoplayer();
        scripts\cp_mp\vehicles\vehicle_occupancy::_id_12F8E( var_3, var_4 );
        scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_giveturret( var_3, var_0._id_12CA3, var_4, 1 );
    }

    if ( var_1 == "gunner" )
        scripts\cp_mp\vehicles\vehicle_occupancy::_id_12F8E( var_3, var_4 );
    else if ( isdefined( var_2 ) && var_2 == "gunner" )
        scripts\cp_mp\vehicles\vehicle_occupancy::_id_12F8E( var_3, var_4 );
}

aircraft_contrailthink()
{
    var_0 = self;
    var_0 endon( "death" );
    level endon( "game_ended" );
    var_0.contrailson = 0;

    for (;;)
    {
        if ( istrue( var_0.contrailson ) )
        {
            if ( var_0 vehicle_getspeed() < level.airplaneminspeedshowcontrail )
            {
                var_0.contrailson = 0;
                var_0 setscriptablepartstate( "fx", "base", 0 );
            }
        }
        else if ( var_0 vehicle_getspeed() > level.airplaneminspeedshowcontrail )
        {
            var_0.contrailson = 1;
            var_0 setscriptablepartstate( "fx", "trails", 0 );
        }

        wait 5;
    }
}

back_vector( var_0, var_1, var_2, var_3, var_4 )
{
    if ( istrue( var_4.success ) )
        thread backendevent( var_0, var_1, var_2, var_3, var_4 );
    else if ( !istrue( var_4.playerdisconnect ) && !istrue( var_4.playerdeath ) )
    {
        if ( var_1 == "pilot" )
        {
            basic_combat( var_3 );
            scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_taketurret( var_3, var_0, var_0._id_12CA3, var_4, 1 );
        }
    }
}

backendevent( var_0, var_1, var_2, var_3, var_4 )
{
    var_5 = undefined;
    var_6 = undefined;

    if ( isdefined( var_2 ) && var_2 == "gunner" )
    {
        var_5 = "a10_warthog_fd";
        var_6 = 3;
    }

    if ( var_1 == "pilot" )
    {
        var_0 setotherent( var_3 );
        var_0 setentityowner( var_3 );
        var_3 controlslinkto( var_0 );

        if ( getdvarint( "scr_br_fd_uav_enabled", 1 ) )
            var_0 battle_tracks_onentervehicle( var_3 );

        thread scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_disablefirefortime( var_3, 0 );
        var_7 = scripts\cp_mp\vehicles\vehicle::_id_12F48( var_0, var_0._id_12CA3 );
        var_7.owner = var_3;
        var_3.vehicle.turret = var_7;
        avlinvel( var_3 );
    }

    var_3 thread scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_animateplayer( var_0, var_1, var_2, undefined, var_5, var_6 );
    thread scripts\cp_mp\vehicles\vehicle_occupancy::_id_12FA7( var_4, 1 );
    scripts\cp_mp\utility\vehicle_omnvar_utility::vehomn_updateomnvarsonseatenter( var_0, var_2, var_1, var_3 );
}

backhatch_delayshow( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !isdefined( var_2 ) )
    {
        if ( isdefined( var_1 ) && var_1 == "pilot" )
            var_3 notify( "exiting_pilot_seat_aircraft" );

        var_3 thread _id_12FDD( level.battle_station_combat_logic );
        var_3 battle_stations();
        var_3 notify( "exiting_aircraft" );
    }
    else if ( var_2 != "pilot" )
    {
        var_3 thread _id_12FDD( level.battle_station_combat_logic );
        var_3 battle_stations();
        var_3 notify( "exiting_pilot_seat_aircraft" );
    }

    if ( istrue( var_3.beardone ) )
    {
        var_3 cameraunlink();
        var_3.beardone = 0;
    }

    if ( istrue( var_4.success ) )
        backpack_dummy_spawn( var_0, var_1, var_2, var_3, var_4 );
}

backpack_dummy_spawn( var_0, var_1, var_2, var_3, var_4 )
{
    if ( var_1 == "pilot" )
    {
        var_0 setotherent( undefined );
        var_0 setentityowner( undefined );

        if ( getdvarint( "scr_br_fd_uav_enabled", 1 ) )
            var_0 thread battle_tracks_onexitvehicle();
    }

    var_5 = !isdefined( var_2 );

    if ( var_1 == "pilot" || var_5 && var_3 hasweapon( var_0._id_12CA3 ) )
    {
        var_6 = scripts\cp_mp\vehicles\vehicle::_id_12F48( var_0, var_0._id_12CA3 );

        if ( !istrue( var_4.playerdisconnect ) )
        {
            var_3 enableturretdismount();
            var_3 controlturretoff( var_6 );

            if ( !istrue( var_4.playerdeath ) )
                scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_taketurret( var_3, var_0, var_0._id_12CA3, var_4, 1 );

            thread scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_cleardisablefirefortime( var_3, var_4.playerdeath );
        }

        var_6.owner = undefined;
        var_6 setotherent( undefined );
        var_6 setentityowner( undefined );
        basic_combat( var_3 );
    }

    if ( !istrue( var_4.playerdisconnect ) )
    {
        var_3 controlsunlink();

        if ( istrue( var_4.playerdeath ) )
            var_3 scripts\cp_mp\vehicles\vehicle_occupancy::addlaststandoverheadiconcallback();

        var_3 scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_stopanimatingplayer();
        var_7 = scripts\cp_mp\vehicles\vehicle_occupancy::vehicle_occupancy_moveplayertoexit( var_3, var_2, var_4 );

        if ( !var_7 )
        {
            if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "vehicle_occupancy", "handleSuicideFromVehicles" ) )
                [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "vehicle_occupancy", "handleSuicideFromVehicles" ) ]]( var_3 );
            else
                var_3 suicide();
        }
    }

    scripts\cp_mp\utility\vehicle_omnvar_utility::vehomn_updateomnvarsonseatexit( var_0, var_1, var_2, var_3 );
}

avlinvel( var_0 )
{
    if ( isdefined( var_0.onplayerconnectrisk ) )
        return;

    var_0.onplayerconnectrisk = 1;
    var_1 = scripts\cp_mp\vehicles\vehicle::vehicle_getleveldataforvehicle( "veh_a10fd" );

    if ( istrue( var_1._id_12336 ) )
        return;

    var_0 scripts\cp_mp\utility\damage_utility::adddamagemodifier( "ctmgGunnerMissileRedux", 0.4, 0, ::bagentinitialized );
}

basic_combat( var_0 )
{
    if ( !isdefined( var_0.onplayerconnectrisk ) )
        return;

    var_0.onplayerconnectrisk = undefined;
    var_1 = scripts\cp_mp\vehicles\vehicle::vehicle_getleveldataforvehicle( "veh_a10fd" );

    if ( istrue( var_1._id_12336 ) )
        return;

    var_0 scripts\cp_mp\utility\damage_utility::removedamagemodifier( "ctmgGunnerMissileRedux", 0 );
}

bagentinitialized( var_0, var_1, var_2, var_3, var_4, var_5, var_6 )
{
    if ( var_4 != "MOD_PROJECTILE_SPLASH" && var_4 != "MOD_GRENADE_SPLASH" )
        return 1;

    if ( !isdefined( var_5 ) )
        return 1;

    switch ( var_5.basename )
    {
        case "tur_gun_fd_mp":
        case "iw8_la_gromeoks_mp":
        case "iw8_la_juliet_mp":
        case "iw8_la_rpapa7_mp":
        case "iw8_la_kgolf_mp":
        case "iw8_la_gromeo_mp":
        case "iw8_la_mike32_mp":
        case "iw8_la_t9launcher_mp":
        case "iw8_la_t9freefire_mp":
        case "iw8_la_t9standard_mp":
        case "lighttank_tur_mp":
            return 0;
        default:
            return 1;
    }
}

base_angles( var_0, var_1, var_2, var_3, var_4 )
{
    scripts\cp_mp\vehicles\vehicle_occupancy::_id_12FA7( var_4 );
    thread base_assault_intro_vo( var_0, var_1, var_2, var_3, var_4 );
}

base_assault_intro_vo( var_0, var_1, var_2, var_3, var_4 )
{
    if ( isdefined( var_2 ) && var_2 == "pilot" )
    {
        var_5 = scripts\cp_mp\vehicles\vehicle_occupancy::_id_12F8E( var_3, var_4 );
        scripts\cp_mp\vehicles\vehicle_occupancy::_id_12FA8( var_5 );
    }
}

_id_12BFF()
{
    return 1;
}

trophy_protectionsuccessful( var_0 )
{
    self._id_12C04--;
    var_1 = var_0.origin;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "vehicle_trophyDestroyTarget", "init" ) )
        [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "vehicle_trophyDestroyTarget", "init" ) ]]( var_0 );

    var_2 = trophy_getbesttag( var_1 );
    self setscriptablepartstate( "trophy_detonate", var_2 );
    var_3 = vectortoangles( self gettagorigin( var_2 ) - var_1 );
    var_4 = combineangles( var_3, ( -90, 0, 0 ) );

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "vehicle_trophyExplode", "init" ) )
        self.explosion thread [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "vehicle_trophyExplode", "init" ) ]]( var_1, var_4 );

    if ( self._id_12C04 == 0 )
    {
        self notify( "upgrade_message", "trophy_no_ammo" );
        self waittill( "trophy_ammo_refill" );
    }
    else
        self notify( "upgrade_message", "trophy_ammo_used" );
}

trophy_getbesttag( var_0 )
{
    var_1 = [ "tag_trophy_1", "tag_trophy_2", "tag_trophy_3", "tag_trophy_4" ];
    var_2 = undefined;
    var_3 = undefined;

    foreach ( var_8, var_5 in var_1 )
    {
        var_6 = self gettagorigin( var_5 );
        var_7 = distancesquared( var_6, var_0 );

        if ( var_8 == 0 || var_7 < var_2 )
        {
            var_2 = var_7;
            var_3 = var_5;
        }
    }

    return var_3;
}

battle_tracks_onentervehicle( var_0 )
{
    var_1 = self;
    var_2 = spawn( "script_model", var_1.origin );
    var_2 setmodel( "tag_origin" );
    var_2 linkto( var_1 );
    var_2 makeportableradar( var_0 );
    var_1.radar = var_2;
}

battle_tracks_onexitvehicle()
{
    level endon( "game_ended" );
    var_0 = self;

    if ( isdefined( var_0.radar ) )
        var_0.radar delete();
}

balloon_hint_logic()
{
    var_0 = scripts\cp_mp\vehicles\vehicle_spawn::vehicle_spawn_getleveldataforvehicle( "veh_a10fd", 1 );
    var_0.maxinstancecount = 2;
    var_0.priority = 75;
    var_0.getspawnstructscallback = ::backup_plane_locations;
    var_0.spawncallback = scripts\cp_mp\utility\script_utility::getsharedfunc( "veh_a10fd", "spawnCallback" );
    var_0.clearancecheckradius = 185;
    var_0.clearancecheckheight = 138;
    var_0.clearancecheckminradius = 185;
}

backup_plane_locations()
{
    if ( isdefined( level.trial_rpg_init ) && level.trial_rpg_init.size != 0 )
        var_0 = level.trial_rpg_init;
    else
        var_0 = scripts\engine\utility::getstructarray( "veh_a10fd", "targetname" );

    if ( var_0.size > 0 )
    {
        var_0 = scripts\cp_mp\vehicles\vehicle_spawn::vehicle_spawn_removespawnstructswithflag( var_0, 1 );

        if ( var_0.size > 1 )
            var_0 = scripts\engine\utility::array_randomize( var_0 );
    }

    return var_0;
}

battle_tracks_playbattletrackstoplayer()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "death" );
    var_0 endon( "exiting_pilot_seat_aircraft" );
    var_1 = -40;
    var_2 = -135;
    var_3 = 40;
    var_4 = -135;
    var_0.battle_tracks_createdefaultlisteningzone = var_0 vehiclecankillhealth( var_1, var_2, "right", "middle", "center", "bottom", &"MP_WZ_ISLAND/FD_DROP_BOMB_HUD", level.bdiedonce );
    var_0.battle_tracks_gettogglestate = var_0 vehiclecankillhealth( var_3, var_4, "left", "middle", "center", "bottom", &"MP_WZ_ISLAND/FD_IN_AIR_COUNTER" );

    while ( !isdefined( var_0.vehicle ) )
        wait 0.5;

    var_0 thread battle_tracks_playerinlisteningzone();
}

battle_stations()
{
    var_0 = self;

    if ( isdefined( var_0.battle_tracks_createdefaultlisteningzone ) )
        var_0.battle_tracks_createdefaultlisteningzone destroy();

    if ( isdefined( var_0.battle_tracks_gettogglestate ) )
        var_0.battle_tracks_gettogglestate destroy();

    var_0.battle_tracks_createdefaultlisteningzone = undefined;
    var_0.battle_tracks_gettogglestate = undefined;
}

battle_tracks_playbattletrackswhenstandingonvehicle( var_0 )
{
    var_1 = self;

    if ( !isdefined( var_1.vehicle ) )
        return;

    if ( var_0 <= 0 )
        var_1.battle_tracks_createdefaultlisteningzone thread playerattractiontriggerenter();

    var_1.battle_tracks_createdefaultlisteningzone setvalue( var_0 );
}

battle_tracks_playerinlisteningzone()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "death" );
    var_0 endon( "exiting_pilot_seat_aircraft" );

    for (;;)
    {
        if ( !isdefined( var_0.vehicle ) )
            return;

        var_1 = 0;

        foreach ( var_3 in level.vehicle.instances["veh_a10fd"] )
        {
            if ( istrue( var_3.payload ) )
                var_1++;
        }

        var_0.battle_tracks_gettogglestate setvalue( var_1 );
        wait 3;
    }
}

vehiclecankillhealth( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7 )
{
    var_8 = fulton_repositoryextractcallback( "default", 1.5 );
    var_8.x = var_0;
    var_8.y = var_1;
    var_8.alignx = var_2;
    var_8.aligny = var_3;
    var_8.horzalign = var_4;
    var_8.vertalign = var_5;
    var_8.alpha = 1;
    var_8.glowalpha = 0;
    var_8.hidewheninmenu = 1;
    var_8.archived = 0;

    if ( isdefined( var_6 ) )
        var_8.label = var_6;

    if ( isdefined( var_7 ) )
        var_8 setvalue( var_7 );

    return var_8;
}

playerattractiontriggerenter()
{
    self endon( "death" );
    var_0 = ( 1, 0, 0 );

    if ( istrue( self._id_119FA ) )
        return;

    var_1 = 0.3;
    var_2 = 1.5;
    self._id_119FA = 1;
    var_3 = self.fontscale;
    var_4 = self.color;

    if ( isdefined( var_0 ) )
        self.color = var_0;

    self changefontscaleovertime( var_1 );
    self.fontscale = var_2;
    wait( var_1 );
    self changefontscaleovertime( var_1 );
    self.fontscale = var_3;
    wait( var_1 );
    self.color = var_4;
    self._id_119FA = undefined;
}

fulton_repositoryextractcallback( var_0, var_1 )
{
    var_2 = newclienthudelem( self );
    var_2.elemtype = "font";
    var_2.font = var_0;
    var_2.fontscale = var_1;
    var_2.basefontscale = var_1;
    var_2.x = 0;
    var_2.y = 0;
    var_2.width = 0;
    var_2.height = int( level.fontheight * var_1 );
    var_2.xoffset = 0;
    var_2.yoffset = 0;
    var_2.children = [];
    var_2.hidden = 0;
    return var_2;
}

fulton_repositorycountdownendcallback()
{
    self.bearsetup = spawnstruct();
    self.bearsetup._id_12909 = [];
}

_id_12121()
{
    var_0 = self;
    level endon( "game_ended" );
    var_0 endon( "death" );
    wait 2;

    while ( isdefined( var_0.vehicle ) )
    {
        foreach ( var_2 in level.players )
        {
            if ( var_2.team == var_0.team )
                continue;

            if ( isdefined( var_2.vehicle ) && isdefined( var_2.vehicle.targetname ) && var_2.vehicle.targetname == "veh_a10fd" )
                var_0 thread being_kicked_from_inactivity( var_2 );
        }

        [var_5, var_6] = mp_runner_patch();

        foreach ( var_2 in level.players )
        {
            if ( var_2.team == var_0.team )
                continue;

            if ( isdefined( level.airplanehasperk ) )
            {
                if ( var_2 [[ level.airplanehasperk ]]( "specialty_guerrilla" ) || var_2 [[ level.airplanehasperk ]]( "specialty_covert_ops" ) )
                    continue;
            }

            var_8 = triangletest( var_2.origin, var_0.vehicle.origin, var_5, var_6 );

            if ( istrue( var_8 ) )
                var_0 thread being_kicked_from_inactivity( var_2 );
        }

        wait 5;
    }
}

mp_runner_patch()
{
    var_0 = self;
    var_0 notify( "get_sonar_cone_scan_vertices" );
    var_0 endon( "get_sonar_cone_scan_vertices" );
    var_1 = var_0.vehicle.origin;
    var_2 = anglestoforward( var_0.vehicle.angles );
    var_3 = vectorcross( var_2, ( 0, 0, 1 ) );
    var_4 = var_2 * level.besttime * cos( level.bestplayer );
    var_5 = level.besttime * sin( level.bestplayer );
    var_6 = [];
    var_7 = ( 0, 0, 0 );
    var_8 = undefined;
    var_9 = undefined;

    for ( var_10 = 0; var_10 < 2; var_10++ )
    {
        var_11 = var_10 / 2 * 360;
        var_12 = var_1 + var_4 + var_5 * ( var_3 * cos( var_11 ) );
        var_7 = var_12;

        if ( isdefined( var_9 ) )
        {
            var_8 = var_12;
            continue;
        }

        var_9 = var_12;
    }

    return [ var_8, var_9 ];
}

triangletest( var_0, var_1, var_2, var_3 )
{
    var_4 = ispointintriangle( var_0, var_1, var_2, var_3 );

    if ( var_4 )
        return 1;
    else
        return 0;
}

ispointintriangle( var_0, var_1, var_2, var_3 )
{
    if ( !isright( var_0, var_1, var_2 ) )
        return 0;

    if ( !isright( var_0, var_2, var_3 ) )
        return 0;

    if ( !isright( var_0, var_3, var_1 ) )
        return 0;

    return 1;
}

isright( var_0, var_1, var_2 )
{
    return ( var_2[0] - var_1[0] ) * ( var_0[1] - var_1[1] ) - ( var_0[0] - var_1[0] ) * ( var_2[1] - var_1[1] ) < 0;
}

being_kicked_from_inactivity( var_0 )
{
    var_1 = self;
    level endon( "game_ended" );
    var_1 endon( "death_or_disconnect" );
    var_2 = "hud_icon_head_marked";
    var_3 = 8;
    var_4 = 1;
    var_5 = 500;
    var_6 = 40000;
    var_1.bearsetup._id_12909[var_0 getentitynumber()] = var_0;
    var_7 = var_0;
    var_7.headicon = var_0 scripts\cp_mp\entityheadicons::setheadicon_singleimage( var_1, var_2, var_3, var_4, var_6, var_5, undefined, 1, 1 );
    var_1 below_player_eye_allowance( var_0 );
    var_1 being_pickedup( var_0 );
}

below_player_eye_allowance( var_0 )
{
    var_1 = self;
    var_1 endon( "death_or_disconnect" );
    var_2 = var_0 getentitynumber();
    var_0 scripts\engine\utility::waittill_notify_or_timeout( "death_or_disconnect", 4.0 );
}

being_pickedup( var_0 )
{
    var_1 = self;
    var_2 = var_0 getentitynumber();

    if ( isdefined( var_1.bearsetup ) && isdefined( var_1.bearsetup._id_12909 ) )
    {
        var_3 = var_1.bearsetup._id_12909[var_2];

        if ( isdefined( var_3 ) && isdefined( var_3.headicon ) )
        {
            scripts\cp_mp\entityheadicons::setheadicon_deleteicon( var_3.headicon );
            var_1.bearsetup._id_12909[var_2] = undefined;
        }
    }
}
