// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

_encstr_9BE21324273AEF0F31D9124BC8D991C8581401A802()
{
    for (;;)
    {
        level waittill( "_encstr_AA580E0A8D91B6D74E1142DA7E263FAB", var_0 );
        var_1 = [];

        if ( isdefined( level._id_11E18.seq3_tanksettings ) )
        {
            for ( var_2 = 0; var_2 < level._id_11E18.seq3_tanksettings.size; var_2++ )
            {
                var_3 = level._id_11E18.seq3_tanksettings[var_2].origin;
                var_1[var_2] = _encstr_9FCA36B673DB38F9031352583B8D9F71DF1DBD2BD82FA3BF6F2B08A0B2B5D7690B8546282F1FEB4196B330B9BACE07E0BF26C51EF69753B7::_encstr_B3390E37087EEB8A6D1579AA081B3294( var_3 );
            }
        }

        var_4 = [];

        if ( isdefined( level._id_11E18.wait_for_player_eliminated ) )
        {
            for ( var_2 = 0; var_2 < level._id_11E18.wait_for_player_eliminated.size; var_2++ )
                var_4[var_2] = _encstr_9FCA36B673DB38F9031352583B8D9F71DF1DBD2BD82FA3BF6F2B08A0B2B5D7690B8546282F1FEB4196B330B9BACE07E0BF26C51EF69753B7::_encstr_B3390E37087EEB8A6D1579AA081B3294( level._id_11E18.wait_for_player_eliminated[var_2] );
        }
    }
}
