// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    if ( !getdvarint( "_encstr_8F1414201B1B01E69B063E412C088815216DE1AA13C2", 0 ) )
        return;

    level.disable_super_in_turret.brmayconsiderplayerdead = 1;
    level.disable_super_in_turret._id_146E7 = 1;
    level.disable_super_in_turret._id_146C9 = init_warning_levels();
    level.disable_super_in_turret._id_146BD = getdvarint( "_encstr_BE8412D6B64BD72912278088836720EB021DCDD3", 300 );
    level.disable_super_in_turret._id_146F1 = getdvarint( "_encstr_8C7920D389DE977660477A70F1E1B88F8901CA3A13AD27EDC02F9D4AF728C6DF25DB", 0 );
    level.disable_super_in_turret._id_146F2 = getdvarint( "_encstr_9309262397C081D3668ECBF373287B45C07DA1BD0FD9569787A132D9781943BC28C704015BA81F7F", 80 );
    level.disable_super_in_turret._id_146F8 = getdvarint( "_encstr_8153297B21762FCEC8DF12089979102711F95282CC44B3C5A083361D41E01E534DB5BB5BF0280FBC70ED2B", 1 );
    level.disable_super_in_turret.brking_movenextcirclecenter = getdvarint( "_encstr_81E41C9BB139F5C493AF3D1E07D7C2D8C6F6DDEBE9DBDA895ACA7DD558EC", 1 );
    level.disable_super_in_turret._id_146D5 = getdvarfloat( "_encstr_8F1D15C710434F32FDB0B8300FFF4B31A848FF5BA83BAD", -1 );
    level.disable_super_in_turret._id_146D6 = getdvarfloat( "_encstr_9C4D159BC69CBEC44ED79E0F07AFC1A5DCCEFA8ED2D695", 0.5 );
    level.disable_super_in_turret._id_146D2 = getdvarint( "_encstr_9FBC173B629BE058DA1FCDC158C960BD4F19B1205A672DE837", 2 );
    level.disable_super_in_turret._id_146E5 = getdvarfloat( "_encstr_943423F05AF2CF39B3DFBAB3E8DFE3731F829009234EC1912F1BCE27DC5F0ED385C96070AB", 1.0 );
    level.disable_super_in_turret._id_146E6 = getdvarfloat( "_encstr_AB1524B3069219D6CB8F0DF1CBE1262B5F1F988EEAE9381D311737CB936AF808E5B326015643", 0.5 );
    level.disable_super_in_turret._id_146E3 = getdvarfloat( "_encstr_B7282413491E57B6A0873A30B1A1FAE7CC217A59317D53AEC09F4B33ABE0C7C76338E14279CE", 1.0 );
    level.disable_super_in_turret._id_146E4 = getdvarfloat( "_encstr_A3E22506B19B0126B2FF082B13A71382F1DD7087C7F1ED590379B26B2ED927AF6873E3473A1FBB", 1.5 );
    level.disable_super_in_turret._id_146E2 = getdvarint( "_encstr_BDF012DCB14E7D3193FAE9F01CF50EB7775693E6", 1 );
    level.disable_super_in_turret._id_12820 = getdvarint( "_encstr_82C71B37B1C9BEC439D7D3E10E7D0EF6BBACE437EBD8EDDED8917BBB73", 1 );
    level.disable_super_in_turret._id_146CF = getdvarfloat( "_encstr_97C1136EB193F53193EB9EF00E7DCDD5B5212DE8E6", 3 );
    level.disable_super_in_turret._id_146D0 = getdvarfloat( "_encstr_8BA717378DC9FAC4E4F5E90F077DB9AEB5212DA3DC94AE9DEC", 20 );
    level.disable_super_in_turret._id_146BF = getdvarint( "_encstr_8B0B17A6C63BA7596277D03833B7F01F226D9E25D653BBA04A", 1 );
    level.disable_super_in_turret._id_146E8 = getdvarint( "_encstr_AD95213A77AB76D6A8F1EAF241092BCD7672CA875B9F300A9DA3DC4794F8070D0F6902", 1 );
    level.disable_super_in_turret._id_146CE = getdvarfloat( "_encstr_9B96176F907A1F9993A7E26B01B1A08BB519E883B3C1357327", 2 );
    level.disable_super_in_turret._id_146CC = getdvarfloat( "_encstr_8B7F16238A63AFF1E08990A0389FDB2B51A9273BB8996013", 2 );
    level.disable_super_in_turret._id_146CD = getdvarfloat( "_encstr_AA7F1667C19B596BCEE73810A2D91D4B60D1835B439707FB", 3 );
    level.disable_super_in_turret._id_146D1 = getdvarfloat( "_encstr_A42D18CB498B51EACDE1E0F1375060AD7D7348C06351A2ABCE78", 4 );
    level.disable_super_in_turret._id_146FC = getdvarint( "_encstr_AAAA15BBE21B60D85A9F4D41D84908BFFF1B90A62A8F2E", 1 );
    level.disable_super_in_turret._id_1470A = getdvarint( "_encstr_A3BB1D43372DBF4D12570278133F13483853B330759EE188C87313DC4980CC", 0 );
    level.disable_super_in_turret._id_146FB = getdvarint( "_encstr_B49F1E234F22B118B3DFCB0B3F77D8A87AE1914547C7E830E33D69DF8E62B36B", 0 );
    level.disable_super_in_turret.spawndragonsbreathstruct = getdvarint( "_encstr_B8D91BB673DBFEDD82D1F8F03B9181F3DF19B038DB7BE10F6DF9287073", 1 );
    level.disable_super_in_turret.fluctuatevalues = getdvarint( "_encstr_A69719DCD839D72639F53DC383D789AECB13B08DDAF5D0575B859B", 1 );
    level.disable_super_in_turret.vehicle_occupancy_friendlystatuschangedcallback = getdvarint( "_encstr_B6191C6EB127EB3193F5F4C30ED7A6ABEC76F5E6D5DAFA0E63B0CB569337", 3 );
    level.disable_super_in_turret.vehicle_occupancy_getreserving = getdvarint( "_encstr_89801CA21A5B687B7EF9E2D3872F22D314075930EBFF78B3EB41C38720AE", 0 );
    level.disable_super_in_turret.spawndistancemax = getdvarint( "_encstr_97F716E6B14EF59839FAD3E107AFCDCAE4CEB2E4BE0D5D8C", 0 );
    level.disable_super_in_turret.vehicle_occupancy_monitorturretcontrols = getdvarint( "_encstr_B238218BE608AF993D0120530F3E62989D828FD3E3E30ECB26F5F3FAC770DCF5C71721", 20 );
    level.disable_super_in_turret.vehicle_occupancy_mp_changedseats = getdvarint( "_encstr_9B9121076FC348F88221B20A12477095EA8BE781B39A2E989783FB4BF12F6844A32739", 30 );
    level.disable_super_in_turret._id_1470C = getdvarint( "_encstr_B682199F1BEA895EA391125A4B3F0A504572D33BBF53F01E378AA8", 1 );
    level.disable_super_in_turret._id_1470D = getdvarint( "_encstr_BD2921CDC6C97D8927AFE9C3E0EBA7DBADC42D95D7CE969B4BBDB97DBDEC2B938D2CBC", 1 );
    level.disable_super_in_turret._id_14061 = getdvarint( "_encstr_A40F246E6CC9D7269CFAD33C387DAECD95EB16E46BF64EAF1AACB0326E43DB3A7DE6C6B01B2B", 0 );
    level.disable_super_in_turret._id_146BC = getdvarfloat( "_encstr_8A0F22B9B1E4BE134EF5A78707FAE9F65B892DACFA1A950B4637D0DE8ED7E636B0B1C227", 0.65 );
    level.disable_super_in_turret.vehicle_occupancy_getplayerfriendlyto = 0;
    level._id_13364 = 1;
    game["_encstr_B8DA073D799798C7C7"]["_encstr_BDE8175A853E594985B333C0626FAA435C45C72ACF75A3E073"] = "_encstr_89871A8260C525E2607949652E2B22B3AE8F20181857120D7051F43F";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_884319EA5AF85743025BCD179BB458292CA3437881505F3999DB98"] = "_encstr_88E31CA7B7AD98B4ACBE3A5685B5B585D159AFB49BA3DEF59EB76BC4A52B";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_B914174F6B26FA9B59AC32AF9BB7AD59DB37ACD70B63A53B95"] = "_encstr_95CE108215BDC0638A9F353B7F23A030462F";
    level._effect["_encstr_B6810D8D172D60DBFF91D31B5AFB8E"] = loadfx( "_encstr_943A3BA57268A583ECC1DF162335D76F592AC23881A0D6403F83F071624A7BC041F888B5AD51F373280566C3F3B0302557C08FB1139B40A776A8DCD5A1" );
    level._effect["_encstr_BC660D381FC51BAA85809AD0C2F71B"] = loadfx( "_encstr_8BF9361BCEF838DA78D239FDCBAAD761D5B03F51B118EE88471D22CA59A0FDF378B7DA7172B971C087F7EB20B02887EF0B90A879388B7033" );
    level.disable_super_in_turret.empvfx = loadfx( "_encstr_98383866DDD0DDBFA422D91273D0CF066BB3F8F46B70050B40A002AAF9F8533FC35F7A4D8599181779B98A12862577F2E18D14C93FA8B5AB94D2" );
    level.disable_super_in_turret.start_coop_defuse_infiltrate = loadfx( "_encstr_A37D34DB72F39840DB3847359A15E8770FFA938D6A8FC090F575C53BB57D284C83B16AA8C2BFABD00D51D55FC8D3F80377FA20517BCB" );
    thread toggleusbstickinhand();
}

toggleusbstickinhand()
{
    waittillframeend;

    if ( level.disable_super_in_turret.vehicle_occupancy_friendlystatuschangedcallback > 0 && level.disable_super_in_turret.vehicle_occupancy_getreserving )
        level.vehicle_occupancy_forceweaponswitchallowed = undefined;

    thread _id_13283();
    thread _id_1472D();
}

_id_126A4()
{
    var_0 = self;

    if ( !isdefined( var_0.spawndomplateflag ) )
        var_0 _id_12725();

    wait 0.5;
    var_0 _id_125FC();
    wait 2;
    var_0 _id_12723( 0 );
}

modifyplayerdamage( var_0 )
{
    var_1 = 250.0;
    var_2 = 100;
    var_3 = var_0.damage;
    var_4 = isplayer( var_0.attacker ) && var_0.attacker _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3();
    var_5 = isdefined( var_0.attacker ) && var_0.attacker nukefridgewatcher();
    var_6 = isplayer( var_0.victim ) && var_0.victim _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3();
    var_7 = scripts\mp\utility\weapon::getweaponbasenamescript( var_0.objweapon );

    if ( var_4 && var_6 && var_0.meansofdeath == "_encstr_8AED0A5719ED37B8FB512FD7" )
    {
        if ( !level.disable_super_in_turret._id_146F1 )
            var_3 = 0;
        else
            var_3 = level.disable_super_in_turret._id_146F2;
    }
    else if ( isdefined( var_0.attacker ) && istrue( var_0.attacker.isjuggernaut ) && var_6 && var_0.meansofdeath == "_encstr_8AED0A5719ED37B8FB512FD7" )
        var_3 = var_0.victim.maxhealth / 3;
    else if ( var_6 && var_0.meansofdeath == "_encstr_8FA10CBC37F487A99F9C0DE438C7" )
        var_3 = 0;
    else if ( var_6 && isdefined( var_0.inflictor ) && isdefined( var_0.inflictor.streakinfo ) && ( var_0.inflictor.streakinfo.streakname == "_encstr_8CE60CA3DE5BC2AFB98EC94B6D59" || var_0.inflictor.streakinfo.streakname == "_encstr_B7F514E0C9AC364BE65ADEB9BEB05A279BA327D2ADB2" || var_0.inflictor.streakinfo.streakname == "_encstr_8BD90EB62CB9EAC28DFAD1EAE49C56D1" ) )
    {
        var_8 = var_0.victim.maxhealth;
        var_9 = var_0.attacker.maxhealth;
        var_3 = var_0.damage * int( floor( var_8 / var_9 ) );
    }
    else if ( level.disable_super_in_turret._id_146F8 && var_6 && isexplosivedamagemod( var_0.meansofdeath ) && isdefined( var_0.inflictor ) && var_0.inflictor scripts\cp_mp\vehicles\vehicle::isvehicle() )
        var_3 = 0;
    else if ( var_6 && ( var_0.meansofdeath == "_encstr_9E0B13A801F1A16F27C52E196DED47FA817110C1A1" || var_0.meansofdeath == "_encstr_A45C0E4B9FDF3165A3B93C4491BFA4A9" ) )
        var_3 = var_0.damage * getdvarfloat( "_encstr_BC67247A07DAEF1A9280D8D8030F5FC011FD680BF7A0FF97695591B7186B10CB54B843B9F5F2", 3.0 );
    else if ( var_4 && !var_6 && var_0.meansofdeath == "_encstr_8AED0A5719ED37B8FB512FD7" )
    {
        var_10 = var_0.victim.maxhealth;
        var_11 = level.disable_super_in_turret._id_146CF;

        if ( istrue( var_0.victim.isjuggernaut ) )
            var_11 = level.disable_super_in_turret._id_146D0;

        if ( !level.disable_super_in_turret._id_146BF )
            var_10 = var_10 + var_0.victim.br_maxarmorhealth;

        var_3 = int( ceil( var_10 / var_11 ) );
    }
    else if ( var_6 && var_5 && istrue( var_0.victim._id_1423B ) )
        var_3 = 0;
    else if ( var_4 && !var_6 && var_0.meansofdeath == "_encstr_A9ED0B35F488AF94A9A0A00D8A" && var_7 == "_encstr_ABB108EEA8EA22DED72B" )
    {
        var_12 = spawnstruct();
        var_12.origin = var_0.point;
        var_0.victim thread scripts\mp\equipment\concussion_grenade::applyconcussion( var_12, var_0.attacker );
    }
    else if ( var_6 )
    {
        var_13 = 0.7;
        var_14 = scripts\mp\utility\weapon::getweaponrootname( var_0.objweapon );
        var_15 = weaponclass( var_7 );
        var_16 = _encstr_97571CC31EE30FBA499B665A8327B7E7F8F54C512FA93F150D207EF2F097::tutzonetriggerlogic( var_0.idflags );

        if ( !var_16 )
        {
            switch ( var_15 )
            {
                case "_encstr_B6070748328C39712B":
                    if ( var_0.shitloc == "_encstr_B2CC0571402BC0" || var_0.shitloc == "_encstr_A8CC07EAC159C72FD8" )
                    {
                        if ( _encstr_97571CC31EE30FBA499B665A8327B7E7F8F54C512FA93F150D207EF2F097::usefailvehiclemsg( var_14 ) )
                            var_3 = int( ceil( level.disable_super_in_turret._id_146BD * var_13 ) );
                        else
                            var_3 = level.disable_super_in_turret._id_146BD;
                    }

                    break;
                default:
                    if ( var_0.shitloc == "_encstr_B2CC0571402BC0" || var_0.shitloc == "_encstr_A8CC07EAC159C72FD8" )
                    {
                        var_17 = var_2;

                        if ( level.disable_super_in_turret._id_14061 )
                            var_17 = var_1;

                        var_3 = int( ceil( var_3 / var_17 * level.disable_super_in_turret._id_146BD * level.disable_super_in_turret._id_146BC ) );
                    }

                    break;
            }
        }

        var_18 = "_encstr_A87112EB5EFA71BEB3E7555973497EC881F551E6" + var_15;
        var_19 = 0;

        if ( var_15 == "_encstr_A91007F0AB1AC9A31A" )
            var_19 = 0.7;

        var_20 = getdvarfloat( var_18, var_19 );

        if ( var_20 != 0 )
            var_3 = int( ceil( var_3 * var_20 ) );

        var_21 = "_encstr_A87112EB5EFA71BEB3E7555973497EC881F551E6" + var_14;
        var_19 = 0;

        if ( var_14 == "_encstr_9C0B12A7D3E269136081C280C69373D031ECAD83" )
            var_19 = 1.43;

        var_22 = getdvarfloat( var_21, var_19 );

        if ( var_22 != 0 )
            var_3 = int( ceil( var_3 * var_22 ) );
    }

    return var_3;
}

nukefridgewatcher()
{
    return scripts\common\vehicle::isvehicle() || isdefined( self.classname ) && self.classname == "_encstr_AB440F9BD8932D071DAFB3CA435A3663B2";
}

_id_11CA1( var_0 )
{
    var_1 = var_0.damage;
    var_2 = var_0.victim;
    var_3 = isplayer( var_0.attacker ) && var_0.attacker _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3();
    var_4 = var_2.vehiclename;

    if ( var_3 && var_0.meansofdeath == "_encstr_8AED0A5719ED37B8FB512FD7" )
    {
        switch ( var_4 )
        {
            case "_encstr_A219044B93BB":
                var_1 = var_2.maxhealth / level.disable_super_in_turret._id_146CC;
                break;
            case "_encstr_BC120A09810621EE6FAB69F3":
            case "_encstr_B6DE05E0ED1382":
                var_1 = var_2.maxhealth / level.disable_super_in_turret._id_146CD;
                break;
            case "_encstr_98C20F6C169CCEDEEB1D27EA1B5BFA6BCE":
            case "_encstr_93120C26CEB35F60D753E8D8E70B":
                var_1 = var_2.maxhealth / level.disable_super_in_turret._id_146D1;
                break;
            case "_encstr_A4E90F635A473A63B2BEC4D2E48CBEAD9D":
            case "_encstr_BC8F0CED4311BB6CA9F19BBFB0A1":
                var_1 = var_2.maxhealth / level.disable_super_in_turret._id_146CE;
                break;
            default:
                break;
        }

        var_1 = int( ceil( var_1 ) );
    }

    return var_1;
}

_id_11B80( var_0, var_1 )
{
    var_2 = var_0 _id_126D2( var_1 );

    if ( scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) && !var_2 )
        _encstr_97571CC31EE30FBA499B665A8327B7E7F8F54C512FA93F150D207EF2F097::_id_11B15( var_0 );

    return !var_2;
}

_id_1365D( var_0 )
{
    if ( istrue( var_0.br_infilstarted ) && scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) && var_0 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
    {
        var_0 _id_12645();
        return 1;
    }

    return 0;
}

_id_11B16()
{
    return 0;
}

_id_126D2( var_0 )
{
    if ( !istrue( var_0 ) )
    {
        if ( _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
        {
            thread _id_12538();
            return 0;
        }
    }

    if ( !istrue( self.br_infilstarted ) || !scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) || level.gameended || !level.disable_super_in_turret._id_146E7 )
        return 0;

    thread _id_12723( 0 );
    return 1;
}

_id_12538()
{
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self setscriptablepartstate( "_encstr_98CB0755CFC5882307", "_encstr_9819045FD029" );
    self setscriptablepartstate( "_encstr_8A6D0C6CF6DAE0586E37A51BED37", "_encstr_A4250C79AF9EF045C2DBC3DF9FCA" );
    self setscriptablepartstate( "_encstr_B7640B6ED65E8CD2CECA95330F", "_encstr_AA1608C07786F13312D3", 0 );

    if ( level.disable_super_in_turret._id_1470C )
    {
        _id_125DA();

        if ( !level.disable_super_in_turret._id_1470D )
            self setscriptablepartstate( "_encstr_AA9108994991F173B8B9", "_encstr_9BA4080D39CFFB5AB7C1" );

        self visionsetnakedforplayer( "_encstr_A40101", 0 );
    }

    waittillframeend;
    _id_12681( 0, 1 );
    _id_1262B( 0 );
}

_id_125DA()
{
    foreach ( var_1 in level.players )
    {
        if ( !var_1 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
            var_1 hudoutlinedisableforclient( self );
    }
}

_id_12681( var_0, var_1 )
{
    self.iszombie = var_0;
    _id_12682( var_0 );

    if ( isdefined( level.disable_super_in_turret._id_11B5B ) )
        _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::_id_126E6( var_0 );

    if ( var_0 )
    {
        self notify( "_encstr_81290B4A27A329DFF5412F9B13" );

        if ( level.disable_super_in_turret.spawndistancemax )
            _id_12725();

        self._id_11F39 = 0;
        self.bcdisabled = 1;
        self.plunderlimit = 1;
        _id_1267D( 0 );
        scripts\cp\vehicles\little_bird_mg_cp::calloutmarkerping_removecallout( 7 );
        scripts\cp\vehicles\little_bird_mg_cp::calloutmarkerping_removecallout( 9 );
        scripts\cp\vehicles\little_bird_mg_cp::calloutmarkerping_removecallout( 10 );
        scripts\cp\vehicles\little_bird_mg_cp::calloutmarkerping_removecallout( 11 );
        _id_14033( "_encstr_B9F20B101D171B094FBE8710BB", self._id_11F39 );
    }
    else
    {
        self notify( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
        self._id_11F39 = undefined;
        self.bcdisabled = undefined;
        self.plunderlimit = undefined;
        scripts\cp\vehicles\little_bird_mg_cp::calloutmarkerping_removecallout( 7 );

        if ( isdefined( level.disable_super_in_turret._id_11B5B ) )
            _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::_id_125CE();
    }

    level notify( "_encstr_B64F1ABBA1C7E315F80B89CAE12859BA28C3BB6F5F7E3AC9E0913F57" );
    self notify( "_encstr_AF4F13DC8EDEE0EB138547D1C62BC6862CD11DB227" );

    if ( istrue( var_1 ) )
    {
        self lerpfovbypreset( "_encstr_AA1608C07786F13312D3" );

        if ( level.disable_super_in_turret._id_1470D )
            thread scripts\mp\supers\super_deadsilence::superdeadsilence_endhudsequence();
    }
}

init_warning_levels()
{
    var_0 = [];
    var_0["_encstr_872D11D1FF892130152B9EE3788CA51CCBFBCF"] = "_encstr_A6B3120F05CFBC15435ADB2FF1F723E338B88B13";
    var_0["_encstr_87C30FC410893345733089A330AB3E9362"] = "_encstr_9BED0AA307609154C76BDB23";
    var_0["_encstr_B44319C6DB5832DEAE3A289C965B2CC95E141DA32C36A1D65673A3"] = "_encstr_AABA05236DC831";
    var_0["_encstr_A9651AE2C897BBF598D1103A83303EBBC3A5DBEB917E43AD20FD4C62"] = "_encstr_AABA05236DC831";
    var_0["_encstr_B66C1363F658327BD53A419396B558E49786B0B5DB"] = "_encstr_AABA05236DC831";
    var_0["_encstr_8702161410EA292F7BB321E36172F3866033F7BCB96F09A9"] = "_encstr_AABA05236DC831";
    var_0["_encstr_A14E11D520C0AC320551FF3F67206AE4782B08"] = "_encstr_AABA05236DC831";
    var_0["_encstr_9D6F1B6C48D16B2D1B48D18AC817252389AEF1395DDBC7F6C968BA3218"] = "_encstr_AABA05236DC831";
    var_0["_encstr_BDDB1C6590701C82D5812FCF97F0DA54285B58A66B70A19AA35BFFEBD106"] = "_encstr_AABA05236DC831";
    var_0["_encstr_A2EA151BD081D44253851297663F0A9C2980C73F48F807"] = "_encstr_AABA05236DC831";
    var_0["_encstr_82B618ABEA2661705BBB2A415B6D7332AB2AD71F9D3880AE324D"] = "_encstr_AABA05236DC831";
    var_0["_encstr_879C11A537D2DA37230B19FA98E96581D0A55B"] = "_encstr_AABA05236DC831";
    var_0["_encstr_B3A418C6F61691DB5747A2175796C1D6B27347824E96B6854E5E"] = "_encstr_AABA05236DC831";
    var_0["_encstr_AA781A89AF4749179393F168BBACE1A08F460DEE3DE7904DBFAA4020"] = "_encstr_AABA05236DC831";
    var_0["_encstr_A31B12E09AEF5518032CF7A1326F20AA4393FB49"] = "_encstr_973508BF93EFFBC363B3";
    var_0["_encstr_BAE713C8CFE03C60079B6BE3E83B5FEC7AAAF917B3"] = "_encstr_AABA05236DC831";
    var_0["_encstr_A1E71363923EA180A70CDA33FC2BCB59229AD0B0DF"] = "_encstr_AABA05236DC831";
    var_0["_encstr_B9E71363DEC291F6ABD196961B63DCE8935616B6CC"] = "_encstr_AABA05236DC831";
    var_0["_encstr_B6920DDA60DB0FAFA33D538DD74913"] = "_encstr_B4841137EA83594EF5899CBECA1EA34E0B8DA3";
    var_0["_encstr_ABCB0DBA7BBB6FCFC35D303D7628F7"] = [ "_encstr_B99C0FF382C5B813BA035133B732658894" ];
    var_0["_encstr_A4450FEB472A87A2834C172243E0E538F8"] = "_encstr_A83C0BF7F4ABABC79045FE5807";
    var_0["_encstr_B2E611340FC91DE80B835BA377BA4DC32BC0A8"] = "_encstr_AABA05236DC831";
    return var_0;
}

spawnangle( var_0 )
{
    var_1 = getarraykeys( level.teamdata );

    foreach ( var_3 in var_1 )
    {
        var_4 = level.teamdata[var_3]["_encstr_8875080E3685E52B93B9"];

        foreach ( var_6 in var_4 )
        {
            if ( var_6 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
            {
                if ( level.disable_super_in_turret.spawndistancemax )
                    var_6 _id_12700();

                var_6 _id_12631();
                continue;
            }

            var_6 _id_12631();
        }
    }
}

_id_12725()
{
    var_0 = -60;
    var_1 = 120;
    var_2 = 180;
    self.spawnboardroom_juggdrop = _id_12530( var_0, var_1, "_encstr_9353062E718710C9", "_encstr_8B8D070BD2EBAF4477", "_encstr_B1C4077FDD2D101D63", "_encstr_8B8D070BD2EBAF4477", &"_encstr_BA2F14181989F899A0D09095E3B6B82754E7B54DD795", 0 );
    self.spawnboardroom_loadoutdrop = _id_12530( var_0, var_1, "_encstr_B1AD05C65666E8", "_encstr_8B8D070BD2EBAF4477", "_encstr_B1C4077FDD2D101D63", "_encstr_8B8D070BD2EBAF4477", &"_encstr_A49116A9A0D7B416A05EE4AA35F551E97DA1D3396AAA35A8", level.disable_super_in_turret._id_146D2 );
    self.spawndomplateflag = _id_12530( 0, var_2, "_encstr_B1C4077FDD2D101D63", "_encstr_8B8D070BD2EBAF4477", "_encstr_B1C4077FDD2D101D63", "_encstr_8B8D070BD2EBAF4477", &"_encstr_A2F20E037B91F9C69B4AA0B0279A5751" );
}

_id_12530( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7 )
{
    var_8 = scripts\mp\hud_util::createfontstring( "_encstr_AA1608C07786F13312D3", 1.5 );
    var_8.x = var_0;
    var_8.y = var_1;
    var_8.alignx = var_2;
    var_8.aligny = var_3;
    var_8.horzalign = var_4;
    var_8.vertalign = var_5;
    var_8.alpha = 0;
    var_8.glowalpha = 0;
    var_8.hidewheninmenu = 1;
    var_8.archived = 0;

    if ( isdefined( var_6 ) )
        var_8.label = var_6;

    if ( isdefined( var_7 ) )
        var_8 setvalue( var_7 );

    return var_8;
}

_id_12682( var_0 )
{
    if ( istrue( var_0 ) )
        self.game_extrainfo = self.game_extrainfo | 4096;
    else
        self.game_extrainfo = self.game_extrainfo & ~4096;
}

_id_12723( var_0 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );

    if ( level.gameended )
        return;

    if ( !isdefined( level.teamdata[self.team]["_encstr_AD720F18CEEB38B2521F756B5789638895"] ) && !isdefined( level._id_12D05 ) )
        _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::dmztut_luicallback( "_encstr_B914174F6B26FA9B59AC32AF9BB7AD59DB37ACD70B63A53B95", self.team );

    _id_131CD( self.team );
    _id_1267D( 1 );
    _id_12727( 1 );
    waittillframeend;
    _id_12681( 1 );
    self._id_12CA8 = 1;

    if ( isdefined( level._id_12D05 ) )
        _id_12645();
    else if ( var_0 )
        _id_126EE();
    else
        _id_12645();

    if ( _encstr_AD64266E6CE44B1CD19B97B53897D9B0B62B1DBC389537F2139CBE7658D6AC8E2F3895DC17B3DC8D::tutorial_showtext( "_encstr_984F1D031571D8A53B3FE3D953B2F948012FEF9BFECFB8F90287E3D1F79AB0" ) )
        [var_2, var_3] = _encstr_AD64266E6CE44B1CD19B97B53897D9B0B62B1DBC389537F2139CBE7658D6AC8E2F3895DC17B3DC8D::_id_12E05( "_encstr_984F1D031571D8A53B3FE3D953B2F948012FEF9BFECFB8F90287E3D1F79AB0" );
    else
        [var_2, var_3] = _id_12582();

    [var_2, var_6] = _id_12722( var_2, var_3 );
    _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::gulagfadetoblack();
    wait 1;
    scripts\mp\class::loadout_emptycacheofloadout( "_encstr_87AC099DB05B59ADF619AC" );
    self.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"] = level.disable_super_in_turret._id_146C9;
    self.class = "_encstr_87AC099DB05B59ADF619AC";
    self.forcespawnangles = var_3;
    self.forcespawnorigin = var_6;
    scripts\mp\playerlogic::spawnplayer( undefined, 0 );
    thread scripts\mp\music_and_dialog::_id_1469B();
    scripts\cp_mp\execution::_clearexecution();
    _encstr_823124376CE42DC11DCD5EB6E0CB3BB0ADAC3A2FE056CDBC314EAF83A536DAAB079BE2D9B9B1::initplayer( 1 );
    _encstr_B2E4252B3FAB9B1009F38F29237E449729C578A17B25C3F279A3502A7A02C66C77330DD01FE027::_id_1252A();
    self notify( "_encstr_BC8310B750A97B7BD185A2D4F58363369038" );
    var_7 = getcompleteweaponname( "_encstr_9B660D018F3841EE3A23DBEE3639F0" );
    scripts\cp_mp\utility\inventory_utility::_takeweapon( var_7 );
    var_8 = getcompleteweaponname( "_encstr_9DFA112DDD70F5662D373A9BD7B61CEBE9ADC4" );
    scripts\cp_mp\utility\inventory_utility::_giveweapon( var_8, undefined, undefined, 1 );
    self detachall();
    self setmodel( "_encstr_BD97155A9309F3DE3099213F9D082503230941D23ED633" );
    self setviewmodel( "_encstr_AFE111F8FF1769A5EAEA801AC5C2CDD0959FD8" );
    scripts\mp\utility\player::_setsuit( "_encstr_80A00EB12BE086703707FB10E399E853" );
    _id_126BD( var_2, var_3, var_6 );
    self skydive_interrupt();
    self.play_disguise_vo = 5;
    self skydive_setbasejumpingstatus( 0 );
    self skydive_setdeploymentstatus( 0 );
    self skydive_beginfreefall();
    thread scripts\cp_mp\utility\inventory_utility::_switchtoweaponimmediate( var_8 );
    _id_1262B( 1 );
    thread _id_12710( var_8, scripts\cp_mp\utility\game_utility::turretdisabled() );
    thread _encstr_97571CC31EE30FBA499B665A8327B7E7F8F54C512FA93F150D207EF2F097::defend_wave_2();
    thread _id_1272A();

    if ( level.disable_super_in_turret.brking_movenextcirclecenter )
        thread _id_12724();

    if ( istrue( level.disable_super_in_turret._id_146B2 ) )
        thread _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::_id_12730();

    thread _id_1270D();
    scripts\mp\utility\perk::giveperk( "_encstr_A2AD12B907591BD2C2363ABCFA1DC95836B62BC9" );
    scripts\mp\utility\perk::giveperk( "_encstr_B206166E0EACC6A52CC6A397EBB9C1E42D9B1DB556C62BB2" );
    scripts\mp\utility\perk::giveperk( "_encstr_9C1F1473C8438810CFF91D9951EF2B3AA3E6947621EB" );
    scripts\common\utility::allow_crate_use( 0 );
    scripts\common\utility::allow_vehicle_use( 0 );
    self lerpfovbypreset( "_encstr_AA880E02A0D02AB113F2AFD9EF4565E0" );

    if ( level.disable_super_in_turret._id_1470D )
        self setclientomnvar( "_encstr_9D77177DDBF11787A79113BAB88DF38E48CFEFE66B20DD5F53", 0 );

    thread _id_126FF();
    self setscriptablepartstate( "_encstr_8A6D0C6CF6DAE0586E37A51BED37", "_encstr_98CB0755CFC5882307" );

    if ( getdvarint( "_encstr_9C112B6E8D93EB89937D4F3CC1AF667BE48DB2F573591D992D591B23F5A1B4CEA1BE1BBD46FAA7F6AD89A5AC6E", 0 ) )
        self markkeyframedmover( 1 );

    if ( isdefined( level._id_12D05 ) )
        scripts\mp\hud_message::showsplash( "_encstr_A66415E3F886022295CDDE953847EBD7CB297713303844" );
    else
        scripts\mp\hud_message::showsplash( "_encstr_B67E17BD0AA148DFDF32D37A4BD798F81E60BF378896C81407" );

    if ( !scripts\mp\utility\perk::_hasperk( "_encstr_9EAA160357C1E73CA33813DBB9D974EF9BB0948C65E96384" ) )
        scripts\mp\utility\perk::giveperk( "_encstr_9EAA160357C1E73CA33813DBB9D974EF9BB0948C65E96384" );

    self.maxhealth = level.disable_super_in_turret._id_146BD;
    self.health = self.maxhealth;
    _encstr_BD96220B5106E75AE8B7770D890AA70F2109F353DB5537C530DD0F0965F06D1BF8E11B7A::scriptablescurid( 0 );
    self._id_12CA8 = undefined;
    wait 3;

    if ( !isdefined( level._id_12D05 ) && scripts\mp\utility\game::round_vehicle_logic() != "_encstr_821904AA2D18" )
    {
        foreach ( var_10 in level.teamdata[self.team]["_encstr_8875080E3685E52B93B9"] )
        {
            if ( self == var_10 )
            {
                _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::dmztut_endgamewithreward( "_encstr_BDE8175A853E594985B333C0626FAA435C45C72ACF75A3E073", var_10 );
                continue;
            }

            _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::dmztut_endgamewithreward( "_encstr_884319EA5AF85743025BCD179BB458292CA3437881505F3999DB98", var_10 );
        }
    }
}

_id_1264B( var_0 )
{
    if ( _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
    {
        if ( istrue( self._id_146C0 ) )
            return int( level.disable_super_in_turret._id_146E5 * var_0 );
        else
            return int( level.disable_super_in_turret._id_146E6 * var_0 );
    }

    return undefined;
}

_id_1262B( var_0 )
{
    _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125CF( var_0 );

    if ( var_0 )
    {
        if ( level.disable_super_in_turret.spawndistancemax )
        {
            self.spawnboardroom_juggdrop.alpha = 1;
            self.spawnboardroom_loadoutdrop.alpha = 1;
            self.spawndomplateflag.alpha = 1;
        }

        self disableweaponpickup();
    }
    else
    {
        _id_12700();
        self enableweaponpickup();
    }
}

_id_131CD( var_0 )
{
    level.teamdata[var_0]["_encstr_AD720F18CEEB38B2521F756B5789638895"] = gettime();
}

_id_1267D( var_0 )
{
    self.tut_popup_listener = var_0;
}

_id_12727( var_0 )
{
    var_1 = self.team;
    scripts\mp\utility\teams::_id_140C9( "_encstr_97A205FB4F0730", var_1, self );
    _id_126D8();

    if ( istrue( var_0 ) )
        [[ level.updategameevents ]]();
}

_id_12700()
{
    if ( isdefined( self.spawnboardroom_juggdrop ) )
        thread kioskfiresaledoneforplayer( self.spawnboardroom_juggdrop, 1.5 );

    if ( isdefined( self.spawnboardroom_loadoutdrop ) )
        thread kioskfiresaledoneforplayer( self.spawnboardroom_loadoutdrop, 1.5 );

    if ( isdefined( self.spawndomplateflag ) )
        self.spawndomplateflag destroy();

    self.spawnboardroom_juggdrop = undefined;
    self.spawnboardroom_loadoutdrop = undefined;
    self.spawndomplateflag = undefined;
}

kioskfiresaledoneforplayer( var_0, var_1 )
{
    wait( var_1 );

    if ( isdefined( var_0 ) )
        var_0 destroy();
}

_id_125FA()
{
    return isdefined( self._id_1472F );
}

_id_1264A( var_0 )
{
    if ( _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
    {
        if ( istrue( self._id_146C0 ) )
            return 1 / level.disable_super_in_turret._id_146E3 * var_0;
        else
            return 1 / level.disable_super_in_turret._id_146E4 * var_0;
    }

    return undefined;
}

onuse( var_0 )
{
    thread _id_120A7( var_0 );
}

_id_120A7( var_0 )
{
    if ( !isdefined( var_0 ) )
    {
        thread _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::removetags( self );
        return;
    }

    if ( !playercanusetags( var_0 ) )
        return;

    thread _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::removetags( self );
    var_0._id_11F39++;

    if ( level.disable_super_in_turret.spawndistancemax )
        var_0 _id_125D4();

    var_0 _id_14033( "_encstr_B9F20B101D171B094FBE8710BB", var_0._id_11F39 );

    if ( isdefined( level.disable_super_in_turret._id_11B5B ) && var_0._id_11F39 >= level.disable_super_in_turret._id_146D2 )
        var_0 thread _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::_id_126FA();
}

playercanusetags( var_0 )
{
    return var_0 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3();
}

_id_125D4()
{
    var_0 = ( 0, 1, 0 );
    self.spawnboardroom_juggdrop setvalue( self._id_11F39 );
    self.spawnboardroom_juggdrop thread spawn_vindia_assault3( var_0 );
    self.spawnboardroom_loadoutdrop thread spawn_vindia_assault3( var_0 );
}

spawn_vindia_assault3( var_0 )
{
    self endon( "_encstr_A3750609A5E61883" );

    if ( istrue( self._id_1293B ) )
        return;

    var_1 = 0.5;
    var_2 = 4;
    self._id_1293B = 1;
    var_3 = self.fontscale;
    var_4 = self.color;

    if ( isdefined( var_0 ) )
        self.color = var_0;

    self changefontscaleovertime( var_1 );
    self.fontscale = var_2;
    wait( var_1 );
    self changefontscaleovertime( var_1 );
    self.fontscale = var_3;
    wait( var_1 );
    self.color = var_4;
    self._id_1293B = undefined;
}

_id_125FC()
{
    var_0 = spawnstruct();
    var_0.current = self getcurrentprimaryweapon();
    var_0._id_12889 = [];
    var_0.brtdm_config = [];
    var_0.brtruck_cleanupents = [];
    var_0.brtruck_ontimelimit = [];
    var_0.offhands = [];
    var_0.nvidiaansel_overridecollisionradius = [];
    var_1 = [];
    var_2 = self getweaponslistprimaries();

    foreach ( var_4 in var_2 )
    {
        if ( !scripts\mp\utility\weapon::update_health_bar_to_player( var_4 ) && !issubstr( var_4.basename, "_encstr_9B660D018F3841EE3A23DBEE3639F0" ) && !scripts\mp\utility\weapon::unset_relic_mythic( var_4.basename ) )
            var_1[var_1.size] = var_4;
    }

    foreach ( var_7 in var_1 )
    {
        var_8 = createheadicon( var_7 );
        var_0.brtdm_config[var_8] = weaponclipsize( var_7 );
        var_0.brtruck_ontimelimit[var_8] = self getweaponammostock( var_7 );

        if ( scripts\mp\utility\weapon::turnexfiltoside( var_7 ) )
            var_0.brtruck_cleanupents[var_8] = self getweaponammoclip( var_7, "_encstr_B1AD05C65666E8" );

        if ( getsubstr( var_8, 0, 4 ) == "_encstr_AD830589BDDC51" )
            continue;

        var_0._id_12889[var_0._id_12889.size] = var_7;
    }

    var_10 = self getweaponslistoffhands();

    foreach ( var_12 in var_10 )
    {
        if ( var_12.basename == "_encstr_B11B0B4C2CDC46167656AF31C9" )
            continue;

        var_13 = self getweaponammoclip( var_12 );

        if ( var_13 <= 0 )
            continue;

        var_0.offhands[var_0.offhands.size] = var_12;
        var_14 = createheadicon( var_12 );
        var_0.brtdm_config[var_14] = var_13;
    }

    foreach ( var_18, var_17 in self.equipment )
        var_0.nvidiaansel_overridecollisionradius[var_17] = var_18;

    var_0.super = undefined;

    if ( isdefined( self.super ) && !self.super.usepercent )
        var_0.super = self.equipment["_encstr_BEB4068F1B5BA3AB"];

    self._id_1472F = var_0;
}

_id_126EE()
{
    if ( _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
        self waittill( "_encstr_8CB10CFB6980532BBA70728A980D" );
}

_id_12645()
{
    self notify( "_encstr_8CB10CFB6980532BBA70728A980D" );
    self _meth_87A9( "_encstr_98CB0755CFC5882307" );
    self setclothtype( "_encstr_9D95063389284BFB" );
    scripts\mp\deathicons::spawn_carriables_from_prefabs_all( self );
}

run_track_enemy_patrollers( var_0, var_1, var_2 )
{
    var_3 = var_0 + var_1 * var_2;

    if ( _encstr_821221B201F8016365BFEEFFA1A05A4178A9EBB8DBE8C36EB69527CF4B96F7F680F3A6::ispointinbounds( var_3, 1 ) )
    {
        var_4 = vectortoangles( var_1 * -1 );
        return [ var_3, var_4 ];
    }
    else
        return [ undefined, undefined ];
}

_id_1270E()
{
    var_0 = undefined;
    var_1 = undefined;
    var_2 = getdvarfloat( "_encstr_A6081D2EFB5376653A596078C3193D493F70BFA45E13F9AB256098F0EBAFF9", 10000 );

    if ( var_2 >= 0 )
    {
        var_3 = _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_12568( 0 );

        if ( isdefined( var_3 ) )
        {
            var_0 = rocket_fuel_stability( var_3.origin, var_2 );

            if ( istrue( level._encstr_98651BD56E95CD2CD9DA2B9BD0CCF69CA7F6B5895AAC39B29B3816DDB9 ) && isscriptabledefined() )
                var_0 = getclosestpointonnavmesh( var_0 );

            var_0 = _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::modifyplayer_damage( var_0 );
            var_1 = _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::registercarryobjectpickupcheck( var_0, var_3.origin );
        }
    }

    return [ var_0, var_1 ];
}

rocket_fuel_stability( var_0, var_1 )
{
    var_2 = 3.14159;
    var_3 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getsafecircleorigin();
    var_4 = vectornormalize( var_0 - var_3 );
    var_5 = vectortoangles( var_4 );
    var_6 = randomfloatrange( getdvarfloat( "_encstr_AB151CB3069219D6CB8F1DCBC713AF9056911B49EDEC611F22474FD387DA", 10.0 ), getdvarfloat( "_encstr_9D151C6E1B4E7D98277D93959B382CDDB9AF4EC2B946AFB0CD9DF5ADB0E1", 60.0 ) );
    var_7 = var_4;
    var_8 = var_0 + var_7 * var_1;

    if ( _encstr_821221B201F8016365BFEEFFA1A05A4178A9EBB8DBE8C36EB69527CF4B96F7F680F3A6::ispointinbounds( var_8, 0 ) )
        return var_8;

    var_7 = var_7 * -1;
    var_8 = var_0 + var_7 * var_1;

    if ( _encstr_821221B201F8016365BFEEFFA1A05A4178A9EBB8DBE8C36EB69527CF4B96F7F680F3A6::ispointinbounds( var_8, 0 ) )
        return var_8;

    var_7 = vectornormalize( var_3 - var_0 );
    var_8 = var_0 + var_7 * var_1;

    if ( _encstr_821221B201F8016365BFEEFFA1A05A4178A9EBB8DBE8C36EB69527CF4B96F7F680F3A6::ispointinbounds( var_8, 0 ) )
        return var_8;

    var_9 = var_1;
    var_10 = distance2d( var_0, var_3 );
    var_11 = var_9 / var_10;

    if ( var_11 > var_2 )
        var_11 = var_2;

    var_12 = var_11 * 180 / var_2;
    var_8 = rotatepointaroundvector( ( 0, 0, 1 ), var_0 - var_3, var_12 ) + var_3;

    if ( _encstr_821221B201F8016365BFEEFFA1A05A4178A9EBB8DBE8C36EB69527CF4B96F7F680F3A6::ispointinbounds( var_8, 0 ) )
        return var_8;

    var_8 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getrandompointincircle( var_0, var_1 );

    if ( _encstr_821221B201F8016365BFEEFFA1A05A4178A9EBB8DBE8C36EB69527CF4B96F7F680F3A6::ispointinbounds( var_8, 0 ) )
        return var_8;

    return undefined;
}

_id_12582()
{
    var_0 = 50;
    var_1 = 10000;
    [var_3, var_4] = _id_1270E();

    if ( isdefined( var_3 ) )
        return [ var_3, var_4 ];

    if ( !isdefined( level.br_circle ) || !isdefined( level.br_circle.dangercircleent ) || istrue( level.disable_super_in_turret._id_146FB ) )
        return [ self.origin, self getplayerangles() ];

    var_5 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getdangercircleradius();
    var_6 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getdangercircleorigin();
    var_7 = var_5 + var_0;
    var_8 = ( self.origin[0], self.origin[1], 0 );
    var_9 = vectornormalize( var_8 - var_6 );
    [var_11, var_4] = run_track_enemy_patrollers( var_6, var_9, var_7 );

    if ( !isdefined( var_11 ) )
    {
        var_9 = var_9 * -1;
        [var_11, var_4] = run_track_enemy_patrollers( var_6, var_9, var_7 );
    }

    if ( !isdefined( var_11 ) )
    {
        var_9 = ( 1, 0, 0 );
        [var_11, var_4] = run_track_enemy_patrollers( var_6, var_9, var_7 );
    }

    if ( !isdefined( var_11 ) )
    {
        var_9 = ( -1, 0, 0 );
        [var_11, var_4] = run_track_enemy_patrollers( var_6, var_9, var_7 );
    }

    if ( !isdefined( var_11 ) )
    {
        var_9 = ( 0, 1, 0 );
        [var_11, var_4] = run_track_enemy_patrollers( var_6, var_9, var_7 );
    }

    if ( !isdefined( var_11 ) )
    {
        var_9 = ( 0, -1, 0 );
        [var_11, var_4] = run_track_enemy_patrollers( var_6, var_9, var_7 );
    }

    if ( !isdefined( var_11 ) )
    {
        var_11 = self.origin;
        var_4 = self.angles;
    }

    var_3 = _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::modifyplayer_damage( var_11, var_1 );
    return [ var_3, var_4 ];
}

_id_12722( var_0, var_1 )
{
    var_2 = var_0;

    if ( level.disable_super_in_turret._id_146FC )
    {
        var_3 = getdvarint( "_encstr_B68A1FD6B64BD72912278088836763EB231A475C4D616F30EAD77001BF791909FB", 10000 );
        var_4 = ( 0, 0, var_3 );
        var_0 = _encstr_97571CC31EE30FBA499B665A8327B7E7F8F54C512FA93F150D207EF2F097::getoffsetspawnorigin( var_0, var_4 );
        var_5 = spawnstruct();
        var_5.origin = var_0;
        var_5.angles = var_1;
        var_5.height = var_3;
        var_2 = _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_1263E( var_5 );
    }
    else
    {
        self setallstreamloaddist( 0.0 );
        _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_126B9( var_2 );
    }

    return [ var_0, var_2 ];
}

_id_126BD( var_0, var_1, var_2 )
{
    _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_126C3( var_2, var_1 );
    var_3 = spawn( "_encstr_93DC0DCD1B272D3847AF5BED23B2C6", var_2 );
    var_3 setmodel( "_encstr_8CB40B4BB398B1C0A81FDF6BEA" );
    var_3.angles = var_1;
    var_3 hide();
    var_3 showtoplayer( self );
    self playerlinktoabsolute( var_3, "_encstr_8CB40B4BB398B1C0A81FDF6BEA" );
    self playerhide();
    thread _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_12524( var_3 );
    waitframe();
    _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_126ED();
    _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_1252B();
    var_3.origin = var_0;
    waitframe();
    self unlink();
    self clearsoundsubmix( "_encstr_BC6A0FBF0BC943BA93805FCFF2BBD18511" );
    self clearsoundsubmix( "_encstr_82CE2DD59F5AADD95CF5DE715D3140D281074979CF92EBF0650AA3AE050D081BFA97CBF5DB9936A8AAA42BC32FC462", 2 );
    self clearclienttriggeraudiozone( 1 );
    self playershow();
    var_4 = 0;

    if ( isdefined( level._id_121CC ) )
        var_4 = level._id_121CC;

    thread scripts\cp_mp\parachute::startfreefall( var_4, 0, undefined, undefined, 1 );
    self setclientomnvar( "_encstr_B79616EBD887E22AA7BD3BD930B832D8B03FB898A9387F82", 0 );
    self setclientomnvar( "_encstr_8F3F1455998F9B292573F1881B7FF7B3CF2CD553FD0B", -1 );
    _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_12C7A();
    wait 0.5;
    _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::gulagfadefromblack();
    waitframe();
    var_3 delete();
    self notify( "_encstr_888F1252495017B230A7F7D77718BD3706C08ADB" );
}

_id_126FF()
{
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );

    if ( level.disable_super_in_turret._id_1470C )
    {
        self hudoutlinedisable();

        if ( !level.disable_super_in_turret._id_1470D )
            self setscriptablepartstate( "_encstr_AA9108994991F173B8B9", "_encstr_87C10DD210082BC453211AB330AFFD" );

        self visionsetnakedforplayer( "_encstr_89C20FC59361FC62B8EFFFA785C8FB3D50", 0 );
        _id_12713();
    }

    waitframe();

    if ( getdvarint( "_encstr_A6541AB96CE47D98C9EBA7C31CBE1BB77BE0D7F47BAD98D2597DCC1E", 1 ) )
        self setscriptablepartstate( "_encstr_98CB0755CFC5882307", "_encstr_956E08DE9B7DB1BDDE38" );
    else
        self setscriptablepartstate( "_encstr_98CB0755CFC5882307", "_encstr_9707035F3B" );
}

_id_12713()
{
    foreach ( var_1 in level.players )
    {
        if ( !var_1 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
            scripts\mp\utility\outline::outlineenableforplayer( var_1, self, "_encstr_B1EA1B6F67F381F0AE9F2659879850CBF9F3F7E3C3CADD30F172E8306D", "_encstr_B91904EC4718" );
    }
}

_id_1270D()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self._id_146C0 = undefined;

    for (;;)
    {
        if ( _id_12714() )
        {
            if ( !isdefined( self._id_146C0 ) || !self._id_146C0 )
            {
                self._id_146C0 = 1;
                _id_12705();
            }
        }
        else if ( !isdefined( self._id_146C0 ) || self._id_146C0 )
        {
            self._id_146C0 = 0;
            _id_12706();
        }

        waitframe();
    }
}

_id_12705()
{
    self notify( "_encstr_888C11C388D1E33458C7E5E679B03ACF0CE1EB" );
    self unsetperk( "_encstr_947514E6E0561B9658361D2FAF4E0B46583931364B0E", 1 );
}

_id_12706()
{
    self notify( "_encstr_8B8C1025B2CF2E41772E0D38AB6BC70FFB13" );

    if ( level.disable_super_in_turret._id_146D5 >= 0 )
    {
        if ( level.disable_super_in_turret._id_146D5 == 0 )
            self setperk( "_encstr_947514E6E0561B9658361D2FAF4E0B46583931364B0E", 1 );
        else
            thread _id_1271F();
    }
}

_id_1271F()
{
    if ( level.disable_super_in_turret._id_146D5 <= 0 )
        return;

    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_888C11C388D1E33458C7E5E679B03ACF0CE1EB" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );

    for (;;)
    {
        self setperk( "_encstr_947514E6E0561B9658361D2FAF4E0B46583931364B0E", 1 );
        wait( level.disable_super_in_turret._id_146D6 );
        self unsetperk( "_encstr_947514E6E0561B9658361D2FAF4E0B46583931364B0E", 1 );
        wait( level.disable_super_in_turret._id_146D5 );
    }
}

_id_12714()
{
    if ( !isdefined( level.br_circle ) || !isdefined( level.br_circle.dangercircleent ) )
        return 0;

    var_0 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getdangercircleorigin();
    var_1 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getdangercircleradius();
    return distance2dsquared( var_0, self.origin ) > var_1 * var_1;
}

_id_12724()
{
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self._id_133E9 = 1;
    self.radarmode = "_encstr_9BC90D60AF62A0CBC229CE5FFFCA35";
    self.hasradar = 1;
    self waittill( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self._id_133E9 = undefined;
    self.hasradar = 0;
}

_id_1272A()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );

    for (;;)
    {
        if ( self issupersprinting() )
            self refreshsprinttime();

        waitframe();
    }
}

_id_12710( var_0, var_1 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    wait 1;

    while ( !self isonground() )
    {
        _id_125B8( var_0 );
        waitframe();
    }

    self setclientomnvar( "_encstr_937E168D2B0166CBA821D25B0899AF5B78852FF379A8AB5F", 0 );
    self skydive_interrupt();
    playfxontag( level._effect["_encstr_BC660D381FC51BAA85809AD0C2F71B"], self, "_encstr_8BE10B4DF5DA2C5A9B39B7EDE8" );
    self playsoundtoplayer( "_encstr_88F814EBDB6B27D0238910AE1F32A28D5EAB774B7D9B", self, self );
    self playsound( "_encstr_B8F914F8D9A8565E132804B27F6E83DD67FB6F15AB47", self, self );

    if ( isbot( self ) )
        return;

    self freezecontrols( 1 );
    var_2 = gettime() + 2000;

    while ( self getcurrentprimaryweapon().classname == "_encstr_AABA05236DC831" && gettime() < var_2 )
    {
        _id_125B8( var_0 );
        waitframe();
    }

    var_3 = propwaitminigameinit( self, 0 );

    if ( !isdefined( var_3 ) )
        var_3 = ( 0, 0, 1 );

    var_4 = anglestoforward( self.angles );
    var_5 = vectortoangles( var_3 );
    var_6 = angleclamp180( var_5[0] + 90 );
    var_5 = ( 0, var_5[1], 0 );
    var_7 = anglestoforward( var_5 );
    var_8 = vectordot( var_7, var_4 );
    var_9 = var_8 * var_6;
    var_10 = getdvarint( "_encstr_B1952377289857123DC97251D061C095AB18DA6557471B5D39F097BD7584E6E92F9DCF18BB", 20 );
    var_11 = getdvarint( "_encstr_A42A21CB498B51EACDE1E0F137506AA07DDB4848A16822EDCF80971DFB9F58A3F62247", -70 );

    if ( var_9 > 0 )
        var_9 = min( var_10, var_9 );
    else
        var_9 = max( var_11, var_9 );

    self setplayerangles( ( var_9, self.angles[1], 0 ) );

    if ( self getcurrentprimaryweapon().classname != "_encstr_AABA05236DC831" )
        self forceplaygestureviewmodel( "_encstr_B48211EC959BF5A7BD5BC42DCAF56E071B2C47" );

    wait 1;
    self skydive_setbasejumpingstatus( 0 );
    self skydive_setdeploymentstatus( 0 );
    wait 0.5;
    self freezecontrols( 0 );
    self freezelookcontrols( 1 );
    self allowsprint( 0 );
    thread _id_12720();
    _id_125B8( var_0 );

    if ( istrue( var_1 ) )
        wait 0.5;
    else
        wait 1.0;

    self freezelookcontrols( 0 );

    if ( istrue( var_1 ) )
        wait 0.5;
    else
        wait 1.0;

    self allowsprint( 1 );
}

_id_125B8( var_0 )
{
    if ( !self hasweapon( var_0 ) )
        scripts\cp_mp\utility\inventory_utility::_giveweapon( var_0, undefined, undefined, 1 );

    if ( self getcurrentprimaryweapon().classname == "_encstr_AABA05236DC831" )
        thread scripts\cp_mp\utility\inventory_utility::_switchtoweaponimmediate( var_0 );
}

_id_11ECD( var_0 )
{
    foreach ( var_2 in level.players )
    {
        if ( !isalive( var_2 ) )
            continue;

        if ( scripts\engine\utility::array_contains( var_0, var_2.team ) )
        {
            var_2 scripts\mp\hud_message::showsplash( "_encstr_97871A16BAD1EF317587A8C83B950E2D4BA2AFAAD30AA7BE34BF1890" );
            continue;
        }

        var_2 scripts\mp\hud_message::showsplash( "_encstr_B6921B3A88A7CF97A0B57481D749A7503130513228BF8737D8256095EE" );
    }
}

clear_tier_lights_all( var_0 )
{
    _id_11ECD( var_0 );

    foreach ( var_2 in var_0 )
    {
        var_3 = level.teamdata[var_2]["_encstr_A31C0D41AACF5C484A3493BB25AAB0"];

        foreach ( var_5 in var_3 )
        {
            if ( isalive( var_5 ) && !var_5 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
            {
                if ( level.disable_super_in_turret.spawndomplateflagtestmap )
                    var_5 _id_125FC();

                var_5 _id_1250E();
            }
        }
    }
}

_id_1250E()
{
    if ( istrue( self.inlaststand ) )
        scripts\mp\laststand::playanim_aibegindismountturret( "_encstr_9DDE142F87F488BE2D30CBB7832D390F8B7666634043", self );

    scripts\cp_mp\killstreaks\juggernaut::tryusejuggernaut( 1 );

    if ( level.disable_super_in_turret.vehicle_occupancy_friendlystatuschangedcallback > 0 && level.disable_super_in_turret.vehicle_occupancy_getreserving )
    {
        objective_icon( self.juggcontext.juggobjid, "_encstr_8AAD13A58DEDDCD7BB0B5E83F65ACD47FA35EAD93B" );
        objective_state( self.juggcontext.juggobjid, "_encstr_A65A0856F3802ACA0D6B" );
        objective_setzoffset( self.juggcontext.juggobjid, 70 );
        objective_setprogress( self.juggcontext.juggobjid, 0.99 );
        objective_setshowprogress( self.juggcontext.juggobjid, 1 );
        objective_setprogressteam( self.juggcontext.juggobjid, self.team );
        objective_setbackground( self.juggcontext.juggobjid, 1 );
        _func_421( self.juggcontext.juggobjid, 1 );
    }
}

onplayerdamaged( var_0 )
{
    if ( level.disable_super_in_turret.vehicle_occupancy_friendlystatuschangedcallback > 0 && level.disable_super_in_turret.vehicle_occupancy_getreserving && istrue( var_0.victim.isjuggernaut ) )
    {
        var_1 = var_0.victim.health / var_0.victim.maxhealth;
        objective_setprogress( var_0.victim.juggcontext.juggobjid, var_1 );

        if ( isdefined( var_0.attacker ) )
            var_0.attacker thread _id_12612( var_0.victim.juggcontext.juggobjid, var_0.victim );
    }
}

_id_12612( var_0, var_1 )
{
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self notify( "_encstr_A297136133923BA0E282B0687DDA907DEA3B2BE58F" );
    self endon( "_encstr_A297136133923BA0E282B0687DDA907DEA3B2BE58F" );
    objective_pinforclient( var_0, self );
    var_1 scripts\engine\utility::waittill_notify_or_timeout( "_encstr_A3750609A5E61883", 1 );
    objective_unpinforclient( var_0, self );
}

_id_13283()
{
    if ( !level.disable_super_in_turret._id_146E2 )
        return;

    level.disable_super_in_turret._id_14693 = spawnstruct();
    level.disable_super_in_turret._id_14693.powers = [];
    battlepassxpmultipliers( level.disable_super_in_turret._id_14693, "_encstr_81DD05A65DB683", [ "_encstr_88120D2E67472A1D50867B441B3037", "_encstr_8C0711B2A3BD9DCE63CA0BC8B9EBE8A139F6BB", "_encstr_A4391756C232CDF585ADA5D689B7F50B36C695E6CD5A4C6356" ], ::_id_12716, 0, undefined, ::_id_12718, undefined, &"_encstr_B46C1470AF08C3B831E78380534937E7DDE6B8799467", undefined, 6, "_encstr_B2730B4B0B69DB8B70E1DBE3DB", "_encstr_B44C0DEA9557EB497202C0905ACAC7" );
    battlepassxpmultipliers( level.disable_super_in_turret._id_14693, "_encstr_B1C1096DCDED30067B5293", [ "_encstr_B12F0D7EC39727EF987FBCB83D9833", "_encstr_8A5E11A5A3FF74C709F561E4D791308980F5CF", "_encstr_B885174277A4CB71D9B7F490FD30CE475F3F71E76BD076CC10" ], ::_id_1271B, 0 );
    battlepassxpmultipliers( level.disable_super_in_turret._id_14693, "_encstr_AD1804EF916E", "_encstr_BA5F07B2CDD6F6B6AC", ::_id_12707, 0, ::_id_1270A, ::_id_12708, ::_id_12709, &"_encstr_B4C213CF09111D815B6F381E160F0857E5A5E55131", undefined, 15, "_encstr_8BEC117616E68EE42B9BB046ACD447168EABCD", "_encstr_A84A1314FE932FD3FD2B80A0EF202B873AA29DA6D2" );
    battlepassxpmultipliers( level.disable_super_in_turret._id_14693, "_encstr_AA180449BD98", "_encstr_AD0D0653443BF7B7", ::_id_12703, 0, undefined, undefined, undefined, &"_encstr_A3580BC1B931C23BDFB801B060", undefined, 15, "_encstr_B47E0AACB5833547851DEA6E", "_encstr_89160CAB0D42D96EEF3A0B9103E7" );

    if ( getdvarint( "_encstr_A8791F63213D3F5103D78273B7818A930F0A60860F21BFA6578947CD73898FE573", 1 ) )
        battlepassxpmultipliers( level.disable_super_in_turret._id_14693, "_encstr_BD010BAFE753C81002A1D12892", [ "_encstr_808C148A828A33F023B7D540679798EBF97B08C89AA3" ], ::_id_1270B, 0, undefined, ::_id_1270C );
}

battlepassxpmultipliers( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12 )
{
    var_13 = "_encstr_98F0129042FADE2955E6D2FAC0B7E9373BFFF32F" + var_1;

    if ( getdvarint( var_13, 1 ) == 0 )
        return;

    if ( isstring( var_2 ) )
        var_2 = [ var_2 ];

    var_0.powers[var_1] = spawnstruct();
    var_0.powers[var_1].clients_hacked = var_2;
    var_0.powers[var_1].func = var_3;
    var_0.powers[var_1]._id_1387B = var_5;
    var_0.powers[var_1].has_ammo_drain_passive = var_6;
    var_0.powers[var_1]._id_127FC = var_7;
    var_0.powers[var_1].label = var_8;
    var_0.powers[var_1].waitforstreamsynccomplete = var_9;
    var_0.powers[var_1].idmask = var_10;
    var_0.powers[var_1]._id_1388F = var_11;
    var_0.powers[var_1]._id_128BE = var_12;
    var_0.powers[var_1]._id_13060 = var_4;
}

_id_1270B( var_0, var_1 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self notify( "_encstr_8C01158FADA24301DACBE0F803E9D9E74A9298164FD859" );
    self endon( "_encstr_8C01158FADA24301DACBE0F803E9D9E74A9298164FD859" );
    var_2 = gettime() + getdvarint( "_encstr_89D121EB5F08492B9E46133BCB6047BE68BF7F528F680DABD01B3A127140C733B1B3FB", 500 );

    while ( var_2 > gettime() )
    {
        if ( self secondaryoffhandbuttonpressed() )
        {
            self notify( "_encstr_AD1804EF916E" );
            break;
        }
        else if ( self fragbuttonpressed() )
        {
            self notify( "_encstr_AA180449BD98" );
            break;
        }

        waitframe();
    }
}

_id_12703( var_0, var_1 )
{
    var_2 = 60;
    var_3 = 1;
    var_4 = 64;
    var_5 = var_4 * var_4;
    var_6 = 768;
    var_7 = var_6 * var_6;
    var_8 = "_encstr_BA0B119A1160317F59FB0962202EB7F9B8912A";
    var_9 = self;
    var_9 enableplayerbreathsystem( 0 );
    var_9 playsoundonmovingent( var_8 );
    var_9 playsoundtoplayer( "_encstr_A10A140ACB88FF4F5B6FC29BA8814528A841C292C333", self, self );
    var_9 playsound( "_encstr_BD4718E2981E7F0E33471FEF4BF65FAA1B5FA75093B9CC8AA303", var_9, var_9 );
    var_9 thread _id_14697( 2 );
    var_10 = anglestoforward( var_9.angles );
    playfx( level.disable_super_in_turret.empvfx, var_9.origin, var_10 );
    var_11 = getcompleteweaponname( "_encstr_97641895ADC1F52339B773CAFACDBDDCAF073616F2AC9CD7DA1C" );
    var_12 = getcompleteweaponname( "_encstr_9D0D1F7248C1C98B5BB8666558205F4D77386A8A40B3FA2FB193629D6E4BD7D591" );
    var_13 = scripts\cp_mp\emp_debuff::get_emp_ents();

    foreach ( var_15 in var_13 )
    {
        var_16 = var_15.owner;

        if ( isdefined( var_16 ) )
        {
            if ( var_16 != var_9 && !scripts\cp_mp\utility\player_utility::playersareenemies( var_9, var_16 ) )
                continue;
        }

        var_17 = distancesquared( var_9.origin, var_15.origin );

        if ( var_17 > var_7 )
            continue;

        var_18 = scripts\engine\utility::ter_op( var_17 > var_5, var_11, var_12 );
        var_15 dodamage( 1, var_9.origin, var_9, var_9, "_encstr_A45C0E4B9FDF3165A3B93C4491BFA4A9", var_18 );
        var_15 playsoundonmovingent( "_encstr_BDFF1368FA70AFBA5101A7771387A2CB386627F5D3" );
        var_19 = scripts\cp_mp\utility\damage_utility::packdamagedata( var_9, var_15, 1, var_18, "_encstr_A45C0E4B9FDF3165A3B93C4491BFA4A9", var_9, var_9.origin );
        thread _id_126F9( var_19 );
    }

    var_21 = getcompleteweaponname( "_encstr_B2931468F730D6F113F510ADC10BD9D9914F58411FE8" );
    var_22 = undefined;

    if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "_encstr_AAB0079B102F47FF38", "_encstr_87C013CF152BE3855B58DAA3E0E3FD13610D5955B6" ) )
        var_22 = [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "_encstr_AAB0079B102F47FF38", "_encstr_87C013CF152BE3855B58DAA3E0E3FD13610D5955B6" ) ]]( var_9.origin, var_6 );

    foreach ( var_24 in var_22 )
    {
        if ( var_24 == var_9 )
            continue;

        if ( var_24 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
            continue;

        if ( !var_24 scripts\cp_mp\emp_debuff::can_emp_player() )
            continue;

        if ( var_24 != var_9 && !scripts\cp_mp\utility\player_utility::playersareenemies( var_9, var_24 ) )
            continue;

        var_24 dodamage( 1, var_9.origin, var_9, var_9, "_encstr_A45C0E4B9FDF3165A3B93C4491BFA4A9", var_21 );
        var_19 = scripts\cp_mp\utility\damage_utility::packdamagedata( var_9, var_24, 1, var_21, "_encstr_A45C0E4B9FDF3165A3B93C4491BFA4A9", var_9, var_9.origin );
        thread _id_126F9( var_19 );
    }

    thread _id_1262C( var_0, var_1 );
}

_id_14697( var_0 )
{
    if ( isdefined( var_0 ) )
        wait( var_0 );

    self enableplayerbreathsystem( 1 );
}

_id_1262C( var_0, var_1 )
{
    if ( level.disable_super_in_turret.spawndistancemax )
        self._id_12821[var_1].choppergunner_refillmissiles scripts\mp\hud_util::updatebar( 1.0, 0 );
    else
        self._id_12821[var_1].frac = 1.0;

    thread _id_12639( var_0, var_1 );
}

_id_1270C( var_0, var_1 )
{
    self notify( "_encstr_8C01158FADA24301DACBE0F803E9D9E74A9298164FD859" );
}

_id_12720()
{
    if ( !level.disable_super_in_turret._id_146E2 )
        return;

    thread _id_126B4( level.disable_super_in_turret._id_14693 );
}

_id_126B4( var_0 )
{
    thread _id_12637( var_0 );
    thread _id_12634( var_0 );
    thread _id_12635( var_0 );

    if ( level.disable_super_in_turret.spawndistancemax )
        thread _id_1263A( var_0 );

    thread _id_12638( var_0 );
    thread _id_12630( var_0 );

    foreach ( var_3, var_2 in var_0.powers )
    {
        if ( isdefined( var_0.powers[var_3]._id_1388F ) )
            _id_14033( var_0.powers[var_3]._id_1388F, 2 );
    }
}

_id_126F9( var_0 )
{
    var_1 = 5;
    var_2 = 2;
    scripts\cp_mp\emp_debuff::apply_emp_struct( var_0 );
    var_3 = var_1;

    if ( isplayer( var_0.victim ) )
    {
        var_0.victim.unmark_on_death = 1;
        var_0.victim playsound( "_encstr_9DFF135D4BABAF98D5A22EE08D90E046436FC1E98B" );

        if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "_encstr_B40D05E05627D6", "_encstr_80C90886B0370A95E4D6" ) )
        {
            if ( var_0.victim != self && var_0.victim [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "_encstr_B40D05E05627D6", "_encstr_80C90886B0370A95E4D6" ) ]]( "_encstr_8833157EDA920790D9030868E7F5289999C2FD86742BE1" ) )
            {
                var_3 = var_2;

                if ( scripts\cp_mp\utility\script_utility::issharedfuncdefined( "_encstr_B8BE07320B5B16ECAC", "_encstr_BDBD15BFDFCF2FABBDEDBE3058921F78ADBA11AE9E413B" ) )
                    self [[ scripts\cp_mp\utility\script_utility::getsharedfunc( "_encstr_B8BE07320B5B16ECAC", "_encstr_BDBD15BFDFCF2FABBDEDBE3058921F78ADBA11AE9E413B" ) ]]( "_encstr_8A760D43963AE8168D9356CD4BB93A" );
            }
        }
    }

    moraleslaptopthink( var_0, var_3 );

    if ( isdefined( var_0.victim ) )
    {
        var_0.victim.unmark_on_death = undefined;
        var_0.victim scripts\cp_mp\emp_debuff::remove_emp();
    }
}

_id_1270A( var_0, var_1 )
{
    scripts\mp\equipment::giveequipment( "_encstr_B84B129FEB68A9BB187F2F6F273CA31D18715767", "_encstr_B98F0AC7D5B99F4DDBA8353B" );
    scripts\mp\equipment::setequipmentslotammo( "_encstr_B98F0AC7D5B99F4DDBA8353B", 1 );
}

_id_12707( var_0, var_1 )
{
    self endon( "_encstr_BC630CF633331AC237327D959B8C" );
    self waittill( "_encstr_AD620DEC4ECA7358912BAF99B43959", var_2, var_3, var_4, var_5 );

    if ( !scripts\mp\utility\weapon::grenadethrown( var_2 ) )
        return;

    self playsound( "_encstr_BC1B131B30FBA78AE5B5954E2DE3C136A0A1D3BB90", self, self );
    thread _id_1262C( var_0, var_1 );
}

_id_12709( var_0, var_1 )
{
    scripts\mp\equipment::setequipmentslotammo( "_encstr_B98F0AC7D5B99F4DDBA8353B", 1 );
}

_id_12708( var_0, var_1 )
{
    scripts\mp\equipment::takeequipment( "_encstr_B98F0AC7D5B99F4DDBA8353B" );
}

moraleslaptopthink( var_0, var_1 )
{
    var_0.victim endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    var_2 = scripts\engine\utility::waittill_notify_or_timeout_return( "_encstr_94C40C10B78B0F2174E539DB4D8C", var_1 );

    if ( var_2 != "_encstr_94C40C10B78B0F2174E539DB4D8C" )
        var_0.empremoved = 1;
}

_id_12630( var_0 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    scripts\engine\utility::_id_143A6( "_encstr_A3750609A5E61883", "_encstr_827F0D381AB535D86F5FBD386BB7A3", "_encstr_81290B4A27A329DFF5412F9B13" );
    thread _id_1262D( var_0 );
    thread _id_12632( var_0 );
    thread _id_12633( var_0 );
    thread _id_12631( var_0 );
}

_id_12637( var_0 )
{
    if ( isbot( self ) )
        return;

    foreach ( var_6, var_2 in var_0.powers )
    {
        foreach ( var_4 in var_2.clients_hacked )
            self notifyonplayercommand( var_6, var_4 );
    }
}

_id_12631( var_0 )
{
    if ( !isdefined( self._id_12821 ) )
        return;

    if ( level.disable_super_in_turret.spawndistancemax )
    {
        foreach ( var_2 in self._id_12821 )
        {
            if ( isdefined( var_2 ) )
            {
                if ( isdefined( var_2.choppergunner_refillmissiles ) )
                    var_2.choppergunner_refillmissiles scripts\mp\hud_util::destroyelem();

                var_2 destroy();
            }
        }
    }

    self._id_12821 = undefined;
}

_id_12634( var_0 )
{
    var_1 = 200;
    var_2 = 18;
    var_3 = var_1;
    self._id_12821 = [];

    foreach ( var_6, var_5 in var_0.powers )
    {
        if ( isdefined( var_5.label ) )
        {
            if ( level.disable_super_in_turret.spawndistancemax )
                self._id_12821[var_6] = _id_1262F( var_5.label, var_5.waitforstreamsynccomplete, var_3, var_5._id_13060 );
            else
            {
                self._id_12821[var_6] = spawnstruct();
                self._id_12821[var_6].frac = 0;
            }

            self._id_12821[var_6].incooldown = 0;
            var_3 = var_3 + var_2;
        }
    }
}

_id_1262F( var_0, var_1, var_2, var_3 )
{
    var_4 = scripts\mp\hud_util::createfontstring( "_encstr_AA1608C07786F13312D3", 1.5 );
    var_4.x = 15;
    var_4.y = var_2;
    var_4.alignx = "_encstr_B1AD05C65666E8";
    var_4.aligny = "_encstr_B91904EC4718";
    var_4.horzalign = "_encstr_A31610D8EA27292E4FB4E2659B23D1CD0D72";
    var_4.vertalign = "_encstr_A16F0FA3DB38EBB0234DAE9B1D2C98B156";
    var_4.alpha = var_3;
    var_4.glowalpha = 0;
    var_4.hidewheninmenu = 1;
    var_4.archived = 0;

    if ( isdefined( var_1 ) && !scripts\engine\utility::is_player_gamepad_enabled() )
        var_4.label = var_1;
    else if ( isdefined( var_0 ) )
        var_4.label = var_0;

    var_5 = scripts\mp\hud_util::createbar( ( 1, 1, 1 ), 160, 14 );
    var_5.x = 13;
    var_5.y = var_2;
    var_5.alignx = "_encstr_B1AD05C65666E8";
    var_5.aligny = "_encstr_B91904EC4718";
    var_5.horzalign = "_encstr_A31610D8EA27292E4FB4E2659B23D1CD0D72";
    var_5.vertalign = "_encstr_A16F0FA3DB38EBB0234DAE9B1D2C98B156";
    var_5.alpha = var_3;
    var_5 _id_132A8();
    var_5.archived = 0;
    var_5.hidewheninmenu = 1;
    var_5.bar.archived = 0;
    var_5.bar.hidewheninmenu = 1;
    var_5.bar.alpha = var_3;
    var_4.choppergunner_refillmissiles = var_5;
    return var_4;
}

_id_132A8( var_0, var_1, var_2, var_3 )
{
    self.bar.horzalign = self.horzalign;
    self.bar.vertalign = self.vertalign;
    self.bar.alignx = "_encstr_B1AD05C65666E8";
    self.bar.aligny = self.aligny;
    self.bar.y = self.y + 2;
    self.bar.x = self.x + 2;
    scripts\mp\hud_util::updatebar( self.bar.frac );
}

_id_12632( var_0 )
{
    if ( isbot( self ) )
        return;

    foreach ( var_6, var_2 in var_0.powers )
    {
        foreach ( var_4 in var_2.clients_hacked )
            self notifyonplayercommandremove( var_6, var_4 );
    }
}

_id_12633( var_0 )
{
    foreach ( var_3, var_2 in var_0.powers )
    {
        if ( isdefined( var_2.has_ammo_drain_passive ) )
            self thread [[ var_2.has_ammo_drain_passive ]]( var_0, var_3 );
    }
}

_id_1262D( var_0 )
{
    if ( !isdefined( var_0 ) || !isdefined( self._id_12821 ) )
        return;

    self notify( "_encstr_B29710BC43DA075DF34B6B77289CE2500328" );

    foreach ( var_3, var_2 in var_0.powers )
    {
        if ( !isdefined( self._id_12821[var_3] ) )
            continue;

        self._id_12821[var_3].incooldown = 0;

        if ( level.disable_super_in_turret.spawndistancemax )
            self._id_12821[var_3].choppergunner_refillmissiles scripts\mp\hud_util::updatebar( 0, 0 );
        else
            self._id_12821[var_3].frac = 0;

        thread _id_12639( var_0, var_3 );
    }

    self.laststandattackermodifiers = undefined;
    self.vehicle_occupancy_mp_hidecashbag = undefined;
}

_id_12BBA( var_0 )
{
    if ( !isdefined( level.teamdata[var_0]["_encstr_BCFC1079C15083B786C063DACB6B8F3D785D"] ) )
        return level.teamdata[var_0]["_encstr_892A0BA3D3F25C4033ADD34893"];
    else
        return level.teamdata[var_0]["_encstr_BCFC1079C15083B786C063DACB6B8F3D785D"];
}

wait_for_chopper_boss_finish_turning( var_0, var_1 )
{
    var_2 = self;
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    var_2 endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    var_2 notify( "_encstr_9CE80F273F2A5FC8A7A6AB83CD7F9083A2" );
    var_2 notify( "_encstr_81290B4A27A329DFF5412F9B13" );
    var_2 notify( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );

    if ( istrue( var_2.respawningfromtoken ) )
        return;

    var_3 = var_0;
    var_4 = "_encstr_809110348850AFAD8FB023EA60EF253B49E5";

    if ( !isalive( var_2 ) && istrue( var_2.delay_enter_combat_after_investigating_grenade ) )
    {
        if ( !level.disable_super_in_turret.fluctuatevalues )
            var_2 _id_1267D( 1 );

        [var_3, var_4] = _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_125C7( var_0, var_1, 0, 1, "_encstr_814C0E2AF8E0C31C8BA0117A90CB9397" );
    }
    else if ( istrue( var_3.hasrespawntoken ) )
        var_3 _encstr_823124376CE42DC11DCD5EB6E0CB3BB0ADAC3A2FE056CDBC314EAF83A536DAAB079BE2D9B9B1::removerespawntoken();

    var_2.respawningfromtoken = 1;
    var_6 = var_2 _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::_id_126E8();

    if ( var_6 )
        var_2 scripts\mp\utility\lower_message::setlowermessageomnvar( 0 );

    var_2 scripts\mp\hud_message::heartbeat_sensor_pick_up_monitor();

    if ( level.disable_super_in_turret.fluctuatevalues )
        var_2 _encstr_9DF529B76033E98361365DC59FEFCAA978C823E790894BBEA54E597F0F03A26402C8FFF778C280F6F7E65E::_id_126FA( 1 );
    else
        var_2 _id_12723( 0 );

    var_2 freezecontrols( 0 );
    var_2 freezelookcontrols( 0 );
    var_2 allowsprint( 1 );
    var_7 = "_encstr_AF0D18FE5239076BAC3F88510FF16067C2B16EF52F72F1708737";
    var_8 = var_0;
    var_2 thread scripts\mp\hud_message::showsplash( var_7, undefined, var_0 );
    var_2.respawningfromtoken = undefined;
}

_id_12638( var_0 )
{
    foreach ( var_3, var_2 in var_0.powers )
    {
        if ( isdefined( var_2._id_1387B ) )
            self thread [[ var_2._id_1387B ]]( var_0, var_3 );
    }
}

_id_12635( var_0 )
{
    if ( isbot( self ) )
        return;

    foreach ( var_3, var_2 in var_0.powers )
        thread _id_12636( var_0, var_3 );
}

_id_12636( var_0, var_1 )
{
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_81290B4A27A329DFF5412F9B13" );
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );

    for (;;)
    {
        self waittill( var_1 );
        waittillframeend;

        if ( isdefined( self._id_12821[var_1] ) && self._id_12821[var_1].incooldown )
        {
            _id_12614();
            continue;
        }

        self thread [[ var_0.powers[var_1].func ]]( var_0, var_1 );
    }
}

_id_12614()
{
    if ( !isdefined( self.laststandattackermodifiers ) || gettime() > self.laststandattackermodifiers )
    {
        self playlocalsound( "_encstr_B9A80F8927EB0E9636B6AE38D746B2B9F2" );
        self.laststandattackermodifiers = gettime() + 1000;
    }
}

_id_1263A( var_0 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_81290B4A27A329DFF5412F9B13" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );

    if ( isbot( self ) )
        return;

    waittillframeend;
    var_1 = scripts\engine\utility::is_player_gamepad_enabled();

    for (;;)
    {
        var_2 = scripts\engine\utility::is_player_gamepad_enabled();

        if ( var_2 != var_1 )
        {
            var_1 = var_2;

            if ( var_2 )
            {
                foreach ( var_5, var_4 in var_0.powers )
                {
                    if ( isdefined( var_4.waitforstreamsynccomplete ) )
                        self._id_12821[var_5].label = var_4.label;
                }
            }
            else
            {
                foreach ( var_5, var_4 in var_0.powers )
                {
                    if ( isdefined( var_4.waitforstreamsynccomplete ) )
                        self._id_12821[var_5].label = var_4.waitforstreamsynccomplete;
                }
            }
        }

        waitframe();
    }
}

_id_12639( var_0, var_1 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_81290B4A27A329DFF5412F9B13" );
    self endon( "_encstr_B29710BC43DA075DF34B6B77289CE2500328" );

    if ( !isdefined( self._id_12821[var_1] ) || istrue( self._id_12821[var_1].incooldown ) )
        return;

    var_2 = self._id_12821[var_1];

    if ( level.disable_super_in_turret._id_12820 && var_2.frac > 0 )
    {
        self._id_12821[var_1].incooldown = 1;
        var_3 = var_0.powers[var_1].idmask;
        var_4 = "_encstr_B77E1BC31EE3D73E4561330B83C772DFBBF54A77A6E84FC501C8EB6291" + var_1;

        if ( getdvarint( var_4, 0 ) != 0 )
            var_3 = getdvarint( var_4, 0 );

        thread _id_126DE( var_0, var_1, var_3, int( var_2.frac * 100 ) );
        var_5 = var_2.frac;
        var_3 = var_3 * var_5;

        if ( level.disable_super_in_turret.spawndistancemax )
        {
            var_2.choppergunner_refillmissiles.bar.color = ( 1, 0.6, 0 );
            var_2.choppergunner_refillmissiles.bar scaleovertime( var_3, 0, var_2.choppergunner_refillmissiles.height );
        }

        wait( var_3 );
        var_6 = "_encstr_8C13100703606BB040562AF7CB38FFB2C2D7" + var_1;
        self playlocalsound( var_6 );
        self._id_12821[var_1].incooldown = 0;
    }
    else
    {
        if ( level.disable_super_in_turret.spawndistancemax )
            var_2.choppergunner_refillmissiles scripts\mp\hud_util::updatebar( 0, 0 );
        else
            var_2.frac = 0;

        thread _id_126DE( var_0, var_1, 0, 0 );
    }

    if ( level.disable_super_in_turret.spawndistancemax )
        var_2.choppergunner_refillmissiles.bar.color = ( 1, 1, 1 );

    if ( isdefined( var_0.powers[var_1]._id_127FC ) )
        self [[ var_0.powers[var_1]._id_127FC ]]( var_0, var_1 );
}

_id_126DE( var_0, var_1, var_2, var_3 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_81290B4A27A329DFF5412F9B13" );
    self endon( "_encstr_B29710BC43DA075DF34B6B77289CE2500328" );

    if ( !isdefined( var_0.powers[var_1]._id_1388F ) || !isdefined( var_0.powers[var_1]._id_128BE ) )
        return;

    _id_14033( var_0.powers[var_1]._id_1388F, 1 );
    var_4 = var_2 * 1000 * var_3 / 100;
    var_5 = gettime();
    var_6 = var_5 + var_4;

    while ( gettime() < var_6 )
    {
        var_7 = gettime();
        var_8 = ( var_6 - gettime() ) / var_4;
        var_9 = var_8 * var_3;
        _id_14033( var_0.powers[var_1]._id_128BE, int( var_9 ) );
        waitframe();
    }

    _id_14033( var_0.powers[var_1]._id_128BE, 0 );
    _id_14033( var_0.powers[var_1]._id_1388F, 2 );
}

_id_14033( var_0, var_1 )
{
    var_2 = 0;
    var_3 = 0;

    switch ( var_0 )
    {
        case "_encstr_B2730B4B0B69DB8B70E1DBE3DB":
            var_2 = 0;
            var_3 = 2;
            break;
        case "_encstr_B44C0DEA9557EB497202C0905ACAC7":
            var_2 = 2;
            var_3 = 7;
            break;
        case "_encstr_B47E0AACB5833547851DEA6E":
            var_2 = 9;
            var_3 = 2;
            break;
        case "_encstr_89160CAB0D42D96EEF3A0B9103E7":
            var_2 = 11;
            var_3 = 7;
            break;
        case "_encstr_8BEC117616E68EE42B9BB046ACD447168EABCD":
            var_2 = 18;
            var_3 = 2;
            break;
        case "_encstr_A84A1314FE932FD3FD2B80A0EF202B873AA29DA6D2":
            var_2 = 20;
            var_3 = 7;
            break;
        case "_encstr_B9F20B101D171B094FBE8710BB":
            var_2 = 27;
            var_3 = 2;
            break;
        default:
            break;
    }

    if ( !isdefined( level._id_146E0 ) )
        level._id_146E0 = [];

    if ( !isdefined( level._id_146E0["_encstr_945114BD831E5143D92D171978B3EAA75F4748679057"] ) )
        level._id_146E0["_encstr_945114BD831E5143D92D171978B3EAA75F4748679057"] = 0;

    var_4 = int( pow( 2, var_3 ) ) - 1;
    var_5 = ( int( var_1 ) & var_4 ) << var_2;
    var_6 = ~( var_4 << var_2 );
    var_7 = self weaponswitchbuttonpressed( "_encstr_945114BD831E5143D92D171978B3EAA75F4748679057" );
    var_8 = var_7 & var_6;
    var_9 = var_8 + var_5;
    level._id_146E0["_encstr_945114BD831E5143D92D171978B3EAA75F4748679057"] = var_9;
    self setclientomnvar( "_encstr_945114BD831E5143D92D171978B3EAA75F4748679057", level._id_146E0["_encstr_945114BD831E5143D92D171978B3EAA75F4748679057"] );
}

_id_12716( var_0, var_1 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_88C61540E8C727399281DD0DF919A3A4D50D1133C1105B" );
    var_2 = -1;

    if ( _id_12717() )
    {
        _id_12614();
        return;
    }

    var_3 = getdvarfloat( "_encstr_AB6123FA8F1AF9D216CFC8B8018F3378DFC2855EF1928BD039BE0E38674A7F779F5B698383", 1.0 );
    var_4 = getdvarfloat( "_encstr_956F20E6D8C97D89E4AFE9C3C1D7E0EDBBB2399BAF35575B1CF55B2DCDD7CC270BC6", 0.25 );
    var_5 = getdvarint( "_encstr_81A7252F5EBB393D13C1109BEA81DB3D13A893BBDFC29D77B069272FB87F48086A046FC83043B0", var_2 );
    var_6 = var_3 * level.framedurationseconds;
    self.vehicle_occupancy_monitormovementcontrols = 0.0;
    self allowmelee( 0 );
    self disableoffhandweapons();

    while ( self ismantling() || self isthrowinggrenade() || self ismeleeing() || scripts\mp\utility\weapon::grenadeinpullback() )
        waitframe();

    thread _id_1270F();
    thread _id_13982();
    var_7 = undefined;
    var_8 = 0;

    if ( !isdefined( self.vehicle_occupancy_mp_hidecashbag ) || gettime() > self.vehicle_occupancy_mp_hidecashbag )
    {
        self playlocalsound( "_encstr_807A19B35B4F5380F3F987B3106B576AF7623B2DBF279BB4F978D3" );
        self.vehicle_occupancy_mp_hidecashbag = gettime() + 500;
    }

    if ( isdefined( var_0.powers[var_1]._id_1388F ) )
        _id_14033( var_0.powers[var_1]._id_1388F, 0 );

    while ( !_id_12717() )
    {
        if ( level.disable_super_in_turret.spawndistancemax )
            self._id_12821[var_1].choppergunner_refillmissiles scripts\mp\hud_util::updatebar( self.vehicle_occupancy_monitormovementcontrols, 0 );
        else
            self._id_12821[var_1].frac = self.vehicle_occupancy_monitormovementcontrols;

        var_9 = self.vehicle_occupancy_monitormovementcontrols;
        self.vehicle_occupancy_monitormovementcontrols = self.vehicle_occupancy_monitormovementcontrols + var_6;

        if ( self.vehicle_occupancy_monitormovementcontrols >= 1 )
        {
            self.vehicle_occupancy_monitormovementcontrols = 1.0;

            if ( var_5 >= 0 )
            {
                if ( !isdefined( var_7 ) )
                {
                    var_7 = gettime() + var_5 * 1000;

                    if ( level.disable_super_in_turret.spawndistancemax )
                        thread _id_1271A( var_1, var_5 );
                }

                if ( gettime() >= var_7 )
                    break;
            }
        }

        if ( level.disable_super_in_turret.spawndistancemax && var_9 < var_4 && self.vehicle_occupancy_monitormovementcontrols >= var_4 )
            self._id_12821[var_1].choppergunner_refillmissiles.bar.color = ( 0, 1, 0 );

        if ( var_9 < 1 && self.vehicle_occupancy_monitormovementcontrols >= 1 )
            self playlocalsound( "_encstr_8F29180DAB81E063BF66A21A8996279F2935856DF1D9AF9F69F8" );

        if ( isdefined( var_0.powers[var_1]._id_128BE ) )
        {
            var_8 = max( int( self.vehicle_occupancy_monitormovementcontrols * 100 ), 0 );
            _id_14033( var_0.powers[var_1]._id_128BE, var_8 );
        }

        waitframe();
    }

    thread _id_12719( var_0, var_1 );
}

_id_12717()
{
    return self getstance() == "_encstr_9F24062875D5FD98" || istrue( self.usingascender );
}

_id_1271C()
{
    if ( level.disable_super_in_turret.vehicle_occupancy_monitorturretcontrols != 0 )
    {
        var_0 = self.origin + ( 0, 0, level.disable_super_in_turret.vehicle_occupancy_monitorturretcontrols );
        var_1 = playerphysicstrace( self.origin, var_0 );

        if ( var_1 != var_0 )
            return 0;
    }

    if ( level.disable_super_in_turret.vehicle_occupancy_mp_changedseats != 0 )
    {
        var_2 = self geteye();
        var_0 = var_2 + ( 0, 0, level.disable_super_in_turret.vehicle_occupancy_mp_changedseats );
        var_3 = 10;
        var_4 = 20;
        var_5 = scripts\engine\trace::create_contents( 0, 1, 0, 1, 0, 0, 1 );
        var_1 = scripts\engine\trace::capsule_trace( var_2, var_0, var_3, var_4, ( 0, 0, 0 ), self, var_5 );

        if ( var_1["_encstr_B130095358E1B3930B687D"] != 1 )
            return 0;
    }

    return 1;
}

_id_12719( var_0, var_1 )
{
    self stopgestureviewmodel( "_encstr_A2421B76CA9BBED3EDAD139656FACD57C1AC4EA6EAB6C1C61A8527CE59" );
    self notify( "_encstr_BD4D1AFA68E8998AEE6577777D1BF2D220D0728E40305A624D636B2B" );
    self notify( "_encstr_88C61540E8C727399281DD0DF919A3A4D50D1133C1105B" );
    var_2 = getdvarfloat( "_encstr_956F20E6D8C97D89E4AFE9C3C1D7E0EDBBB2399BAF35575B1CF55B2DCDD7CC270BC6", 0.25 );
    var_3 = getdvarint( "_encstr_970F27D32145D9EE55A9F041E3E1034FBB88F3575732AD1DA3710D94B6AF8BC840EF3793390F6BEE4A", 1 );

    if ( self.vehicle_occupancy_monitormovementcontrols >= var_2 && !_id_12717() && _id_1271C() && !self ismantling() )
    {
        self playsoundtoplayer( "_encstr_AAE611420B3B4FF2C3A04A3358EBAD2B36F4AF", self, self );
        self playsound( "_encstr_A16416F487E0BE3757382B393557DA0EFA6E333C7D9B38D8", self, self );
        var_4 = getdvarfloat( "_encstr_A23020CA2332594D6A464BC31FBF21D7D8575342F668D32F6337A39138F7725BE071", 1300 );
        var_5 = self getplayerangles();
        thread _id_12711();
        _id_1250A( var_5, var_4, self.vehicle_occupancy_monitormovementcontrols );
        thread _id_126D7();
        thread _id_12528();
        self.laststandattackermodifiers = undefined;
        self.vehicle_occupancy_mp_hidecashbag = undefined;
    }
    else if ( var_3 )
    {
        if ( level.disable_super_in_turret.spawndistancemax )
            self._id_12821[var_1].choppergunner_refillmissiles.bar.frac = 0;
        else
            self._id_12821[var_1].frac = 0;

        _id_14033( var_0.powers[var_1]._id_128BE, 0 );
        self enableoffhandweapons();
        self allowmelee( 1 );
        self notify( "_encstr_BC8310B750A97B7BD185A2D4F58363369038" );
        _id_12614();
    }
    else
        _id_12614();

    _id_12718( var_0, var_1, 1 );
}

_id_1270F()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_88C61540E8C727399281DD0DF919A3A4D50D1133C1105B" );

    if ( self isgestureplaying( "_encstr_A2421B76CA9BBED3EDAD139656FACD57C1AC4EA6EAB6C1C61A8527CE59" ) )
        return;

    while ( self ismantling() || self isthrowinggrenade() || self ismeleeing() || scripts\mp\utility\weapon::grenadeinpullback() )
        waitframe();

    self forceplaygestureviewmodel( "_encstr_A2421B76CA9BBED3EDAD139656FACD57C1AC4EA6EAB6C1C61A8527CE59" );

    while ( self isgestureplaying( "_encstr_A2421B76CA9BBED3EDAD139656FACD57C1AC4EA6EAB6C1C61A8527CE59" ) )
    {
        if ( self isonladder() )
        {
            self stopgestureviewmodel( "_encstr_A2421B76CA9BBED3EDAD139656FACD57C1AC4EA6EAB6C1C61A8527CE59" );
            break;
        }

        waitframe();
    }
}

_id_12711()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self setscriptablepartstate( "_encstr_B7640B6ED65E8CD2CECA95330F", "_encstr_82F80FCDDE786179B9758E7A97B3B2E4BD", 0 );
    wait 0.2;
    self notify( "_encstr_BC8310B750A97B7BD185A2D4F58363369038" );
    self forceplaygestureviewmodel( "_encstr_8BF71539CDA036EBB878D0EBBA2987E392B03E52A51D1B" );

    while ( !_id_12715() )
        waitframe();

    self notify( "_encstr_890F15E220381BD44379DA236B8181C7D099507C4D634F" );
    self stopgestureviewmodel( "_encstr_8BF71539CDA036EBB878D0EBBA2987E392B03E52A51D1B" );
    self setscriptablepartstate( "_encstr_B7640B6ED65E8CD2CECA95330F", "_encstr_AA1608C07786F13312D3", 0 );
    self playsoundtoplayer( "_encstr_8CBC0E52D9A8F9FF0FB0520BBE67DBEA", self, self );
    self playsound( "_encstr_873217AA235AA9D87052CFCE32AFBB9B139999BBC2EB38DCB3", self, self );
    self playsound( "_encstr_ADBC0E6AA3E3B0800A7CCBE9A7756066", self, self );
    wait 0.2;
    self enableoffhandweapons();
    self allowmelee( 1 );
}

_id_12715()
{
    return self isonground() || self isonladder() || self ismantling();
}

_id_1250A( var_0, var_1, var_2, var_3 )
{
    var_4 = 1;
    var_5 = ( 0, 0, 20 );

    if ( !isdefined( var_3 ) )
        var_3 = var_5;

    var_6 = var_0;
    var_7 = ( 0, 0, 1 );
    var_8 = ( 1, 0, 0 );

    if ( getdvarint( "_encstr_ABB5289653FBDEFDA2B198905BB1919057FD9E0E977343DB0AD9C0103356792E6F6F2606050F2B1B35F2", var_4 ) )
    {
        var_7 = propwaitminigameinit();

        if ( !isdefined( var_7 ) )
            var_7 = ( 0, 0, 1 );

        var_9 = ( 0, var_6[1], 0 );
        var_10 = anglestoright( var_9 );
        var_8 = vectorcross( var_7, var_10 );
        var_11 = vectortoangles( var_8 );
        var_12 = angleclamp180( var_11[0] );
        var_13 = -85;
        var_14 = var_12;
        var_15 = var_6[0];

        if ( var_15 > var_12 )
            var_15 = var_12;

        var_16 = getdvarfloat( "_encstr_B1502F06E3159FCDB3C1A31BE1F15BAAF3CD0BFF56A4D7F5E14623EB1B3EB0DF87371BD0A72F1B9F5D909170109F17297B", -45.0 );
        var_17 = getdvarfloat( "_encstr_9F502F9B56AB9F463D296B43380FBA2763CD0213E070FF4DE111D32AA34F742F59A08AAA05F9A314F77029A228DF6DAF10", 0.0 );
        var_18 = ( var_15 - var_13 ) / ( var_14 - var_13 );
        var_19 = var_17 + var_18 * ( var_16 - var_17 );
        var_6 = ( var_15 + var_19, var_6[1], var_6[2] );
    }

    var_20 = getdvarfloat( "_encstr_9C5821FBC623E7EE98C9657ACB799227FC1F7A2B69682DCDAB40C90A6DD9702157FC29", 0.0 );

    if ( var_20 != 0.0 )
        var_6 = ( var_6[0] + var_20, var_6[1], var_6[2] );

    var_21 = anglestoforward( var_6 );
    var_22 = var_21 * var_2 * var_1;
    var_23 = self.origin + var_3;
    self setorigin( var_23 );
    self setvelocity( var_22 );
    glassradiusdamage( self.origin + ( 0, 0, 30 ), 30, 50, 51 );
    var_24 = anglestoforward( self.angles );
    var_25 = self.origin + ( 0, 0, 30 ) + var_24 * 15;
    radiusdamage( var_25, 100, 1, 1 );
}

_id_126D7()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    var_0 = getdvarfloat( "_encstr_896D17B96C9CBE89E4F5F4E11CFA58D2E4AF36BD9B4727BDC6", 400.0 );

    if ( var_0 <= 0.0 )
        return;

    var_1 = getdvarfloat( "_encstr_A11321B96C39BE89397D9E0F38BE2C4B27FAC6DBE6A3C9ED8DBEB50B3CF59BE09595C8", 1400.0 );
    wait 0.2;

    while ( !_id_12715() )
    {
        var_2 = self getnormalizedmovement();

        if ( length( var_2 ) > 0 )
        {
            var_3 = rotatevector( ( var_2[0], -1.0 * var_2[1], 0 ), self.angles );
            var_4 = self getvelocity();
            var_5 = length( var_4 );
            var_6 = var_3 * var_0 * level.framedurationseconds;
            var_7 = var_4 + var_6;
            var_8 = length( var_7 );

            if ( var_8 <= var_1 )
                self setvelocity( var_7 );
            else if ( var_5 < var_1 )
            {
                var_7 = vectornormalize( var_7 ) * var_1;
                self setvelocity( var_7 );
            }
        }

        waitframe();
    }
}

_id_12528()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_890F15E220381BD44379DA236B8181C7D099507C4D634F" );
    var_0 = getdvarfloat( "_encstr_BE23264A5B7BC9761296529937E14BA03AF788C9D008B4A71DF19F43721F334D13FF91D15B7B3D7D", 0.3 );

    if ( var_0 < 0 )
        return;

    if ( var_0 > 0 )
        wait( var_0 );

    self _meth_87B0();
}

isvalidpointinbounds( var_0, var_1, var_2, var_3, var_4 )
{
    level notify( "_encstr_9EC80CA072FB454143974EB364FF" );
    level endon( "_encstr_9EC80CA072FB454143974EB364FF" );
    var_5 = var_0 + var_1;
    var_6 = var_2 + var_3 * 20;
    var_7 = var_2 + var_4 * 20;

    for (;;)
        waitframe();
}

_id_1271B( var_0, var_1 )
{
    if ( isdefined( self.vehicle_occupancy_monitormovementcontrols ) )
        _id_12719( var_0, "_encstr_81DD05A65DB683" );
    else
        self notify( "_encstr_88C61540E8C727399281DD0DF919A3A4D50D1133C1105B" );
}

propwaitminigameinit( var_0, var_1 )
{
    if ( !isdefined( var_0 ) )
        var_2 = self;
    else
        var_2 = var_0;

    if ( !isdefined( var_1 ) )
        var_1 = 0;

    var_3 = [ var_2 ];
    var_4 = [ self.origin ];

    for ( var_5 = -1.0; var_5 <= 1.0; var_5 = var_5 + 2.0 )
    {
        for ( var_6 = -1.0; var_6 <= 1.0; var_6 = var_6 + 2.0 )
        {
            var_7 = var_2 getpointinbounds( var_5, var_6, 0.0 );
            var_7 = ( var_7[0], var_7[1], self.origin[2] );
            var_4[var_4.size] = var_7;
        }
    }

    var_8 = ( 0, 0, 0 );
    var_9 = 0;

    foreach ( var_11 in var_4 )
    {
        var_12 = scripts\engine\trace::_bullet_trace( var_11 + ( 0, 0, 4 ), var_11 + ( 0, 0, -16 ), 0, var_3 );
        var_13 = var_12["_encstr_B130095358E1B3930B687D"] > 0.0 && var_12["_encstr_B130095358E1B3930B687D"] < 1;

        if ( var_13 )
        {
            var_8 = var_8 + var_12["_encstr_930E073E8FC00DDF69"];
            var_9++;
        }
    }

    if ( var_9 > 0 )
    {
        var_8 = var_8 / var_9;
        return var_8;
    }
    else
        return undefined;
}

_id_12718( var_0, var_1, var_2 )
{
    if ( istrue( var_2 ) )
        thread _id_12639( var_0, var_1 );

    self.vehicle_occupancy_monitormovementcontrols = undefined;
}

_id_1271A( var_0, var_1 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_827F0D381AB535D86F5FBD386BB7A3" );
    self endon( "_encstr_88C61540E8C727399281DD0DF919A3A4D50D1133C1105B" );
    self endon( "_encstr_BD4D1AFA68E8998AEE6577777D1BF2D220D0728E40305A624D636B2B" );

    if ( var_1 <= 0 )
        return;

    var_2 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::can_killstreak_be_detected( var_1, int( var_1 * 5 ), 1 );
    var_3 = 1;

    for ( var_4 = 0; var_4 < var_2.size; var_4++ )
    {
        if ( var_3 )
            self._id_12821[var_0].choppergunner_refillmissiles.bar.color = ( 1, 0, 0 );
        else
            self._id_12821[var_0].choppergunner_refillmissiles.bar.color = ( 0, 1, 0 );

        wait( var_2[var_4] );
        var_3 = !var_3;
    }
}

_id_125D7( var_0, var_1 )
{
    var_2 = 1800;
    var_3 = spawnstruct();
    var_3.origin = self.origin;
    var_0 thread scripts\mp\equipment\concussion_grenade::applyconcussion( var_3, self );
    var_0 thread _id_1262E( level.disable_super_in_turret._id_14693 );
    var_4 = var_0.origin - self.origin;
    var_5 = vectortoangles( var_4 );
    var_6 = distance( var_0.origin, self.origin );
    var_7 = 1.0 - var_6 / var_1;
    var_0 _id_1250A( var_5, var_2, var_7 );
}

standard_health( var_0 )
{
    if ( isexplosivedamagemod( var_0.meansofdeath ) && var_0.objweapon.basename == "_encstr_9D0D1F7248C1C98B5BB8666558205F4D77386A8A40B3FA2FB193629D6E4BD7D591" || var_0.objweapon.basename == "_encstr_97641895ADC1F52339B773CAFACDBDDCAF073616F2AC9CD7DA1C" || var_0.objweapon.basename == "_encstr_B2931468F730D6F113F510ADC10BD9D9914F58411FE8" )
        return 1;
    else
        return 0;
}

_id_1262E( var_0 )
{
    if ( !isdefined( var_0 ) )
        return;

    self notify( "_encstr_B29710BC43DA075DF34B6B77289CE2500328" );

    foreach ( var_3, var_2 in var_0.powers )
    {
        if ( !isdefined( self._id_12821[var_3] ) )
            continue;

        self._id_12821[var_3].incooldown = 0;
        thread _id_1262C( var_0, var_3 );
    }
}

_id_13982()
{
    var_0 = self;
    var_0 endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    var_0 notify( "_encstr_893715479BBA58138119D1120A9D2BEBA0058153C0F098" );
    var_0 endon( "_encstr_893715479BBA58138119D1120A9D2BEBA0058153C0F098" );
    var_0 lerpfovbypreset( "_encstr_BA420DDD4757180B9B4F6A19C2BFCD" );
    var_0 waittill( "_encstr_BC8310B750A97B7BD185A2D4F58363369038" );
    var_0 lerpfovbypreset( "_encstr_AA880E02A0D02AB113F2AFD9EF4565E0" );
}

addtoteamlives( var_0, var_1 )
{
    var_0 _id_126D8();
}

removefromteamlives( var_0, var_1 )
{
    var_0 _id_126D8();
}

_id_125E9()
{
    return istrue( self.tut_popup_listener );
}

watch_flight_collision( var_0 )
{
    if ( _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() )
    {
        var_1 = isdefined( var_0.attacker ) && var_0.attacker nukefridgewatcher();

        if ( !var_1 || !level.disable_super_in_turret._id_1470A )
            return 0;

        thread _id_1262E( level.disable_super_in_turret._id_14693 );
        thread _id_1271D();
        thread _id_12731( var_0 );
        thread _id_12701();
    }

    return 1;
}

_id_12731( var_0 )
{
    var_1 = 500;
    var_2 = 90;
    var_3 = 60;
    var_4 = 30;
    var_5 = var_0.direction_vec;
    var_6 = vectortoyaw( var_5 );
    var_7 = var_2;
    var_8 = var_3;

    if ( scripts\engine\utility::cointoss() )
        var_8 = var_8 * -1;

    var_8 = var_8 + var_6;
    var_9 = ( var_7, var_8, 0 );
    var_10 = vectornormalize( ( var_5[0], var_5[1], 0 ) );
    var_11 = var_10 * var_4 + ( 0, 0, var_4 );
    _id_1250A( var_9, var_1, 1.0, var_11 );
}

_id_12701()
{
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self._id_1423B = 1;
    var_0 = getdvarfloat( "_encstr_8AEE1CAF782B374A95D8E098B727C3D5B080575BD0E649E293E5EDD49D33", 1.5 );
    wait( var_0 );
    self._id_1423B = undefined;
}

_id_1271D()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_B62B1411FAD375317F6BA9359580179933903BFA4B33" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self waittill( "_encstr_B7A21B1B1B424D019B336FC50B392CDB8F9BCBF870937B16873BC73712" );
    waittillframeend;
    self isholdingbreath( 1 );
    self.usedprops = 1;
    self.laststandreviveent makeunusable();
    var_0 = self.laststandreviveent;
    var_0.usetime = getdvarfloat( "_encstr_889B19C7B18B4ED81DD94B134BE1AD95C8FC0ED00AF904414138FF", 3.0 ) * 1000;

    if ( !isdefined( var_0.curprogress ) )
        var_0.curprogress = 0;

    while ( scripts\mp\utility\player::isreallyalive( self ) && var_0.curprogress < var_0.usetime )
    {
        if ( self isinexecutionvictim() )
        {
            waitframe();
            continue;
        }

        if ( !isdefined( var_0.userate ) )
            var_0.userate = 0;

        var_0.curprogress = var_0.curprogress + level.frameduration * var_0.userate;
        var_0.userate = 1;
        scripts\mp\gameobjects::updateuiprogress( var_0, 1 );

        if ( var_0.curprogress >= var_0.usetime )
            break;

        waitframe();
    }

    var_0.usetime = undefined;
    var_0.curprogress = undefined;
    var_0.userate = undefined;
    scripts\mp\laststand::playanim_aibegindismountturret( "_encstr_9DDE142F87F488BE2D30CBB7832D390F8B7666634043", self );
    self playsoundtoplayer( "_encstr_9B41177040F8B7C2E613571B11186AC1E009A17F1B38408A30", self, self );
    self playsound( "_encstr_81241B4A2FBD8EC37F829F95D323AE01506EC36B90ED9008E32A21088E" );
    self isholdingbreath( 0 );
}

_id_12810()
{
    if ( istrue( level.br_debugsolotest ) || level.gameended )
        return;

    var_0 = 0;
    var_1 = [];
    var_2 = [];

    foreach ( var_4 in level.teamnamelist )
    {
        var_5 = level.teamdata[var_4]["_encstr_97580AC41D811F767F3072CB"];

        if ( var_5 > 0 )
        {
            if ( level.teamdata[var_4]["_encstr_BCFC1079C15083B786C063DACB6B8F3D785D"] > 0 )
            {
                if ( ( level.disable_super_in_turret.vehicle_occupancy_getplayerfriendlyto || level.disable_super_in_turret.vehicle_occupancy_friendlystatuschangedcallback == 0 ) && var_2.size > 0 )
                    return;

                var_2[var_2.size] = var_4;
                var_0 = var_0 + level.teamdata[var_4]["_encstr_BCFC1079C15083B786C063DACB6B8F3D785D"];
                continue;
            }

            if ( level.teamdata[var_4]["_encstr_892A0BA3D3F25C4033ADD34893"] > 0 )
                var_1[var_1.size] = var_4;
        }
    }

    if ( !level.disable_super_in_turret.vehicle_occupancy_getplayerfriendlyto && var_0 <= level.disable_super_in_turret.vehicle_occupancy_friendlystatuschangedcallback )
    {
        level.disable_super_in_turret.vehicle_occupancy_getplayerfriendlyto = 1;
        thread clear_tier_lights_all( var_2 );

        if ( level.disable_super_in_turret._id_146E8 )
            level.disable_super_in_turret._id_146E7 = 0;
    }

    if ( var_2.size > 1 )
        return;

    var_7 = scripts\mp\utility\script::quicksort( var_1, ::_id_134D6 );

    for ( var_8 = 0; var_8 < var_7.size; var_8++ )
    {
        var_4 = var_7[var_8];
        var_9 = var_8 + 2;
        thread _encstr_97571CC31EE30FBA499B665A8327B7E7F8F54C512FA93F150D207EF2F097::_id_1209B( var_4, var_9, 0, 1 );
    }

    thread scripts\mp\gamelogic::endgame( var_2[0], game["_encstr_94EA0B2BE623AF39CA589BBDB9"]["_encstr_A636132B37CAB5A595DCF556B14BD696DC85A39591"] );
}

_id_134D6( var_0, var_1 )
{
    var_2 = level.teamdata[var_0]["_encstr_AD720F18CEEB38B2521F756B5789638895"];
    var_3 = level.teamdata[var_1]["_encstr_AD720F18CEEB38B2521F756B5789638895"];
    return var_2 >= var_3;
}

_id_1472D()
{
    wait 5.0;
    scripts\mp\utility\sound::besttime( "_encstr_8C9607C49CAF9E870E" );
}

_id_126D8()
{
    var_0 = self.team;
    level.teamdata[var_0]["_encstr_BCFC1079C15083B786C063DACB6B8F3D785D"] = 0;

    foreach ( var_2 in level.teamdata[var_0]["_encstr_A31C0D41AACF5C484A3493BB25AAB0"] )
    {
        if ( !var_2 _encstr_9E81231898C28383CB8760E558BF27EB18E74BB010797A7D4A032187800594B088064FFB1B::_id_125F3() && !var_2 _id_125E9() )
            level.teamdata[var_0]["_encstr_BCFC1079C15083B786C063DACB6B8F3D785D"]++;
    }
}
