// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

spawn_and_enter_cargo_truck_mg()
{
    level thread airfield_safehouse_loot();
}

airfield_safehouse_loot()
{
    level._id_13443["_encstr_AAE007D90BB9A5E61A"] = loadfx( "_encstr_97531F35435B48F8877259185C7D98970293B73FBF5227C8AC0183C8C54F10DBCB" );
    level.helidrivableenablesiteonflyaway["_encstr_AAE007D90BB9A5E61A"] = loadfx( "_encstr_9440460B9C18562BC4ABD9F163552AC373B665212899FBC0E72FD19BB3B0F20D773B02F575436093D68BBF32DB6158A03C91BBB3A0170180035837FF572FD38F79F29304FDD64F4B" );
    level.helidrivableenablesiteonflyaway["_encstr_B62907C3A61007BD50"] = loadfx( "_encstr_88D94403AC5156C14372C74B583089DB21B78D3FA0874A1D2918034F28187E62B75517F7F61DE64E9140D75B68CE388A71631F6EDB27FA6F1908DF7F7843D7D7E705F523CCB1" );
    level._id_1207B = ::airlock_show_back_doors;
    level.playerwaittospawn = ::airlock_button_r;
    level._effect["_encstr_8FB21F6766E1EB4CC9BE36DEBD8EBE8D2C36342BFAA17BC65A322CBC7D6CDB16D8"] = loadfx( "_encstr_A90D43D8F31080B32B58E076A2C6FB737C8780C06EA78143D272618F78FE3D79CB4B4870F36E103DCA98F006921161600FE3F9C8271330C32184D019ACFA436A5747F040BB" );

    if ( !scripts\mp\flags::levelflag( "_encstr_97EC123360481CB793B883EB058A0FFBA2C91DF3" ) )
        scripts\mp\flags::levelflagwait( "_encstr_97EC123360481CB793B883EB058A0FFBA2C91DF3" );

    airlock();
    var_0 = getdvarint( "_encstr_BA84133B629BE058DA1FFBE95CC978B06BBA36C03A", 0 ) == 1;

    if ( !var_0 )
        return;

    level.spawn_lot_paratroopers = 1;
    level thread airdrop_givecrateuseweapon();
    var_1 = getdvarint( "_encstr_87E81BE6B127F54CC9EBA186F532AC98D576AF6A0785EEE6154EACCACD", 0 ) == 1;

    if ( var_1 )
        level.spawn_and_enter_little_bird_mg = airduct_locations();
    else
        level.spawn_and_enter_little_bird_mg = airstrike_watchdeployweaponchange();

    all_but_one_player_in_vehicle();
    var_2 = getdvarint( "_encstr_BD6B1C22E3F3E96B7087A4402F4BB7C1AB0A56EB8BF06BDEB03370C0BF12", 0 ) == 1;

    for ( var_3 = 0; var_3 < level.spawn_and_enter_little_bird_mg.size; var_3++ )
    {
        if ( var_2 )
        {
            airdropbasecashamount( var_3 );
            continue;
        }

        airdrop_specialcasecanusecrate( var_3 );
    }

    foreach ( var_5 in level.spawn_and_enter_little_bird_mg )
        level thread airstrike_canbeused( var_5, 0, 1, 0 );

    var_7 = getdvarint( "_encstr_95781C936E93A74E3531423A4947C6370BD80E377EDEE3923388DAF38051", 1 ) == 1;

    if ( var_7 )
        level thread airholder();

    level thread airlock_callbutton_think();
    scripts\engine\scriptable::_id_12F5B( "_encstr_B7BE0C2B3028C75A5918661D7F01", ::airdrop_playdeploydialog );
    scripts\engine\scriptable::_id_12F5B( "_encstr_B94D1005B2A5C0B76359CB5062574E787D34", ::airstrike_movewithplane );
}

airlock_callbutton_think()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );

    for (;;)
    {
        level waittill( "_encstr_AA580E0A8D91B6D74E1142DA7E263FAB" );

        if ( !isdefined( level.spawn_and_enter_little_bird_mg ) )
            continue;

        foreach ( var_1 in level.spawn_and_enter_little_bird_mg )
            all_modes( var_1._id_13D19 );
    }
}

airdrop_givecrateuseweapon()
{
    scripts\mp\utility\sound::besttime( "_encstr_B4EA15F823B7483F9A8F60F365727B11F1678920872EA3" );
}

airlock_slot_think( var_0 )
{
    for ( var_1 = 0; var_1 < var_0.size; var_1++ )
    {
        var_2 = getdvarint( "_encstr_AFC41A97FF53D868F251809849DC200D9AA72D218F2A9A2031B20B76" + var_1, 0 ) == 1;

        if ( var_2 )
            var_0[var_1].complete_hack_console = 1;
    }

    for ( var_1 = var_0.size - 1; var_1 >= 0; var_1-- )
    {
        if ( istrue( var_0[var_1].complete_hack_console ) )
            var_0 = scripts\engine\utility::can_path_to_target( var_0, var_1 );
    }

    var_3 = getdvarint( "_encstr_8B88143B61366F8E889F4058873013EFC8FBA3C2090E", 6 );
    var_3 = min( var_3, var_0.size );
    var_4 = [];
    var_5 = scripts\engine\utility::array_randomize( var_0 );

    for ( var_1 = 0; var_1 < var_3; var_1++ )
        var_4[var_4.size] = var_5[var_1];

    return var_4;
}

airlock()
{
    airlock_stop( "_encstr_9EDF0778AA2789E9F3", "_encstr_947D1DD50340ED2F4F676C2845B028041AB7578A01D6A05D26A608A0F5FF05" );
    airlock_stop( "_encstr_9EDF0778AA2789E9F3", "_encstr_80BD20BAFB01B265029065391AA40A71E58B4FA997D9181F7025C76737963AEB1393" );
    airlock_stop( "_encstr_9EDF0778AA2789E9F3", "_encstr_A2BA1E11C23F40D55ADF91511F122FC8D41A3E89AE6B589DB1FBAF5107FA6738" );
}

airlock_stop( var_0, var_1 )
{
    var_2 = getentitylessscriptablearrayinradius( var_1, "_encstr_A8ED125A5723AF9B405770989B255F1FF3897A60" );

    foreach ( var_4 in var_2 )
        var_4 setscriptablepartstate( "_encstr_A39B05D63DA213", var_0, 0 );
}

airdrop_specialcasecanusecrate( var_0 )
{
    var_1 = level.spawn_and_enter_little_bird_mg[var_0].origin;
    var_2 = 5000;
    level.spawn_and_enter_little_bird_mg[var_0].hideintelinstancefromplayer = getentitylessscriptablearrayinradius( "_encstr_947D1DD50340ED2F4F676C2845B028041AB7578A01D6A05D26A608A0F5FF05", "_encstr_A8ED125A5723AF9B405770989B255F1FF3897A60", var_1, var_2 );
    level.spawn_and_enter_little_bird_mg[var_0].waypoints_creation = getentitylessscriptablearrayinradius( "_encstr_80BD20BAFB01B265029065391AA40A71E58B4FA997D9181F7025C76737963AEB1393", "_encstr_A8ED125A5723AF9B405770989B255F1FF3897A60", var_1, var_2 );
    level.spawn_and_enter_little_bird_mg[var_0].spawn_lootcrates_on_each_traincar = getentitylessscriptablearrayinradius( "_encstr_A2BA1E11C23F40D55ADF91511F122FC8D41A3E89AE6B589DB1FBAF5107FA6738", "_encstr_A8ED125A5723AF9B405770989B255F1FF3897A60", var_1, var_2 );
    var_3 = 5;
    var_4 = 5;
    var_5 = 10;
    airlock_back_blocker( level.spawn_and_enter_little_bird_mg[var_0].hideintelinstancefromplayer, var_0, var_3 );
    airlock_back_blocker( level.spawn_and_enter_little_bird_mg[var_0].waypoints_creation, var_0, var_4 );
    airlock_back_blocker( level.spawn_and_enter_little_bird_mg[var_0].spawn_lootcrates_on_each_traincar, var_0, var_5 );
}

airlock_back_blocker( var_0, var_1, var_2 )
{
    var_3 = randomint( var_2 );

    foreach ( var_5 in var_0 )
    {
        var_3++;
        var_3 = var_3 % var_2;
        var_5.spawn_maint_wave = var_1;
        var_5._id_11A25 = var_3;
    }
}

airstrike_watchdeployweaponchange()
{
    var_0 = scripts\engine\utility::getstructarray( "_encstr_A8F7152D9A31C06D576243C8EA1317F895F3CF8922672B", "_encstr_A8ED125A5723AF9B405770989B255F1FF3897A60" );
    var_1 = airlock_slot_think( var_0 );
    var_2 = [];

    foreach ( var_4 in var_1 )
    {
        var_5 = airstrike_removeactivestrike( var_4.origin );
        var_2[var_2.size] = var_5;
    }

    return var_2;
}

airholder()
{
    var_0 = getdvarint( "_encstr_95781C936E93A74E3531423A4947C6370BD80E377EDEE3923388DAF38051", 1 ) == 1;

    if ( var_0 )
        scripts\mp\flags::gameflagwait( "_encstr_989F0E38272BD6161DB143F532BDDC2B" );

    var_1 = 6;
    wait( var_1 );
    var_2 = 1;

    for ( var_3 = 0; var_3 < level.spawn_and_enter_little_bird_mg.size; var_3++ )
    {
        airstrike_addactivestrike( level.spawn_and_enter_little_bird_mg[var_3], var_2 );
        level thread airstrike_canbeused( level.spawn_and_enter_little_bird_mg[var_3], var_2, 1, 0 );
        level.spawn_and_enter_little_bird_mg[var_3] setscriptablepartstate( "_encstr_B9E50B23DEDA7D364BC9C6C659", "_encstr_948806DDD04BE895", 0 );
        level.spawn_and_enter_little_bird_mg[var_3]._id_13D19 _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::calloutmarkerping_watchwhenobjectivedeleted( 1 );
    }
}

airduct_locations()
{
    var_0 = [];
    var_1 = ( -1852, -1253, 0 );
    var_2 = airstrike_removeactivestrike( var_1 );
    var_0[var_0.size] = var_2;
    var_1 = ( -1859, -3900, 0 );
    var_2 = airstrike_removeactivestrike( var_1 );
    var_0[var_0.size] = var_2;
    return var_0;
}

airstrike_removeactivestrike( var_0 )
{
    var_1 = spawn( "_encstr_93DC0DCD1B272D3847AF5BED23B2C6", var_0 );
    var_1 setmodel( "_encstr_A47F1F14C19EFF748D286B132083EA579336659570403F3A5F50917B18F12922E3" );
    var_1.unset_relic_noregen = 1;
    return var_1;
}

airdropbasecashamount( var_0 )
{
    level.spawn_and_enter_little_bird_mg[var_0].hideintelinstancefromplayer = [];
    level.spawn_and_enter_little_bird_mg[var_0].waypoints_creation = [];
    level.spawn_and_enter_little_bird_mg[var_0].spawn_lootcrates_on_each_traincar = [];
    var_1 = [];
    var_1[0] = ( 100, 0, 0 );
    var_1[1] = ( -100, 0, 0 );
    var_1[2] = ( 0, 100, 0 );
    var_1[3] = ( 0, -100, 0 );
    var_2 = ( 0, 0, 0 );

    foreach ( var_4 in var_1 )
    {
        var_5 = level.spawn_and_enter_little_bird_mg[var_0].origin + var_4;
        var_6 = spawn_allies_at_defend( "_encstr_AA2E2272233864D21DB4879EB82F771273A94068218F62DF175F06E007D03B8FF059FFD3", var_5, var_2, 1 );
        level.spawn_and_enter_little_bird_mg[var_0].hideintelinstancefromplayer = scripts\engine\utility::array_add( level.spawn_and_enter_little_bird_mg[var_0].hideintelinstancefromplayer, var_6 );
        var_6 = spawn_allies_at_defend( "_encstr_9540253139D7C6B7F61DFAB036BBB05EDCD76E0EB0DD9B7DB10B8DA159F51BCAECB2E619B0C9F2", var_5, var_2, 1 );
        level.spawn_and_enter_little_bird_mg[var_0].waypoints_creation = scripts\engine\utility::array_add( level.spawn_and_enter_little_bird_mg[var_0].waypoints_creation, var_6 );
        var_6 = spawn_allies_at_defend( "_encstr_BAF923C44EFA1BEDDEA3FA58C6770BCB9BAFCDC185EE73AFC62C36D0B27DA17BD8B4C885F2", var_5, var_2, 1 );
        level.spawn_and_enter_little_bird_mg[var_0].spawn_lootcrates_on_each_traincar = scripts\engine\utility::array_add( level.spawn_and_enter_little_bird_mg[var_0].spawn_lootcrates_on_each_traincar, var_6 );
    }
}

spawn_allies_at_defend( var_0, var_1, var_2, var_3 )
{
    var_4 = easepower( var_0, var_1, var_2 );
    return var_4;
}

airstrike_addactivestrike( var_0, var_1 )
{
    if ( istrue( var_0.stopdragonsbreathburning ) )
        var_1 = 0;

    var_0._id_13A12 = var_1;

    switch ( var_1 )
    {
        case 0:
            var_0 setscriptablepartstate( "_encstr_8BE3078E16C6AD581C", "_encstr_9EDF0778AA2789E9F3", 0 );
            break;
        case 1:
            var_0 setscriptablepartstate( "_encstr_8BE3078E16C6AD581C", "_encstr_AB5F0AF22D3BEB582872209A", 0 );
            break;
        case 2:
            var_0 setscriptablepartstate( "_encstr_8BE3078E16C6AD581C", "_encstr_AD5F0A28774073F9FFD4CB0D", 0 );
            break;
        case 3:
            var_0 setscriptablepartstate( "_encstr_8BE3078E16C6AD581C", "_encstr_B81D0C52DB487F556FB34C0A225D", 0 );
            break;
    }
}

airstrike_canbeused( var_0, var_1, var_2, var_3 )
{
    var_0 notify( "_encstr_8B3110CDE5B71912C9403FEF2003F1427F06" );
    var_0 endon( "_encstr_8B3110CDE5B71912C9403FEF2003F1427F06" );
    var_0._id_13D1B = var_1;
    wait( var_3 );
    airdrop_watchforcrateuseend( "_encstr_9F6318D7D268B07B308F62930D3A15B1A5E8B609DD830B0CB272" + var_1 + "_encstr_8953151E88D38FDBA1BE6891D8095A1625B8E3C2180556" + var_2 );

    if ( isdefined( var_0._id_13D19.claimplayer ) )
        _encstr_890626F852FABB63A30BE831E0264973E59A7820FB57C7D0C312D83FC647500B0BA248E8766F3F91::destroy_vehicles( var_0._id_13D19.claimplayer, var_1 );

    switch ( var_1 )
    {
        case 0:
            var_0 setscriptablepartstate( "_encstr_9C5F0D339C4141D770E8B71F980884", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_9FEF054BD599BA", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_8FBA0CA49DC867E37FE3B02FEE0F", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_9D19053B41CE0B", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_BD5F0947E22A9FD91EBBF8", "_encstr_9EDF0778AA2789E9F3", 0 );

            if ( !istrue( var_0._id_12744 ) )
            {
                var_0 setscriptablepartstate( "_encstr_BCD50BD161DF40C53701ED29BA", "_encstr_9EDF0778AA2789E9F3", 0 );
                var_0 setscriptablepartstate( "_encstr_A16A0A8D5AEC34E8CDD77B73", "_encstr_9EDF0778AA2789E9F3", 0 );
            }

            break;
        case 1:
            var_0 setscriptablepartstate( "_encstr_9C5F0D339C4141D770E8B71F980884", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_9FEF054BD599BA", "_encstr_BE8B08B3B4CD963163B2", 0 );
            var_0 setscriptablepartstate( "_encstr_8FBA0CA49DC867E37FE3B02FEE0F", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_9D19053B41CE0B", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_BD5F0947E22A9FD91EBBF8", "_encstr_9EDF0778AA2789E9F3", 0 );

            if ( !istrue( var_0._id_12744 ) )
            {
                var_0 setscriptablepartstate( "_encstr_BCD50BD161DF40C53701ED29BA", "_encstr_9EDF0778AA2789E9F3", 0 );
                var_0 setscriptablepartstate( "_encstr_A16A0A8D5AEC34E8CDD77B73", "_encstr_9EDF0778AA2789E9F3", 0 );
            }

            break;
        case 2:
            var_0 setscriptablepartstate( "_encstr_9FEF054BD599BA", "_encstr_BE8B08B3B4CD963163B2", 0 );
            var_0 setscriptablepartstate( "_encstr_8FBA0CA49DC867E37FE3B02FEE0F", "_encstr_BE8B08B3B4CD963163B2", 0 );
            var_0 setscriptablepartstate( "_encstr_9D19053B41CE0B", "_encstr_9EDF0778AA2789E9F3", 0 );
            var_0 setscriptablepartstate( "_encstr_BD5F0947E22A9FD91EBBF8", "_encstr_9EDF0778AA2789E9F3", 0 );

            if ( !istrue( var_0._id_12744 ) )
            {
                var_0 setscriptablepartstate( "_encstr_BCD50BD161DF40C53701ED29BA", "_encstr_BE8B08B3B4CD963163B2", 0 );
                var_0 setscriptablepartstate( "_encstr_A16A0A8D5AEC34E8CDD77B73", "_encstr_9EDF0778AA2789E9F3", 0 );
            }

            break;
        case 3:
            var_0 setscriptablepartstate( "_encstr_9FEF054BD599BA", "_encstr_BE8B08B3B4CD963163B2", 0 );
            var_0 setscriptablepartstate( "_encstr_8FBA0CA49DC867E37FE3B02FEE0F", "_encstr_BE8B08B3B4CD963163B2", 0 );
            var_0 setscriptablepartstate( "_encstr_9D19053B41CE0B", "_encstr_BE8B08B3B4CD963163B2", 0 );
            var_0 setscriptablepartstate( "_encstr_BD5F0947E22A9FD91EBBF8", "_encstr_BE8B08B3B4CD963163B2", 0 );

            if ( !istrue( var_0._id_12744 ) )
            {
                var_0 setscriptablepartstate( "_encstr_BCD50BD161DF40C53701ED29BA", "_encstr_BE8B08B3B4CD963163B2", 0 );
                var_0 setscriptablepartstate( "_encstr_A16A0A8D5AEC34E8CDD77B73", "_encstr_BE8B08B3B4CD963163B2", 0 );
            }

            break;
    }

    if ( var_2 )
    {
        var_4 = undefined;
        var_5 = undefined;
        var_6 = undefined;

        switch ( var_1 )
        {
            case 0:
                var_4 = "_encstr_9EDF0778AA2789E9F3";
                var_5 = "_encstr_9EDF0778AA2789E9F3";
                var_6 = "_encstr_9EDF0778AA2789E9F3";
                break;
            case 1:
                var_4 = "_encstr_AF5007D88DDEE6AC23";
                var_5 = "_encstr_9EDF0778AA2789E9F3";
                var_6 = "_encstr_9EDF0778AA2789E9F3";
                break;
            case 2:
                var_4 = "_encstr_9EDF0778AA2789E9F3";
                var_5 = "_encstr_AF5007D88DDEE6AC23";
                var_6 = "_encstr_9EDF0778AA2789E9F3";
                break;
            case 3:
                var_4 = "_encstr_9EDF0778AA2789E9F3";
                var_5 = "_encstr_9EDF0778AA2789E9F3";
                var_6 = "_encstr_AF5007D88DDEE6AC23";
                break;
        }

        foreach ( var_8 in var_0.hideintelinstancefromplayer )
            var_8 setscriptablepartstate( "_encstr_A39B05D63DA213", var_4, 0 );

        foreach ( var_8 in var_0.waypoints_creation )
            var_8 setscriptablepartstate( "_encstr_A39B05D63DA213", var_5, 0 );

        foreach ( var_8 in var_0.spawn_lootcrates_on_each_traincar )
            var_8 setscriptablepartstate( "_encstr_A39B05D63DA213", var_6, 0 );
    }
}

all_but_one_player_in_vehicle()
{
    var_0 = getdvarint( "_encstr_87FF1ACD1BE4BE98E4F5431AFA3A39952BF523B7B57D93854696EAE6", 250 );
    var_1 = getdvarint( "_encstr_AFEF1AFA49B07F3A2EAFABA347D5C3BDE056B745208168028BE7B32B", 100 );
    var_2 = getdvarint( "_encstr_98B31E23792E6786B09754579BB10AB7DD13CB69C10F13FB50F54D1FB138D53F", 30 );
    var_3 = var_2 * 2;

    if ( getdvarint( "_encstr_BACF20F8EF12B69D7399730BE16AFFB8576B40484FCC884F9AB1F80C47230DE0D407", 0 ) != 0 )
        var_3 = getdvarint( "_encstr_BACF20F8EF12B69D7399730BE16AFFB8576B40484FCC884F9AB1F80C47230DE0D407", 30 );

    for ( var_4 = 0; var_4 < level.spawn_and_enter_little_bird_mg.size; var_4++ )
    {
        var_5 = level.spawn_and_enter_little_bird_mg[var_4].origin;
        var_6 = spawn( "_encstr_9E6B0FE8274B9DD92BC9D7278591B4D5E6", var_5, 0, var_0, var_1 );
        var_6._id_13DC7 = [];
        var_7 = _encstr_9E7F211898C28383CB8760E558BF27EB18E74BB010797A7D47017210081F958AA85B5F::setupobjective( var_6, "_encstr_9BA4080D39CFFB5AB7C1" );
        var_7._id_13D1A = var_4;
        var_6._id_13D19 = var_7;
        var_7.onuse = ::aitype_counts;
        var_7.onbeginuse = ::all_alive_players;
        var_7.onuseupdate = ::all_alive_players_entities;
        var_7.onenduse = ::all_alive_players_entites;
        var_7._id_128B9 = ::all_but_one_player_downed;
        var_7._id_12079 = ::alertforspawngroupdirection;
        var_7.oncontested = ::alcove_trig;
        var_7.onuncontested = ::alivejuggernauts;
        var_7.forest_barrels = ::airstrikebetweentwopoints;
        var_7.gate_swings_open = 1;
        var_7.id = "_encstr_8FD9082F7548D1BB9A8F";
        var_7.pinobj = 0;
        var_7.lockupdatingicons = 1;
        var_7 scripts\mp\gameobjects::setcapturebehavior( "_encstr_930E073E8FC00DDF69" );
        var_7 scripts\mp\gameobjects::setusetime( var_3 );
        scripts\mp\objidpoolmanager::update_objective_setneutrallabel( var_7.objidnum, "_encstr_A40101" );
        scripts\mp\objidpoolmanager::objective_playermask_hidefromall( var_7.objidnum );
        var_7.flagmodel delete();
        var_7.flagmodel = undefined;
        var_7.outlineent = undefined;
        var_7.visibilitymanuallycontrolled = 1;
        var_7 _encstr_B47322A2CE6512F8030826172850A7DA0355EB582FE30B7F29E8EF37685099626DFCB256::calloutmarkerping_watchwhenobjectivedeleted( 0 );
        level.spawn_and_enter_little_bird_mg[var_4]._id_13D19 = var_7;
        level.spawn_and_enter_little_bird_mg[var_4].weapongroupdata = [];
        level.spawn_and_enter_little_bird_mg[var_4].weapongetflinchtype = [];
        level.spawn_and_enter_little_bird_mg[var_4].trial_mount_nag = [];
        level.spawn_and_enter_little_bird_mg[var_4].trial_missionscript_init_funcs = [];
    }
}

airfield_safehouse_edit_loadout( var_0 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self notify( "_encstr_AAEF1AB1DBB7477DB1B1592CC9EB91CAB1B05EAFCA1E47569BC8AC32" );
    self endon( "_encstr_AAEF1AB1DBB7477DB1B1592CC9EB91CAB1B05EAFCA1E47569BC8AC32" );
    var_1 = getdvarint( "_encstr_B2E41A2B3FAB8080053101AB9FCA40A730C6B8BD3FAE01A899604FA8", 30 );
    wait( var_1 );
    var_2 = getdvarint( "_encstr_AF6D1B4B609DA1FB23C80830E0C987759F08C2A2E8356963B94D01258E", 260 );

    if ( var_2 <= 0 )
        return;

    var_3 = 520;
    var_4 = scripts\mp\utility\player::getplayersinradius( var_0._id_13D19.trigger.origin, var_3 );

    if ( var_4.size > 0 )
    {
        thread airfield_safehouse_edit_loadout( var_0 );
        return;
    }

    var_5 = canceljoins( undefined, undefined, var_0.origin, var_2 );

    if ( isdefined( var_5 ) )
    {
        foreach ( var_7 in var_5 )
        {
            if ( scripts\engine\utility::string_starts_with( var_7.type, "_encstr_B3401CF9BA1E28125FD08F66C91043D0AEF9EAC949F3084109F7284B7D69" ) )
                continue;

            if ( scripts\engine\utility::string_starts_with( var_7.type, "_encstr_A4D90E79134F1950FD54A7D76926B055" ) )
                continue;

            if ( var_7 getscriptableisreserved() && !isdefined( var_7.embassy_main ) )
                continue;

            _encstr_823124376CE42DC11DCD5EB6E0CB3BB0ADAC3A2FE056CDBC314EAF83A536DAAB079BE2D9B9B1::_id_11A21( var_7 );
        }
    }
}

airstrikebetweentwopoints()
{
    var_0 = getdvarint( "_encstr_A62024835EA3977E0521524A397175177EB51D0BE76A4F82CB508A31B85B6DE7D3B068818951", 13 );
    var_1 = getdvarint( "_encstr_BDEB248B3F68298B3EE6929ACE1D871DA9A915E3536861036F7B5AD11166CF1380778069F178", 26 );
    var_2 = self;
    var_3 = var_2.curprogress > 0.5 * var_2.usetime;
    return scripts\engine\utility::ter_op( var_3, var_1, var_0 );
}

alcove_trig()
{
    var_0 = self;
    var_1 = "_encstr_873B13BB58F20EBDD273E8F5367B37E82BB9472BC8";
    var_0 scripts\mp\gameobjects::setobjectivestatusicons( var_1 );
    scripts\mp\objidpoolmanager::objective_set_progress_team( var_0.objidnum, undefined );
    all_modes( var_0 );
    var_2 = "_encstr_9534223D58FF68428D88477E6D096746DA957DA031758730BBDF9809C3EB038A18C801FA";
    all_alive_players_near_exfil( var_0, var_2 );
}

all_alive_players_near_exfil( var_0, var_1 )
{
    if ( all_obit_models( var_0 ) )
    {
        var_2 = airstrikecount( var_0 );

        foreach ( var_4 in var_2 )
            var_4 playsoundtoplayer( var_1, var_4, var_4 );
    }
}

alivejuggernauts( var_0 )
{
    var_1 = self;
    var_2 = level.spawn_and_enter_little_bird_mg[var_1._id_13D1A];
    var_2.trial_mount_nag = [];
    _encstr_BE892FD6B64BBB6B14972A208317C1E3C25FCD5BCA925778EABBA178AF7D59312B82CDF0A6EA31FAD337C848C3C6517752::onarmorboxusedbyplayer( var_0, 0 );
    all_modes( var_1 );
}

aitype_counts( var_0 )
{
    var_1 = self;
    var_2 = level.spawn_and_enter_little_bird_mg[var_1._id_13D1A];
    var_2.cheese = 1;
    var_1.claimteam = var_0.team;
    var_1.curprogress = var_1.usetime;
    alertforspawngroupdirection( 1 );
}

all_but_one_player_downed( var_0 )
{
    var_1 = self;
    var_2 = level.spawn_and_enter_little_bird_mg[var_1._id_13D1A];

    if ( istrue( var_2.stopdragonsbreathburning ) )
        return 0;

    var_3 = scripts\engine\utility::array_contains( var_2.weapongetflinchtype, var_1.claimteam );
    var_4 = getdvarint( "_encstr_ABE2206E1B93FA2627FA1A1AF585C6B1B7DD4AAC072B85A31ABDB6E063561DA57BB9", 0 ) == 1;

    if ( var_3 && !var_4 )
    {
        var_1.claimplayer setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 13 );
        var_5 = 0;
        return var_5;
    }

    var_6 = istrue( var_1.playerkilled_washitbyvehicle );
    var_7 = !scripts\engine\utility::array_contains( var_2.trial_mount_nag, var_1.claimteam );
    var_8 = var_6 && var_0 && var_7;
    var_5 = !var_8;
    return var_5;
}

all_alive_players_entities( var_0, var_1, var_2, var_3 )
{
    var_4 = self;
    all_modes( var_4 );
}

alertforspawngroupdirection( var_0 )
{
    var_1 = self;
    var_2 = level.spawn_and_enter_little_bird_mg[var_1._id_13D1A];
    var_3 = var_1.curprogress / var_1.usetime;

    if ( !isdefined( var_2._id_13D1B ) )
        return;

    if ( !var_0 )
        var_1.playerkilled_washitbyvehicle = 1;

    var_4 = var_0 && istrue( var_1.playerkilled_washitbyvehicle );

    if ( var_4 )
        var_1.playerkilled_washitbyvehicle = 0;

    if ( !scripts\engine\utility::array_contains( var_2.trial_mount_nag, var_1.claimteam ) )
        var_2.trial_mount_nag = scripts\engine\utility::array_add( var_2.trial_mount_nag, var_1.claimteam );

    var_5 = scripts\engine\utility::ter_op( var_0 && !istrue( var_2.stopdragonsbreathburning ), "_encstr_8F070350FB", "_encstr_9EDF0778AA2789E9F3" );

    if ( var_2 getscriptablehaspart( "_encstr_9B1409332F9A265220B073" ) )
        var_2 setscriptablepartstate( "_encstr_9B1409332F9A265220B073", var_5, 0 );

    if ( !var_0 && istrue( var_2.cheese ) )
    {
        var_2.cheese = undefined;

        if ( var_2 getscriptablehaspart( "_encstr_9C5F0D339C4141D770E8B71F980884" ) )
            var_2 setscriptablepartstate( "_encstr_9C5F0D339C4141D770E8B71F980884", "_encstr_A1A7087891C61B11B313", 0 );
    }

    var_6 = var_2._id_13D1B;

    if ( var_3 == 1 )
    {
        if ( var_6 != 3 )
        {
            var_7 = "_encstr_B7931E4B2978F2A2A02E62EE60A3C7BBCFADB3D7FF1BEA64B8519EF0FB815147";
            all_alive_players_near_exfil( var_1, var_7 );
            var_8 = 265;
            var_9 = scripts\mp\utility\player::getplayersinradius( var_2._id_13D19.trigger.origin, var_8 );

            foreach ( var_11 in var_9 )
            {
                if ( var_11.team == var_1.claimteam )
                {
                    _encstr_A83527375FF36358943A0858E22728AFFAAFA1ABAB2A36DADA520ED34B55D05D71772933B3C6F4F0F3::displayplayersplash( var_11, "_encstr_8C611DC4E47D3AE4562BEB46598DDE27588E5A7BE6D7B1F6D6071B2BE85623" );
                    var_11 scripts\cp\vehicles\vehicle_compass_cp::_id_120A4( "_encstr_A2D612B3C1A04B7A2851213608B0A00205410F1B" );
                    var_11 scripts\cp\vehicles\vehicle_compass_cp::_id_120A4( "_encstr_B8A714D086BE275A19198D59BE8D7B5BE0D8AC1D56C8" );
                }
            }

            all_end_checkpoints_activated( var_1 );

            if ( var_2 getscriptablehaspart( "_encstr_9C5F0D339C4141D770E8B71F980884" ) )
                var_2 setscriptablepartstate( "_encstr_9C5F0D339C4141D770E8B71F980884", "_encstr_827C0BAB39D0035B4883B3EA4B", 0 );

            var_13 = scripts\engine\utility::array_contains( var_2.weapongetflinchtype, var_1.claimteam );
            var_14 = var_1.claimteam != "_encstr_AABA05236DC831" && !var_13;
            var_15 = getdvarfloat( "_encstr_A8F7270F8B7A19EE1321C0C8492310F059ECBB8D3525D12DA3CB79115143DDE06F792167DCCF10FFCF", 1 );
            level thread airstrike_canbeused( var_2, 3, var_14, var_15 );

            if ( !var_13 )
                var_2.weapongetflinchtype = scripts\engine\utility::array_add( var_2.weapongetflinchtype, var_1.claimteam );

            if ( !istrue( var_2._id_12744 ) )
                airlock_slot( var_1._id_13D1A );
        }
    }
    else if ( var_3 > 0.5 )
    {
        if ( var_6 != 2 )
        {
            if ( var_0 )
            {
                all_end_checkpoints_activated( var_1 );

                if ( var_2 getscriptablehaspart( "_encstr_9C5F0D339C4141D770E8B71F980884" ) )
                    var_2 setscriptablepartstate( "_encstr_9C5F0D339C4141D770E8B71F980884", "_encstr_B1A012B907B0EEDCFA32ACB1B7C90BE8A5F6DCCD", 0 );
            }

            var_16 = scripts\engine\utility::array_contains( var_2.weapongroupdata, var_1.claimteam );
            var_14 = var_1.claimteam != "_encstr_AABA05236DC831" && !var_16;
            var_15 = getdvarfloat( "_encstr_88542507A6BEE1B633DE60286089B85AA778186BD5FDC99B449D1FA29ADB99477D5E399D597663", 1 );
            level thread airstrike_canbeused( var_2, 2, var_14, var_15 );

            if ( !var_16 )
                var_2.weapongroupdata = scripts\engine\utility::array_add( var_2.weapongroupdata, var_1.claimteam );

            var_17 = "_encstr_A8CF182A62C0FBEA103FFBF145A379777718A3E2EE2397E9DA09";
            all_alive_players_near_exfil( var_1, var_17 );
        }
    }
    else if ( var_3 <= 0.01 && !var_0 )
    {
        var_1.curprogress = 0;
        var_1.playerkilled_washitbyvehicle = 0;
        var_2.trial_mount_nag = [];

        if ( var_2 getscriptablehaspart( "_encstr_9B1409332F9A265220B073" ) )
            var_2 setscriptablepartstate( "_encstr_9B1409332F9A265220B073", "_encstr_9EDF0778AA2789E9F3", 0 );

        var_2 thread airfield_safehouse_edit_loadout( var_2 );
    }
    else if ( var_3 < 0.5 && !var_0 )
    {
        if ( var_6 != 1 )
        {
            level thread airstrike_canbeused( var_2, 1, 0, 0 );
            var_2.trial_mount_nag = [];
        }
    }

    var_18 = var_2._id_13A12;

    if ( var_3 > 0.5 && var_0 )
    {
        if ( var_18 != 3 )
            airstrike_addactivestrike( var_2, 3 );
    }
    else if ( var_3 < 0.5 && var_0 || var_3 > 0.5 && !var_0 )
    {
        if ( var_18 != 2 )
            airstrike_addactivestrike( var_2, 2 );
    }
    else if ( var_3 < 0.5 )
    {
        if ( var_18 != 1 )
            airstrike_addactivestrike( var_2, 1 );
    }
}

all_end_checkpoints_activated( var_0 )
{
    if ( isdefined( var_0._id_11E61 ) )
    {
        if ( gettime() < var_0._id_11E61 )
            return;
    }

    var_1 = var_0.trigger.origin;
    level thread _encstr_A83527375FF36358943A0858E22728AFFAAFA1ABAB2A36DADA520ED34B55D05D71772933B3C6F4F0F3::_id_140B1( var_1, "_encstr_9318045AFDDD", 3 );
    var_2 = 15000;
    var_0._id_11E61 = gettime() + var_2;
}

all_obit_models( var_0 )
{
    if ( isdefined( var_0.isloadinggulag ) )
    {
        if ( gettime() < var_0.isloadinggulag )
            return 0;
    }

    var_1 = 5000;
    var_0.isloadinggulag = gettime() + var_1;
    return 1;
}

all_alive_players( var_0 )
{
    var_1 = self;
    var_2 = level.spawn_and_enter_little_bird_mg[var_1._id_13D1A];
    var_2 notify( "_encstr_AAEF1AB1DBB7477DB1B1592CC9EB91CAB1B05EAFCA1E47569BC8AC32" );

    if ( !scripts\engine\utility::array_contains( var_1.trigger._id_13DC7, var_0 ) )
        var_1.trigger._id_13DC7 = scripts\engine\utility::array_add( var_1.trigger._id_13DC7, var_0 );

    var_1 thread scripts\mp\gameobjects::useobjectdecay( var_0.team );
    var_3 = scripts\engine\utility::array_contains( var_2.weapongetflinchtype, var_0.team );
    var_4 = scripts\engine\utility::array_contains( var_2.trial_mount_nag, var_0.team );

    if ( !var_3 && var_4 && istrue( var_1.playerkilled_washitbyvehicle ) )
        var_1.playerkilled_washitbyvehicle = 0;

    var_5 = var_1.claimteam == "_encstr_AABA05236DC831" || istrue( var_1.stalemate );

    if ( !istrue( var_2.stopdragonsbreathburning ) && !var_3 && !var_5 )
        all_end_checkpoints_activated( var_1 );

    if ( !var_4 && !var_3 )
    {
        var_6 = "_encstr_BA01232083D1CD43A747A6975EEBAEB7068AD88069B41F584F64A79317EF7053EFF3099A37";
        all_alive_players_near_exfil( var_1, var_6 );
    }

    if ( !isdefined( var_1._id_11F63 ) || !var_1._id_11F63 )
    {
        var_1._id_11F63 = 1;
        var_7 = scripts\mp\utility\teams::getfriendlyplayers( var_0.team, 0 );

        foreach ( var_9 in var_7 )
            var_9 notify( "_encstr_A1D9274BEB48358F8DB3925A1BEAFFEA8343CED77F68BE3332C8DA02043313A551137D4BB131467FD0" );
    }

    if ( !istrue( var_2.stopdragonsbreathburning ) && !scripts\engine\utility::array_contains( var_2.trial_missionscript_init_funcs, var_0 ) )
    {
        var_2.trial_missionscript_init_funcs = scripts\engine\utility::array_add( var_2.trial_missionscript_init_funcs, var_0 );
        var_0 scripts\cp\vehicles\vehicle_compass_cp::_id_120A4( "_encstr_8A820F36F691B62CB9AF2D733ACA1BF51B" );
    }

    all_modes( var_1 );
}

all_alive_players_entites( var_0, var_1, var_2 )
{
    var_3 = self;
    _encstr_9E7F211898C28383CB8760E558BF27EB18E74BB010797A7D47017210081F958AA85B5F::dompoint_onuseend( var_0, var_1, var_2 );

    if ( var_2 )
        aitype_counts( var_1 );

    all_modes( var_3 );
}

airstrikecount( var_0 )
{
    var_1 = level.spawn_and_enter_little_bird_mg[var_0._id_13D1A];
    var_2 = getdvarint( "_encstr_87FF1ACD1BE4BE98E4F5431AFA3A39952BF523B7B57D93854696EAE6", 250 );
    var_3 = var_2 + 15;
    var_4 = var_3 * var_3;
    var_5 = [];

    for ( var_6 = var_0.trigger._id_13DC7.size - 1; var_6 >= 0; var_6-- )
    {
        var_7 = var_0.trigger._id_13DC7[var_6];
        var_8 = distance2dsquared( var_7.origin, var_0.trigger.origin );
        var_9 = var_8 > var_4;
        var_10 = scripts\engine\utility::array_contains( var_1.weapongetflinchtype, var_7.team );

        if ( !var_9 && !var_10 )
            var_5[var_5.size] = var_7;
    }

    return var_5;
}

airstrikeid( var_0 )
{
    if ( !isdefined( level.br_circle ) || !isdefined( level.br_circle.dangercircleent ) )
        return 0;

    var_1 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getdangercircleorigin();
    var_2 = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::getdangercircleradius();
    return distance2dsquared( var_1, var_0 ) > var_2 * var_2;
}

all_gas_trap_structs( var_0, var_1 )
{
    var_2 = [];
    var_3 = 0;

    foreach ( var_5 in level.teamnamelist )
    {
        if ( var_0.touchlist[var_5].size > 0 )
        {
            var_3++;
            var_6 = var_0.touchlist[var_5];
            var_7 = getarraykeys( var_6 );

            for ( var_8 = 0; var_8 < var_7.size; var_8++ )
            {
                var_9 = var_6[var_7[var_8]].player;
                var_2[var_2.size] = var_9;
            }
        }
    }

    var_11 = [];

    foreach ( var_9 in var_1 )
    {
        if ( !scripts\engine\utility::array_contains( var_2, var_9 ) )
            var_11[var_11.size] = var_9;
    }

    return [ var_2, var_11, var_3 ];
}

all_modes( var_0 )
{
    var_1 = level.spawn_and_enter_little_bird_mg[var_0._id_13D1A];

    if ( istrue( var_1.stopdragonsbreathburning ) )
        return;

    var_1.stopdragonsbreathburning = airstrikeid( var_0.trigger.origin );

    if ( istrue( var_1.stopdragonsbreathburning ) )
    {
        airstrike_addactivestrike( var_1, 0 );
        level thread airstrike_canbeused( var_1, 1, 0, 0 );
    }

    var_2 = var_0.trigger._id_13DC7;
    [var_4, var_5, var_6] = all_gas_trap_structs( var_0, var_2 );
    var_0.trigger._id_13DC7 = var_4;

    foreach ( var_8 in var_5 )
    {
        var_8 setclientomnvar( "_encstr_87B915D748EE7B5AD7AD827C18F7B1201310E743B0C3B3", 0 );
        var_8 setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 0 );
    }

    var_10 = var_0.curprogress / var_0.usetime;

    foreach ( var_12 in var_4 )
    {
        var_13 = scripts\engine\utility::array_contains( var_1.weapongetflinchtype, var_12.team );

        if ( var_1.stopdragonsbreathburning )
        {
            var_12 setclientomnvar( "_encstr_87B915D748EE7B5AD7AD827C18F7B1201310E743B0C3B3", 0 );
            var_12 setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 0 );
            continue;
        }

        if ( var_13 )
        {
            var_12 setclientomnvar( "_encstr_87B915D748EE7B5AD7AD827C18F7B1201310E743B0C3B3", 1 );
            var_12 setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 13 );
            continue;
        }

        var_12 setclientomnvar( "_encstr_87B915D748EE7B5AD7AD827C18F7B1201310E743B0C3B3", var_10 );

        if ( var_6 > 1 || var_0.claimteam == "_encstr_AABA05236DC831" || var_0.claimteam == "_encstr_9BA4080D39CFFB5AB7C1" || istrue( var_0.stalemate ) )
        {
            var_12 setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 20 );
            continue;
        }

        if ( var_0.claimteam == var_12.team )
        {
            var_12 setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 18 );
            continue;
        }

        var_12 setclientomnvar( "_encstr_82370C57A5EBB92B1B57C9B4DC9D", 20 );
    }

    if ( var_1.stopdragonsbreathburning )
        var_1 setscriptablepartstate( "_encstr_B9E50B23DEDA7D364BC9C6C659", "_encstr_9EDF0778AA2789E9F3", 0 );
    else if ( var_6 > 1 )
        var_1 setscriptablepartstate( "_encstr_B9E50B23DEDA7D364BC9C6C659", "_encstr_9E7407D077A04928BF", 0 );
    else if ( var_6 == 1 )
    {
        var_1 setotherent( var_0.claimplayer );
        var_1 setscriptablepartstate( "_encstr_B9E50B23DEDA7D364BC9C6C659", "_encstr_8793097D0BEB0D39BA9759", 0 );
    }
    else
        var_1 setscriptablepartstate( "_encstr_B9E50B23DEDA7D364BC9C6C659", "_encstr_948806DDD04BE895", 0 );
}

airlock_doors()
{
    var_0 = [];
    var_0[var_0.size] = [ 26, 36, 2, 0, 18, 19, 36, 0 ];
    var_0[var_0.size] = [ 27, 36, 18, 19, 14, 13, 4, 36, 14, 5 ];
    var_0[var_0.size] = [ 28, 36, 8, 2, 4, 36, 0, 13, 3, 36, 18, 13, 14, 22 ];
    var_0[var_0.size] = [ 29, 36, 8, 13, 19, 14, 36, 12, 14, 11, 19, 4, 13 ];
    var_0[var_0.size] = [ 30, 36, 3, 4, 15, 19, 7, 18, 36, 5, 0, 17 ];
    var_0[var_0.size] = [ 31, 36, 1, 4, 11, 14, 22, 36, 19, 7, 4, 13 ];
    var_0[var_0.size] = [ 32, 36, 8, 11, 4, 36, 15, 17, 4, 24 ];
    var_0[var_0.size] = [ 33, 36, 14, 5, 36, 1, 11, 14, 14, 3 ];
    var_0[var_0.size] = [ 34, 36, 17, 14, 3, 36, 4, 24, 4, 18 ];
    var_0[var_0.size] = [ 26, 35, 36, 11, 0, 24, 36, 3, 14, 22, 13 ];
    var_0[var_0.size] = [ 26, 26, 36, 24, 14, 20, 17, 36, 0, 17, 12, 18 ];
    var_0[var_0.size] = [ 26, 27, 36, 19, 14, 36, 2, 11, 0, 8, 12 ];
    var_0[var_0.size] = [ 26, 28, 36, 24, 14, 20, 17, 36, 15, 17, 8, 25, 4 ];
    return var_0;
}

airlock_slot( var_0 )
{
    if ( getdvarint( "_encstr_AAA618903A92AF59D37F131B67F7A0BDBA2279F8F26A2FF16F6D", 0 ) == 0 )
        return;

    var_1 = level.spawn_and_enter_little_bird_mg[var_0];
    var_2 = airlock_doors();
    var_3 = randomint( var_2.size );
    var_4 = getdvarint( "_encstr_B85A21E68D9C7D984EAF341ABEED9D95E4C95A2395FA5B56E6E60BCE59EB4BDC8C2BC3", -1 );

    if ( var_4 != -1 )
        var_3 = var_4;

    level thread airlock_show_front_doors( var_2[var_3], var_1, ::airlock_positions, ::airlock_pivot );
}

airlock_callbuttons()
{
    var_0 = [];
    var_0[0] = "_encstr_8817043AC1E9";
    var_0[1] = "_encstr_A11808A5E99AC806CF85";
    var_0[2] = "_encstr_8C18080EDA85DE66C9D0";
    var_0[3] = "_encstr_82130625691A4886";
    var_0[4] = "_encstr_B74C028B";
    var_0[5] = "_encstr_9C0E08C5807104B401B8";
    var_0[6] = "_encstr_931306019E46D148";
    var_0[7] = "_encstr_8B0E08668618C88A5AE8";
    var_0[8] = "_encstr_A31704CABE35";
    var_0[9] = "_encstr_B339082A9230B84EE131";
    var_0[10] = "_encstr_B11306E06E5EF932";
    var_0[11] = "_encstr_823908E280A5107101E2";
    var_0[12] = "_encstr_B31704556131";
    var_0[13] = "_encstr_A917040D6152";
    var_0[14] = "_encstr_B413065A80A5024B";
    var_0[15] = "_encstr_AF39085C04B4806904C5";
    var_0[16] = "_encstr_9CEC08653F6B3616392A";
    var_0[17] = "_encstr_937D06F58A2EB1AE";
    var_0[18] = "_encstr_AB7D0608209A2175";
    var_0[19] = "_encstr_804C0246";
    var_0[20] = "_encstr_AD7D06178071014B";
    var_0[21] = "_encstr_AF0E08D8C62E89C5E00E";
    var_0[22] = "_encstr_BA7D067DE7A3FE2D";
    var_0[23] = "_encstr_B91808B5D9EA961AB708";
    var_0[24] = "_encstr_9E1808FDA7E5BEEDC1A2";
    var_0[25] = "_encstr_98EC0898F6B90AF6F618";
    var_0[26] = "_encstr_AD0E0A5667D0F225290A5E86";
    var_0[27] = "_encstr_BA4C0AE208E201D2025A0296";
    var_0[28] = "_encstr_97B60A5AE220C80EB161F64D";
    var_0[29] = "_encstr_8FB60AAE825E0185787A2EC9";
    var_0[30] = "_encstr_9FB60A02F9A0B69EAA60961D";
    var_0[31] = "_encstr_899F0AB0E27EB66DD795FE6A";
    var_0[32] = "_encstr_BC8D0ABDE7A3FE2E017A92A2";
    var_0[33] = "_encstr_B20D0A9BE0F5BA21324EA158";
    var_0[34] = "_encstr_970D0A3649FB2249F13A66ED";
    var_0[35] = "_encstr_B30D0AA5A6168FF29EBDC9DB";
    var_0[36] = "_encstr_B64C02F0";
    return var_0;
}

airlock_show_front_doors( var_0, var_1, var_2, var_3 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    var_1 notify( "_encstr_8B370D9C5A9132D856FACD3A0BC98E" );
    var_1 endon( "_encstr_8B370D9C5A9132D856FACD3A0BC98E" );
    var_1._id_12744 = 1;
    var_4 = 0.5;
    var_5 = airlock_callbuttons();

    foreach ( var_7 in var_0 )
    {
        if ( var_5[var_7] == "_encstr_B64C02F0" )
        {
            [[ var_3 ]]( var_1 );
            wait( var_4 * 7 );
            continue;
        }

        var_8 = var_5[var_7];
        var_9 = strtok( var_8, "_encstr_884C02C6" );

        foreach ( var_11 in var_9 )
        {
            if ( var_11 == "_encstr_B74C028B" )
            {
                [[ var_2 ]]( var_1 );
                wait( var_4 );
                [[ var_3 ]]( var_1 );
            }
            else if ( var_11 == "_encstr_804C0246" )
            {
                [[ var_2 ]]( var_1 );
                wait( var_4 * 3 );
                [[ var_3 ]]( var_1 );
            }

            [[ var_3 ]]( var_1 );
            wait( var_4 );
        }

        [[ var_3 ]]( var_1 );
        wait( var_4 * 3 );
    }

    [[ var_3 ]]( var_1 );
    wait( var_4 * 7 );
    var_1._id_12744 = 0;
    level thread airstrike_canbeused( var_1, var_1._id_13D1B, 0, 0 );
}

airlock_positions( var_0 )
{
    var_0 setscriptablepartstate( "_encstr_BCD50BD161DF40C53701ED29BA", "_encstr_9EDF0778AA2789E9F3", 0 );
    var_0 setscriptablepartstate( "_encstr_A16A0A8D5AEC34E8CDD77B73", "_encstr_BE8B08B3B4CD963163B2", 0 );
}

airlock_pivot( var_0 )
{
    var_0 setscriptablepartstate( "_encstr_BCD50BD161DF40C53701ED29BA", "_encstr_BE8B08B3B4CD963163B2", 0 );
    var_0 setscriptablepartstate( "_encstr_A16A0A8D5AEC34E8CDD77B73", "_encstr_9EDF0778AA2789E9F3", 0 );
}

airlock_show_doors( var_0 )
{
    var_1 = ( 11188, 13178, 7261 );
    var_2 = distance( var_1, var_0.origin );
    var_3 = 200;
    var_4 = var_2 <= var_3;

    if ( var_4 )
        var_0._id_13442 = 1;
}

airlock_show_back_doors( var_0 )
{
    if ( istrue( var_0._id_13442 ) )
    {
        var_1 = istrue( var_0.play_found_leads_counting_building_two );

        if ( var_0 airlock_show_room_doors() && !var_1 )
        {
            var_0 scripts\cp\vehicles\vehicle_compass_cp::_id_120A4( "_encstr_B8A714D086BE275A19198D59BE8D7B5BE0D8AC1D56C8" );
            var_0.play_found_leads_counting_building_two = 1;
            airlock_front_blocker( var_0 );
        }
    }
}

airlock_front_blocker( var_0 )
{
    var_1 = "_encstr_89071D40E3B1AD23C727C637FE4B4E57E62A78E009D2CB59E7054E36F706DB";
    var_0 playsoundtoplayer( var_1, var_0, var_0 );
    var_0 playsoundtoplayer( "_encstr_8B401BFAAE7E5F9251884BF291BB0C87539B4F7E5081679D51F8D22B78", var_0 );
    var_0 thread scripts\mp\hud_message::showsplash( "_encstr_88FA168B7B9971D8770951B229F7A78D5F19C7377D1B67E2" );
    _encstr_BC7029E78F23B38864CAF888321778FF8AFF917B5BFA06AA8A62FE015D14812142433BAFA742CEEAA73A61::ai_ascender_animloop( var_0.origin, var_0.angles );
    _encstr_890626F852FABB63A30BE831E0264973E59A7820FB57C7D0C312D83FC647500B0BA248E8766F3F91::destroy_vehicle_on_pilot_death( var_0 );
}

airlock_show_room_doors()
{
    if ( !isdefined( self ) || !isplayer( self ) )
        return 0;

    var_0 = self;
    return istrue( var_0.unset_relic_punchbullets );
}

airdrop_playdeploydialog( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !isdefined( var_0 ) || !isdefined( var_3 ) )
        return;

    var_5 = getcompleteweaponname( "_encstr_970B08473F92B171FD8A" );

    if ( var_3 hasweapon( var_5 ) && var_3 getammocount( var_5 ) > 0 )
        return;

    var_0 setscriptablepartstate( "_encstr_B7BE0C2B3028C75A5918661D7F01", "_encstr_9EDF0778AA2789E9F3" );
    var_3 thread _encstr_823124376CE42DC11DCD5EB6E0CB3BB0ADAC3A2FE056CDBC314EAF83A536DAAB079BE2D9B9B1::playerplaypickupanim();
    var_3 scripts\mp\equipment::giveequipment( "_encstr_98E40B56B8BA96E0D78D7B58D8", "_encstr_987F080E394BDAC2E45E" );
    var_3 playlocalsound( "_encstr_94360F8D33A1F280E667DF1F9226CF3FD7" );
}

airstrike_movewithplane( var_0, var_1, var_2, var_3, var_4 )
{
    if ( !isdefined( var_0 ) || !isdefined( var_3 ) )
        return;

    var_5 = getcompleteweaponname( "_encstr_98410C37CDDEEE4C2C1BD8AFB61C" );

    if ( var_3 hasweapon( var_5 ) && var_3 getammocount( var_5 ) > 0 )
        return;

    var_0 setscriptablepartstate( "_encstr_B94D1005B2A5C0B76359CB5062574E787D34", "_encstr_9EDF0778AA2789E9F3" );
    var_3 thread _encstr_823124376CE42DC11DCD5EB6E0CB3BB0ADAC3A2FE056CDBC314EAF83A536DAAB079BE2D9B9B1::playerplaypickupanim();
    var_3 scripts\mp\equipment::giveequipment( "_encstr_B97B0FD5994D81171F5B66477F3AA7B2F8", "_encstr_987F080E394BDAC2E45E" );
    var_3 playlocalsound( "_encstr_94360F8D33A1F280E667DF1F9226CF3FD7" );
    airlock_show_doors( var_3 );
}

airstrike_watchgameend()
{
    var_0 = self;
    var_0 scripts\engine\utility::waittill_notify_or_timeout( "_encstr_8AE90E7D08B8538A21DB77CF1155D2B3", 4 );
    wait 2;

    if ( isdefined( var_0 ) )
        var_0 delete();
}

airstrike_watchownerdisown( var_0, var_1, var_2 )
{
    if ( var_0 == "_encstr_970B08473F92B171FD8A" )
    {
        var_2 playlocalsound( "_encstr_AA8D1CBE1279472BECFF4891AB372197C13A21B7A8B23556C127F868C744" );
        airdrop_crushchicken( var_2 );
    }
    else if ( var_0 == "_encstr_98410C37CDDEEE4C2C1BD8AFB61C" )
        playfxontag( level._id_13443["_encstr_AAE007D90BB9A5E61A"], var_2, "_encstr_87DA078B11C012A35F" );
}

airdrop_crushchicken( var_0 )
{
    var_0 thread scripts\mp\equipment\gas_grenade::gas_applycough( var_0, 1 );
    playfxontagforclients( level.helidrivableenablesiteonflyaway["_encstr_B62907C3A61007BD50"], var_0, "_encstr_A93008E0529FF7E1B73D", var_0 );
    playfxontag( level.helidrivableenablesiteonflyaway["_encstr_AAE007D90BB9A5E61A"], var_0, "_encstr_87DA078B11C012A35F" );

    if ( isdefined( level.playerentercombatareamessage ) )
        var_0 [[ level.playerentercombatareamessage ]]();
}

airlock_button_l()
{
    var_0 = scripts\cp_mp\utility\game_utility::tutorialzoneenter();
    var_1 = getdvarint( "_encstr_A92819DC36E4D7C493FACC33AF87B50BCDAF268DEA591C274BB98E", 1 ) == 0;
    return !var_0 && !var_1;
}

airlock_button_think()
{
    var_0 = [];
    var_0[var_0.size] = "_encstr_8C8F23AE7B505FDA1D9FC787CBC7028621A3257913420933FBFF8FC73760BBC579C95A7C69";
    var_0[var_0.size] = "_encstr_87C822A89BA51F281B8F6C6D893310D5C11340B9132899607FDDF65E65AF18EF75DA90E0";
    var_0[var_0.size] = "_encstr_B61B214C39C6EDB7A3F5EE2B2C1CF673EB3786F5D1729BAC6BB40B57A3F67D63AC9DCA";
    var_0[var_0.size] = "_encstr_888321AEAE923837C0369C25773FF0C547D0FDFFD341811FE87F2660908921CADA5020";
    var_0[var_0.size] = "_encstr_93881E9A1D9825BF3DE6634A091787DDA9871DDF796A2E1FE69B4BD173E7BBD7";
    var_0[var_0.size] = "_encstr_B39F21E6465972E703694737A0BBAF2A67576AD12D5B5A310BD80B0F5071A742D1FBB6";
    var_0[var_0.size] = "_encstr_89952026391BBDED47EBEE2B85387BB9AFB039AF163796AC27392C13C8BE8D56EC59";
    return var_0[randomint( var_0.size )];
}

airlock_button_r( var_0, var_1 )
{
    var_2 = [];
    var_3 = 0;
    var_4 = 0;

    if ( var_0.type == "_encstr_AA2E2272233864D21DB4879EB82F771273A94068218F62DF175F06E007D03B8FF059FFD3" )
    {
        var_5 = 15;
        var_4 = getdvarint( "_encstr_B49E23234F22B118B3DFEA03A80F9DE87A4096587BE3FB78C271625808E31767A1E226D7B8", var_5 );
        var_6 = 5;
        var_3 = getdvarint( "_encstr_A93F233A560D1992BB01A3ABE97147E29BF8C5B9CE5392D0611977AF20C83F4A49074D2EA5", var_6 );
        var_7 = 5;
        var_2 = verifybunkercode( "_encstr_A3AB1A665937E85AB3B2EB995993D9F6E4AF4C16DCCAFAB19CB04795", var_0._id_11A25 );
    }
    else if ( var_0.type == "_encstr_9540253139D7C6B7F61DFAB036BBB05EDCD76E0EB0DD9B7DB10B8DA159F51BCAECB2E619B0C9F2" )
    {
        var_8 = 15;
        var_4 = getdvarint( "_encstr_AF9626CDC64EAF139CBE0D86AFB12BECCAE632C227F2FAC685368695AF6EB9B7BBAFC61A16B96C95", var_8 );
        var_9 = 15;
        var_3 = getdvarint( "_encstr_81D226070FFE31A2285EB4BC76F0ED0ADDBDC3C7D5A3F99BE8A1ACC76E703F222147571B5B406255", var_9 );
        var_7 = 5;
        var_2 = verifybunkercode( "_encstr_9E911A2F050F1C6B530109A8B26356CF6AE148FB7A85812FABD71B17", var_0._id_11A25 );
    }
    else if ( var_0.type == "_encstr_BAF923C44EFA1BEDDEA3FA58C6770BCB9BAFCDC185EE73AFC62C36D0B27DA17BD8B4C885F2" )
    {
        var_10 = 10;
        var_4 = getdvarint( "_encstr_8A77249B3639BE26C9FA86A1FA34B7C64B8C0BE5F5C62C6C4356BEDC9BBDBBFA6C0D859B8DCA", var_10 );
        var_11 = 30;
        var_3 = getdvarint( "_encstr_A16424E636E4BE2627AF4334AF86DE8D4B8CB0BC7DD8B0D81A59EBC6B70B367DC68685DCD82B", var_11 );
        var_7 = 5;
        var_2 = verifybunkercode( "_encstr_A2F41B55AF531BE00318E12487AAAB7B137160B15463EF69D3D0B95315", var_0._id_11A25 );
    }
    else
    {

    }

    var_1 scripts\cp\vehicles\vehicle_compass_cp::_id_120A4( "_encstr_B1820FEB57A8D5172E76324A3B0D7B014A" );
    var_12 = randomint( 100 );
    var_13 = var_12 <= var_3;
    var_14 = var_12 > var_3 && var_12 <= var_3 + var_4;

    if ( !isdefined( var_1._id_136CA ) )
        var_1._id_136CA = [];

    var_15 = !scripts\engine\utility::array_contains( var_1._id_136CA, var_0.spawn_maint_wave );
    var_16 = 15;
    var_17 = getdvarint( "_encstr_B49E23234F22B118B3DFEA03A8199DC83A21994B47E5F490C2BA22DB88D31767A1E226D7B8", var_16 );
    var_12 = randomint( 100 );
    var_18 = var_12 <= var_17;

    if ( ( var_18 || var_14 ) && airlock_button_l() )
        var_2[var_2.size] = airlock_button_think();

    if ( getdvarint( "_encstr_9F8413C399030751F8767281859F9037F13527EC97", 0 ) > 0 && getdvarint( "_encstr_B4861637C693D74C277D99CCBE197BAE13B12BEB8D16DC86", 0 ) > 0 )
    {
        if ( var_0.type == "_encstr_AA2E2272233864D21DB4879EB82F771273A94068218F62DF175F06E007D03B8FF059FFD3" )
            var_2[var_2.size] = "_encstr_94201F7673491898FBC1F3E2857D119A13078A2737E8F027F68FA86BA89F8887BF";
        else if ( var_0.type == "_encstr_9540253139D7C6B7F61DFAB036BBB05EDCD76E0EB0DD9B7DB10B8DA159F51BCAECB2E619B0C9F2" )
            var_2[var_2.size] = "_encstr_BDF81BC493B1DBDB8EFAC1365D7346B29C7DD8B09BD0FACAE05A36BEC8";
        else if ( var_0.type == "_encstr_BAF923C44EFA1BEDDEA3FA58C6770BCB9BAFCDC185EE73AFC62C36D0B27DA17BD8B4C885F2" )
            var_2[var_2.size] = "_encstr_BE611B264E1BF6EDE8AFC1C6AEB98C959C7DD8C2B934EB9C2C93AC7D46";
    }

    if ( var_15 )
    {
        if ( var_13 )
        {
            playfx( scripts\engine\utility::getfx( "_encstr_8FB21F6766E1EB4CC9BE36DEBD8EBE8D2C36342BFAA17BC65A322CBC7D6CDB16D8" ), var_0.origin, anglestoforward( var_0.angles ), anglestoup( var_0.angles ) );
            var_2 = [];
            var_2[var_2.size] = "_encstr_B7BE0C2B3028C75A5918661D7F01";
            var_19 = "_encstr_8B181D190FF5894ED6F5370B9BD17DB985E61D16AFDCB0EA9D34D12FBE2681";
            var_1 playsoundtoplayer( var_19, var_1, var_1 );
            airdrop_crushchicken( var_1 );
            var_1._id_136CA = scripts\engine\utility::array_add( var_1._id_136CA, var_0.spawn_maint_wave );
        }
        else if ( var_14 )
        {
            var_2[var_2.size] = "_encstr_B94D1005B2A5C0B76359CB5062574E787D34";
            var_20 = "_encstr_8AB71A9908470826F257D7FBFB0BF8F811E503B179AE9856AA6F4B21";
            var_1 playsoundtoplayer( var_20, var_1, var_1 );
            var_1._id_136CA = scripts\engine\utility::array_add( var_1._id_136CA, var_0.spawn_maint_wave );
        }
    }

    return var_2;
}

airdrop_watchforcrateuseend( var_0 )
{
    var_1 = getdvarint( "_encstr_AB1313B3069219D6CB8F29D17752AD384D9FDC88AF", 0 ) == 1;

    if ( var_1 )
        iprintlnbold( "_encstr_A4CC05AC204A8F" + var_0 );
}
