// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

init()
{
    _encstr_A18624E0EFEA87BAA35A56BBFB0EBF36CA096B407105AFF796F09F4F7DAFB0DCE162357947B7::init();
    _encstr_BA9929DB6F38F4738DD3361ADB4877AE68DB5449A178BAC6BEEB49C2A3B19FA290C7F3D10760C4FAD4E382::init();
    _encstr_B1E12A9BC69C9683A3DCBCD6E0F23B85DAB28E5EE0953779314EBEB04EAD7BC9CBD7D139B046954E7176B9D8::init();
    _findgivearmoramountanddropleftovers::init();
    scripts\mp\flags::gameflaginit( "_encstr_AA250D0FF5B0C7F66BD30BB8439569", 0 );
    level thread _spawnpois();
}

initplayer()
{
    _encstr_A18624E0EFEA87BAA35A56BBFB0EBF36CA096B407105AFF796F09F4F7DAFB0DCE162357947B7::initplayer();
}

onprematchdone()
{
    scripts\mp\flags::gameflagwait( "_encstr_AA250D0FF5B0C7F66BD30BB8439569" );
    _encstr_BA9929DB6F38F4738DD3361ADB4877AE68DB5449A178BAC6BEEB49C2A3B19FA290C7F3D10760C4FAD4E382::onprematchdone();
    _encstr_B1E12A9BC69C9683A3DCBCD6E0F23B85DAB28E5EE0953779314EBEB04EAD7BC9CBD7D139B046954E7176B9D8::onprematchdone();
}

getinteractiveoutlineasset()
{
    return "_encstr_AD0F1217CDFBC334B548A91260A12B8BF6366594";
}

_spawnpois()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    var_0 = 0.05;
    var_1 = 5;
    var_2 = 5;
    var_3 = 7;
    var_4 = 7;

    if ( getdvar( "_encstr_A10E10BABF1EB12D4B819F18E8488BAA02E5", "_encstr_A40101" ) == "_encstr_BE180432D63D" || getdvar( "_encstr_A10E10BABF1EB12D4B819F18E8488BAA02E5", "_encstr_A40101" ) == "_encstr_89E10946E1536E6DD6A2B0" || getdvar( "_encstr_A10E10BABF1EB12D4B819F18E8488BAA02E5", "_encstr_A40101" ) == "_encstr_AD1F058082CACF" )
    {
        level.binoculars_checkexpirationtimer = getdvarint( "_encstr_9C251F6EB139AF13B5EDAF2B3B95CD3AF5194B6ED19CA5C4AB47D2EDDCFA382C91", 35 );
        level._id_12946 = getdvarint( "_encstr_9E5A24283FC2466D7245383D1B2AADEB07DB70B0CB7AD8259BAB2B30F5A1D931649F40084F08", 1 );
        level.fly_over_path = getdvarint( "_encstr_B90C2437B14EF5266BEDBE985DF2371D853AD2BD73EB23966E3AE4A526BA3A4BDBCDEB1CC219", 0 );
        level thread _id_1325B();
    }

    level._id_11C41 = getdvarint( "_encstr_A62A1BF29B786F8490578094EB780FB716D61ADBE346177E1803876EFF", var_4 );
    level._id_11B6D = getdvarint( "_encstr_87251B1327BEB585E1F5831BEA9BC8CA39FA59E1D14E16B13A4BDBCD9B", var_3 );

    if ( level._id_11C41 < level._id_11B6D )
        level._id_11B6D = randomintrange( level._id_11C41, level._id_11B6D + 1 );

    var_5 = getdvarint( "_encstr_80AF14EBF08E057A81D8261A394783C956907F576060", 65 );
    var_6 = _encstr_BA9929DB6F38F4738DD3361ADB4877AE68DB5449A178BAC6BEEB49C2A3B19FA290C7F3D10760C4FAD4E382::registeraccesscardlocs();

    if ( isdefined( var_6 ) && var_6.size > 0 )
    {
        var_6 = play_lz_vo( var_6 );
        var_6 = ai_semtex_swapp( var_6, var_5, level.fly_over_path );

        if ( isdefined( var_6 ) && var_6.size > 0 )
            _encstr_BA9929DB6F38F4738DD3361ADB4877AE68DB5449A178BAC6BEEB49C2A3B19FA290C7F3D10760C4FAD4E382::_id_131C0( var_6 );
    }

    var_7 = getdvarint( "_encstr_804A15B2932FD50F8AD01902D1B09B1887883B1AD8234A", 65 );
    var_8 = _encstr_B1E12A9BC69C9683A3DCBCD6E0F23B85DAB28E5EE0953779314EBEB04EAD7BC9CBD7D139B046954E7176B9D8::registeraccesscardlocs();

    if ( isdefined( var_8 ) && var_8.size > 0 )
    {
        var_8 = play_music_to_team( var_8 );
        var_8 = ai_semtex_swapp( var_8, var_7, level.fly_over_path );

        if ( isdefined( var_8 ) && var_8.size > 0 )
            _encstr_B1E12A9BC69C9683A3DCBCD6E0F23B85DAB28E5EE0953779314EBEB04EAD7BC9CBD7D139B046954E7176B9D8::_id_131C0( var_8 );
    }

    var_9 = _encstr_A18624E0EFEA87BAA35A56BBFB0EBF36CA096B407105AFF796F09F4F7DAFB0DCE162357947B7::register_vfx();

    if ( isdefined( var_9 ) && var_9.size > 0 )
    {
        var_9 = ai_semtex_swapp( var_9, level._id_11B6D, 1 );

        if ( isdefined( var_9 ) && var_9.size > 0 )
            _encstr_A18624E0EFEA87BAA35A56BBFB0EBF36CA096B407105AFF796F09F4F7DAFB0DCE162357947B7::_id_1314B( var_9 );
    }

    var_10 = scripts\engine\utility::getstructarray( "_encstr_ADE713C49CBE39ACDC0E85EE9B7DDCE858D196F69B", "_encstr_B8CE0BE43FC317DF690862BA48" );

    for ( var_11 = 0; var_11 < var_10.size; var_11++ )
    {
        wait( var_0 );
        _encstr_87D224DBF00DBC23536EFFA5875037C64BA833F3D08BF2A649D687B215E3B30ED7681EAA205F::spawnambulance( var_10[var_11] );
    }

    scripts\mp\flags::gameflagset( "_encstr_AA250D0FF5B0C7F66BD30BB8439569" );
}

ai_semtex_swapp( var_0, var_1, var_2 )
{
    if ( var_0.size == 0 || var_1 == 0 )
        return undefined;

    if ( var_1 > var_0.size )
        var_1 = var_0.size;

    if ( getdvar( "_encstr_A10E10BABF1EB12D4B819F18E8488BAA02E5", "_encstr_A40101" ) == "_encstr_BE180432D63D" || getdvar( "_encstr_A10E10BABF1EB12D4B819F18E8488BAA02E5", "_encstr_A40101" ) == "_encstr_AD1F058082CACF" )
        return _encstr_A13B293BF60BE722D1A8DEF2984FDF7F406DA4B9973147BDA5D8C16A08339763BA4F3D6725583B2547F80A::ai_shooting_timer( var_0, var_1, var_2 );
    else if ( getdvar( "_encstr_A10E10BABF1EB12D4B819F18E8488BAA02E5", "_encstr_A40101" ) == "_encstr_89E10946E1536E6DD6A2B0" )
        return _encstr_986F2E8BA05DEC73231E8FF5B760E736BB7803A3A0DB22569986F7F7C7F0D73BFB689A5918AB5B5FB367D3ED48D9C706::ai_shooting_timer( var_0, var_1, var_2 );
    else if ( !isdefined( level.br_circle ) || !isdefined( level.br_level ) )
        return ai_shooting_watch( var_0, var_1 );

    var_3 = level.br_level.default_class_chosen.size - 1;
    var_4 = int( max( 1, var_3 * getdvarfloat( "_encstr_97A90D3E92F9E9E86987809047AB61", 1.0 ) ) );

    for ( var_5 = 0; var_5 < var_0.size; var_5++ )
    {
        var_6 = var_0[var_5];
        var_7 = randomintrange( -1 * var_4, var_4 + 1 );
        var_6.score = _encstr_8A18233F26D6B373C5535613B3D5AABF583020D08BFDCE86F68B4649324ABAB809C65856C7::relic_amped_reset_deathshield_on_revived( var_6.origin ) + var_7;
    }

    var_8 = scripts\engine\utility::array_sort_with_func( var_0, ::hidequestcircletoall );
    var_9 = [];

    for ( var_5 = 0; var_5 < var_1; var_5++ )
        var_9[var_5] = var_8[var_5];

    return scripts\engine\utility::array_slice( var_8, 0, var_1 );
}

hidequestcircletoall( var_0, var_1 )
{
    return var_0.score > var_1.score;
}

ai_shooting_watch( var_0, var_1 )
{
    if ( var_0.size == 0 || var_1 == 0 )
        return;

    var_2 = [];

    if ( var_0.size > 0 )
    {
        var_0 = scripts\engine\utility::array_randomize( var_0 );
        var_3 = int( min( var_1, var_0.size ) );

        for ( var_4 = 0; var_4 < var_3; var_4++ )
            var_2[var_2.size] = var_0[var_4];
    }

    return var_2;
}

showmiscmessagetoteam( var_0, var_1, var_2, var_3 )
{
    if ( isdefined( var_0 ) )
    {
        var_4 = "_encstr_8BAA0D6BB288F0787D49920E07EF7B";
        var_5 = 1;
        var_6 = 0;
        var_7 = -1;
        var_8 = tablelookuprownum( var_4, var_5, var_1 );

        if ( isdefined( var_8 ) && var_8 >= 0 )
            var_7 = int( tablelookupbyrow( var_4, var_8, var_6 ) );

        if ( var_7 < 0 )
            return;

        var_9 = undefined;

        if ( isdefined( var_3 ) )
            var_9 = gettime() + var_3;

        var_12 = scripts\mp\utility\teams::getteamdata( var_0, "_encstr_8875080E3685E52B93B9" );

        foreach ( var_14 in var_12 )
            var_14 scripts\mp\utility\lower_message::setlowermessageomnvar( var_7, var_9, var_2 );
    }
}

initstatemachineforpoitype( var_0 )
{
    if ( !isdefined( level.poistates ) )
        level.poistates = [];

    level.poistates[var_0] = [];
}

registerstatecallbacksforpoitype( var_0, var_1, var_2, var_3, var_4 )
{
    level.poistates[var_0][var_1] = spawnstruct();
    level.poistates[var_0][var_1].onenter = var_2;
    level.poistates[var_0][var_1].onupdate = var_3;
    level.poistates[var_0][var_1].onexit = var_4;
}

gotopoistate( var_0, var_1 )
{
    var_2 = self;

    if ( isdefined( var_2.currentstate ) )
    {
        var_3 = level.poistates[var_0][var_2.currentstate];

        if ( isdefined( var_3 ) && isdefined( var_3.onexit ) )
            level [[ var_3.onexit ]]( var_2 );
    }

    var_2 notify( "_encstr_B77811E0F65AEBE6A3583A56D7364385CDEC95" );
    var_2.currentstate = var_1;
    var_3 = level.poistates[var_0][var_2.currentstate];

    if ( isdefined( var_3 ) )
    {
        if ( isdefined( var_3.onenter ) )
            level [[ var_3.onenter ]]( var_2 );

        if ( isdefined( var_3.onupdate ) )
            var_2 thread _poistateupdate( var_3.onupdate );
    }
}

gotopoistateontimer( var_0, var_1, var_2 )
{
    var_3 = self;
    var_3 endon( "_encstr_A3750609A5E61883" );
    var_3 endon( "_encstr_B77811E0F65AEBE6A3583A56D7364385CDEC95" );
    wait( var_2 );
    var_3 thread gotopoistate( var_0, var_1 );
}

getcurrentpoistate()
{
    var_0 = self;
    return var_0.currentstate;
}

_poistateupdate( var_0 )
{
    var_1 = self;
    var_1 endon( "_encstr_A3750609A5E61883" );
    var_2 = var_1.currentstate;

    while ( var_2 == var_1.currentstate )
    {
        level [[ var_0 ]]( var_1 );
        waitframe();
    }
}

_id_1325B()
{
    if ( !isdefined( level.mapcorners ) )
        waitframe();

    var_0 = level.mapcorners[0].origin[0];
    var_1 = level.mapcorners[1].origin[0];
    var_2 = ( level.mapcorners[0].origin[0], level.mapcorners[0].origin[1], level.mapcorners[0].origin[2] );
    var_3 = ( level.mapcorners[1].origin[0], level.mapcorners[0].origin[1], level.mapcorners[1].origin[2] );

    if ( var_1 < var_0 )
    {
        var_2 = ( level.mapcorners[1].origin[0], level.mapcorners[0].origin[1], level.mapcorners[1].origin[2] );
        var_3 = ( level.mapcorners[0].origin[0], level.mapcorners[0].origin[1], level.mapcorners[0].origin[2] );
    }

    var_4 = level.mapcorners[0].origin[1];
    var_5 = level.mapcorners[1].origin[1];
    var_6 = ( level.mapcorners[0].origin[0], level.mapcorners[1].origin[1], level.mapcorners[0].origin[2] );
    var_7 = ( level.mapcorners[1].origin[0], level.mapcorners[1].origin[1], level.mapcorners[1].origin[2] );

    if ( var_5 < var_4 )
    {
        var_6 = ( level.mapcorners[1].origin[0], level.mapcorners[1].origin[1], level.mapcorners[1].origin[2] );
        var_7 = ( level.mapcorners[0].origin[0], level.mapcorners[1].origin[1], level.mapcorners[0].origin[2] );
    }

    var_8 = [];

    if ( scripts\cp_mp\utility\game_utility::update_ai_volumes() )
    {
        level.ignorevehicleexplosivedamage = abs( distance( var_7, var_2 ) );
        var_9 = level.ignorevehicleexplosivedamage / 10;
        var_2 = ( var_2[0] + var_9, var_2[1] - var_9, var_2[2] );
        var_3 = ( var_3[0] - var_9, var_3[1] - var_9, var_3[2] );
        var_6 = ( var_6[0] - var_9, var_6[1] + var_9, var_6[2] );
        var_7 = ( var_7[0] + var_9, var_7[1] + var_9, var_7[2] );
        level.ignorevehicleexplosivedamage = abs( distance( var_7, var_2 ) );

        for ( var_10 = 1; var_10 < 4; var_10 = var_10 + 2 )
        {
            var_11 = var_10 * level.ignorevehicleexplosivedamage / 2;

            for ( var_12 = 1; var_12 < 4; var_12 = var_12 + 2 )
            {
                var_13 = var_12 * level.ignorevehicleexplosivedamage / 2;
                var_14 = ( var_7[0] + var_11 / 2, var_7[1] + var_13 / 2, 0 );
                var_8[var_8.size] = var_14;
            }
        }
    }

    level._id_12950 = [];

    if ( level.mapname == "_encstr_A6341077402EAAEB6F61873EDB3BE27971B0" )
    {
        level._id_12950[level._id_12950.size] = ( 3965, 4054, 0 );
        level._id_12950[level._id_12950.size] = ( 4069, -4150, 0 );
        level._id_12950[level._id_12950.size] = ( -4035, -4074, 0 );
        level._id_12950[level._id_12950.size] = ( -4009, 4105, 0 );
    }
    else if ( level.mapname == "_encstr_98C50CAD07D7C4E4EB5BF6DC2BCB" )
    {
        level._id_12950[level._id_12950.size] = ( 46569.5, -8170, 0 );
        level._id_12950[level._id_12950.size] = ( 56849.5, -8170, 0 );
        level._id_12950[level._id_12950.size] = ( 67081.5, -17919.5, 0 );
        level._id_12950[level._id_12950.size] = ( 46593, -17919.5, 0 );
    }
    else if ( scripts\cp_mp\utility\game_utility::unlink_on_ai_death() )
    {
        level._id_12950[level._id_12950.size] = ( -21299.2, 41779.2, 0 );
        level._id_12950[level._id_12950.size] = ( 37683.2, 41779.2, 0 );
        level._id_12950[level._id_12950.size] = ( 37683.2, -17203.2, 0 );
        level._id_12950[level._id_12950.size] = ( -21299.2, -17203.2, 0 );
    }
    else
    {
        var_15 = 0.8;
        var_16 = 0.5;
        var_17 = var_15 * var_16;
        level._id_12950[level._id_12950.size] = ( var_0 * var_17, var_5 * var_17, 0 );
        level._id_12950[level._id_12950.size] = ( var_1 * var_17, var_5 * var_17, 0 );
        level._id_12950[level._id_12950.size] = ( var_1 * var_17, var_4 * var_17, 0 );
        level._id_12950[level._id_12950.size] = ( var_0 * var_17, var_4 * var_17, 0 );
    }

    level._id_12950 = scripts\engine\utility::array_randomize( level._id_12950 );

    if ( level.binoculars_checkexpirationtimer > 0 && scripts\cp_mp\utility\game_utility::update_ai_volumes() )
    {
        var_18 = randomintrange( 0, 5 );
        var_9 = level.ignorevehicleexplosivedamage / 10;
        var_19 = level.ignorevehicleexplosivedamage / ( 100 / level.binoculars_checkexpirationtimer );

        switch ( var_18 )
        {
            case 0:
                var_20 = ( var_2[0] + var_9, var_2[1] - var_9, var_2[2] );
                var_21 = ( var_3[0] - var_19, var_3[1] - var_9, var_3[2] );
                var_22 = ( var_6[0] - var_19, var_6[1] + var_19, var_6[2] );
                var_23 = ( var_7[0] + var_9, var_7[1] + var_19, var_7[2] );
                break;
            case 1:
                var_20 = ( var_2[0] + var_19, var_2[1] - var_9, var_2[2] );
                var_21 = ( var_3[0] - var_9, var_3[1] - var_9, var_3[2] );
                var_22 = ( var_6[0] - var_19, var_6[1] + var_9, var_6[2] );
                var_23 = ( var_7[0] + var_19, var_7[1] + var_19, var_7[2] );
                break;
            case 2:
                var_20 = ( var_2[0] + var_19, var_2[1] - var_19, var_2[2] );
                var_21 = ( var_3[0] - var_9, var_3[1] - var_19, var_3[2] );
                var_22 = ( var_6[0] - var_9, var_6[1] + var_9, var_6[2] );
                var_23 = ( var_7[0] + var_19, var_7[1] + var_9, var_7[2] );
                break;
            case 3:
                var_20 = ( var_2[0] + var_9, var_2[1] - var_19, var_2[2] );
                var_21 = ( var_3[0] - var_19, var_3[1] - var_19, var_3[2] );
                var_22 = ( var_6[0] - var_19, var_6[1] + var_9, var_6[2] );
                var_23 = ( var_7[0] + var_9, var_7[1] + var_9, var_7[2] );
                break;
            case 4:
                var_20 = ( var_2[0] + var_19, var_2[1] - var_19, var_2[2] );
                var_21 = ( var_3[0] - var_19, var_3[1] - var_19, var_3[2] );
                var_22 = ( var_6[0] - var_19, var_6[1] + var_19, var_6[2] );
                var_23 = ( var_7[0] + var_19, var_7[1] + var_19, var_7[2] );
                break;
            default:
                var_20 = ( var_2[0] + var_19, var_2[1] - var_19, var_2[2] );
                var_21 = ( var_3[0] - var_19, var_3[1] - var_19, var_3[2] );
                var_22 = ( var_6[0] - var_19, var_6[1] + var_19, var_6[2] );
                var_23 = ( var_7[0] + var_19, var_7[1] + var_19, var_7[2] );
                break;
        }

        var_24 = [];
        level._id_121BB = [];
        level._id_121BA = abs( distance( var_23, var_20 ) );
        level._id_127DE = level._id_121BA / 2;

        for ( var_10 = 1; var_10 < 4; var_10 = var_10 + 2 )
        {
            var_11 = var_10 * level._id_121BA / 2;

            for ( var_12 = 1; var_12 < 4; var_12 = var_12 + 2 )
            {
                var_13 = var_12 * level._id_121BA / 2;
                var_14 = ( var_23[0] + var_11 / 2, var_23[1] + var_13 / 2, 0 );
                var_24[var_24.size] = var_14;
            }
        }

        if ( level._id_12946 == 2 )
            level._id_121BB = scripts\engine\utility::array_randomize( var_24 );
        else
        {
            switch ( var_18 )
            {
                case 0:
                    if ( level._id_12946 )
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                    }
                    else
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                    }

                    break;
                case 1:
                    if ( level._id_12946 )
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                    }
                    else
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                    }

                    break;
                case 2:
                    if ( level._id_12946 )
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                    }
                    else
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                    }

                    break;
                case 3:
                    if ( level._id_12946 )
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                    }
                    else
                    {
                        level._id_121BB[level._id_121BB.size] = var_24[0];
                        level._id_121BB[level._id_121BB.size] = var_24[1];
                        level._id_121BB[level._id_121BB.size] = var_24[3];
                        level._id_121BB[level._id_121BB.size] = var_24[2];
                    }

                    break;
                case 4:
                    level._id_121BB = scripts\engine\utility::array_randomize( var_24 );
                    break;
                default:
                    level._id_121BB = scripts\engine\utility::array_randomize( var_24 );
                    break;
            }
        }
    }
}

play_lz_vo( var_0 )
{
    if ( getdvarint( "_encstr_959D1837D84ED7C427F5DA5A7BE6ADAF91D2B9E8395A4C571D2B", 1 ) == 0 || !scripts\cp_mp\utility\game_utility::unsetchainkillstreaks() )
        return var_0;

    var_1 = getdvarfloat( "_encstr_B11D206E6CE4F52627F5B5B4BD9BDAAF91969BD139D213AEA3B2EBDA2DDCF507954E", 1.0 );
    var_2 = getdvarfloat( "_encstr_88792113A7F0B1E3569ECA12602E0F79981BAB9C1D4086E77DF1815A8888A7EF58D724", 7000 );
    var_3 = var_2 * var_2;
    var_4 = [];
    var_5 = [];
    var_5[0] = battle_tracks_onexitvehicle( ( 40925, -7519, 0 ), 49000000 );
    var_5[1] = battle_tracks_onexitvehicle( ( -40840, -4814, 0 ), 36000000 );
    var_5[2] = battle_tracks_onexitvehicle( ( 42787, 8460, 0 ), 81000000 );
    var_5[3] = battle_tracks_onexitvehicle( ( -7848, -42422, 0 ), 121000000 );

    foreach ( var_7 in var_0 )
    {
        var_8 = 0;

        foreach ( var_10 in level.calloutglobals.calloutzones )
        {
            if ( ispointinvolume( var_7.origin, var_10 ) )
            {
                if ( !isdefined( var_10.wait_for_computer_power ) )
                    var_10.wait_for_computer_power = [];

                var_8 = 1;
                var_10.wait_for_computer_power[var_10.wait_for_computer_power.size] = var_7;
                break;
            }
        }

        if ( !var_8 )
        {
            foreach ( var_10 in var_5 )
            {
                var_13 = distance2dsquared( var_10.origin, var_7.origin );

                if ( var_13 < var_10._id_129E5 )
                {
                    var_8 = 1;
                    var_10.wait_for_computer_power[var_10.wait_for_computer_power.size] = var_7;
                    break;
                }
            }
        }

        if ( !var_8 )
            var_4[var_4.size] = var_7;
    }

    var_16 = scripts\engine\utility::array_combine( level.calloutglobals.calloutzones, var_5 );

    foreach ( var_10 in var_16 )
    {
        if ( var_10.wait_for_computer_power.size == 0 )
        {
            var_10.wait_for_computer_power = undefined;
            continue;
        }

        var_18 = scripts\engine\utility::array_randomize( var_10.wait_for_computer_power );
        var_4[var_4.size] = var_18[0];
        var_19 = [];
        var_19[0] = var_18[0];
        var_20 = int( ceil( var_18.size / var_1 ) );
        var_21 = 1;

        for ( var_22 = 1; var_22 < var_18.size && var_21 < var_20; var_22++ )
        {
            var_23 = var_18[var_22];
            var_24 = 1;

            foreach ( var_26 in var_19 )
            {
                var_13 = distance2dsquared( var_23.origin, var_26.origin );

                if ( var_13 < var_3 )
                {
                    var_24 = 0;
                    break;
                }
            }

            if ( var_24 )
            {
                var_4[var_4.size] = var_23;
                var_19[var_19.size] = var_23;
                var_21++;
            }
        }

        var_10.wait_for_computer_power = undefined;
    }

    return var_4;
}

play_music_to_team( var_0 )
{
    if ( getdvarint( "_encstr_948019AF2392311973B6288613419333F7C58377A3431C6E0B993D", 1 ) == 0 || !scripts\cp_mp\utility\game_utility::turretdisabled() )
        return var_0;

    var_1 = getdvarfloat( "_encstr_89FB21ABF1A6DF3E380FCCB20BF0872358898213BB7EFFF62871D5973BB08D4F77C1AB", 1.0 );
    var_2 = getdvarfloat( "_encstr_B9BE22376CE4D798C9F51DE42CC8CA93D723A5DC474ED28957A356F5DA5A37EB19D29BE8", 7000 );
    var_3 = var_2 * var_2;
    var_4 = [];

    foreach ( var_6 in var_0 )
    {
        var_7 = 0;

        foreach ( var_9 in level.calloutglobals.calloutzones )
        {
            if ( ispointinvolume( var_6.origin, var_9 ) )
            {
                if ( !isdefined( var_9._id_13C6A ) )
                    var_9._id_13C6A = [];

                var_7 = 1;
                var_9._id_13C6A[var_9._id_13C6A.size] = var_6;
                break;
            }
        }

        if ( !var_7 )
            var_4[var_4.size] = var_6;
    }

    foreach ( var_9 in level.calloutglobals.calloutzones )
    {
        if ( !isdefined( var_9._id_13C6A ) || var_9._id_13C6A.size == 0 )
        {
            var_9._id_13C6A = undefined;
            continue;
        }

        var_13 = scripts\engine\utility::array_randomize( var_9._id_13C6A );
        var_4[var_4.size] = var_13[0];
        var_14 = [];
        var_14[0] = var_13[0];
        var_15 = int( ceil( var_13.size / var_1 ) );
        var_16 = 1;

        for ( var_17 = 1; var_17 < var_13.size && var_16 < var_15; var_17++ )
        {
            var_18 = var_13[var_17];
            var_19 = 1;

            foreach ( var_21 in var_14 )
            {
                var_22 = distance2dsquared( var_18.origin, var_21.origin );

                if ( var_22 < var_3 )
                {
                    var_19 = 0;
                    break;
                }
            }

            if ( var_19 )
            {
                var_4[var_4.size] = var_18;
                var_14[var_14.size] = var_18;
                var_16++;
            }
        }

        var_9._id_13C6A = undefined;
    }

    return var_4;
}

battle_tracks_onexitvehicle( var_0, var_1 )
{
    var_2 = spawnstruct();
    var_2.origin = var_0;
    var_2._id_129E5 = var_1;
    var_2.wait_for_computer_power = [];
    return var_2;
}

player_give_intel_1_ks( var_0 )
{
    var_1 = incrementpersistentstat( level.players, self.origin, var_0 );

    foreach ( var_3 in var_1 )
    {
        if ( !isdefined( var_3 ) || !isalive( var_3 ) )
            continue;

        if ( var_3 getstance() != "_encstr_9F24062875D5FD98" )
            continue;

        var_4 = var_3 getboundshalfsize();
        var_0 = var_4[0];
        var_5 = 2.0 * var_4[2];

        if ( capsuletracepassed( var_3.origin, var_0, var_5, undefined, 0, 0 ) )
            continue;

        var_3 setstance( "_encstr_9C3D071B63023B26C3", 1 );
    }
}
