// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

setupcommoncallbacks()
{
    level.onnormaldeath = ::oncommonnormaldeath;
    level.onsuicidedeath = ::oncommonsuicidedeath;
    level.onteamchangedeath = ::oncommonteamchangedeath;

    if ( isusingmatchrulesdata() )
        setdynamicdvar( "_encstr_9F02182F27E629BFD8609F6959ABCEE037A3FF078387237F888B", getmatchrulesdata( "_encstr_BE700D1BDB5BB5DEDCD31C3AA5B7CD", "_encstr_A93F0F3F5D35989158D05F9F181347D2A7" ) );

    level.set_systems_init_flag = getdvarint( "_encstr_9F02182F27E629BFD8609F6959ABCEE037A3FF078387237F888B", 0 );

    if ( level.set_systems_init_flag > 0 )
    {
        _id_131C1();
        setomnvar( "_encstr_BD301598976FC1EBF247A1B81FAA4F08AE5F28383FECD9", 1 );
        level thread _id_1439C();
    }

    var_0 = undefined;

    if ( getdvar( "_encstr_A3E50BB4F963C07726B069E13F" ) == "_encstr_9DB606854E567385" )
    {
        var_1 = 0;

        if ( isusingmatchrulesdata() )
            var_1 = getmatchrulesdata( "_encstr_ADC90AF1B62133DE0970337A", "_encstr_974D0CBF104845FAD9A3877C9DDD" );
        else
            var_1 = scripts\mp\utility\dvars::dvarintvalue( "_encstr_974D0CBF104845FAD9A3877C9DDD", 0, 0, 2 );

        if ( var_1 == 2 )
            var_0 = 1;
    }

    level.maxtagsvisible = 0;
    var_2 = getdvarint( "_encstr_BE9C0BCC55174365D31941E829" ) && !getdvarint( "_encstr_B3390BA3091FD489090E7A2219" );

    if ( var_2 )
    {
        level.maxtagsvisible = getdvarint( "_encstr_A483150BC63B0FB7AB080AA1D09FEEA7B13665866DCD6B", 0 );

        if ( getdvar( "_encstr_BC050B8321978C816169428DCF" ) == "_encstr_9D0A0D8DEF670ABF8B48776B48A375" && getdvarint( "_encstr_B46A17076FC3487084AE71285375D996CAC79FA3B3AA2FD0A4", 1 ) )
            level.maxtagsvisible = 1;
    }
    else if ( getdvar( "_encstr_BC050B8321978C816169428DCF" ) == "_encstr_9D0A0D8DEF670ABF8B48776B48A375" && !dotournamentendgame() && !isgamebattlematch() )
        level.maxtagsvisible = 1;

    if ( level.maxtagsvisible || istrue( var_0 ) )
    {
        _id_11962();
        level._id_1326E = ::_id_1326E;
        level thread [[ level._id_1326E ]]();
        level thread scripts\mp\utility\entity::global_physics_sound_monitor();

        if ( getdvarint( "_encstr_A3F2148F229B96DFE73B18E1CB5779E1FF38E7AFA9E3", 1 ) == 1 )
        {
            _id_13237();
            level _id_13471();

            if ( getdvarint( "_encstr_8B5D1907D0838FA21B69BF394EDF3A7B89A0F78763FBE1BA73F1C5", 3 ) > 0 )
            {
                if ( !isdefined( game["_encstr_BC4D0A9FC31163490939151D"] ) )
                    game["_encstr_BC4D0A9FC31163490939151D"] = 0;
            }
        }
    }
    else
        level.maxtagsvisible = undefined;

    if ( getdvarint( "_encstr_B3FC1A0AB9408FBA771B2FCF4FA7C2EB3041451FF32B7643481D6B67", 0 ) == 1 )
    {
        level.select_stairway_spawners["_encstr_B7BA0E3FD8CBF7CA638EE71B783D5283"] = loadfx( "_encstr_B2CE294D58199AA467928105997F7793C5B1175A3872C6ABCFCB0F84DF9380E649EDB7504FF36A557D6A78" );
        level.playinggulagbink = 1;
    }

    var_3 = scripts\mp\utility\game::matchmakinggame() && scripts\mp\utility\game::usequesttimer();

    if ( var_3 )
    {
        level.setplayerselfrevivingextrainfo = 1;
        level.spawnoffsettacinsertmax["_encstr_A2930D6B0BD55CCFF058989F701903"] = loadfx( "_encstr_B65E3ADD56305293FF9FFEA003465CE88DAD6377FCDF0A64D3B3F608FA6381E0A3058BFD5F04A038FF5A2B738363CDA9BF8A1B53062F60732203E1FA" );
        level.spawnoffsettacinsertmax["_encstr_B2930DF0C72E10DFB2F913A4C15ADD"] = loadfx( "_encstr_A63A37B333F0BCA5DD0EF5D6C1797616DA956BBD91CA79B3663CBE8658B11BDBBB59ACE6D7B536FA36581C3A572756EB95B959DA5E17ECCCC3" );
        level.spawnoffsettacinsertmax["_encstr_A8CB0C87C9A023641029E321E058"] = loadfx( "_encstr_AB3336BB94FBC671C769173343F857E9785508B99F5F35212BC5E70288C30558EE8B17A223FFFBFD9A6AF9D0B3D0E3DC5F461A03482BD243" );
        level.spawnoffsettacinsertmax["_encstr_A208084E263B9F9E18B7"] = loadfx( "_encstr_AF392DECCCE1BC4BEE07EBC44E97ECB05BB238B1C2975E0DDDAC5973CB6799C3F543BBAC9573FAC42C1DDCC5B3993C" );
        level.spawnoffsettacinsertmax["_encstr_B8190CB2D358FA998B320827F24F"] = loadfx( "_encstr_8040313476F3F0CBC3A7D1201B8D9F71DF1DBFA1C95F28312B5A0848A6F345AABF8844AD25DB6E6D96B380B90A8D3328C32E4B" );
        level.spawnoffsettacinsertmax["_encstr_B6170EA87A651F49B7B3656B848FF0E7"] = loadfx( "_encstr_A81C3D533350F6534B2A67CDA20E27E0CD3F7370CFA2EDFAC335609346CB45F0B81078B963483B2F2368B1C94B20B71BF69BEBB38D99B80278529BE8D4C9D8" );
        level.spawnoffsettacinsertmax["_encstr_BDA50F71381DB8A32645A110B8C2FF28BF"] = loadfx( "_encstr_9E2F3B9BB850B21F67F29936163F2FDF5AF08BC0AFA9C0D09FEBAD33489B450807B8B751A3922FD23F180FE8C1289753F153A2EDA81806B97ED8947963" );

        if ( getdvarint( "_encstr_A9E818B9D8E4D71CC6C2BC954E7DB23BCA37D1D7D6BDC8B263CD", 1 ) > 0 )
        {
            var_4 = strtok( getdvar( "_encstr_B8441C936E93A7CA09C053EA2017844F88C5093CE858871521F83AE3E869", "_encstr_8B010566804C0C" ), "_encstr_884C02C6" );
            level.spawnoffsettacinsertmin = int( var_4[0] );
            level.spawnoutofboundstrigger = int( var_4[1] );
            level._id_12070 = ::_id_12070;
        }
    }

    level._id_1368D = undefined;
    scripts\mp\utility\join_team_aggregator::registeronplayerjointeamcallback( ::onplayerjointeamcommon );
    scripts\mp\utility\game::registerdogtagsenableddvar( scripts\mp\utility\game::getgametype(), 0 );
    level._effect["_encstr_BAF310F90AB04DB7370331AF3A29182025E5"] = loadfx( "_encstr_9BCE34EB333A17AAAF5B990D673702E120B01F07E871DF63D5139182C5538BABE8F9ABFF08C9DB5A19A5E97F3D5FA362D0A02213C822" );
}

updatecommongametypedvars()
{
    level.dogtagsenabled = scripts\mp\utility\dvars::dvarintvalue( "_encstr_9531083D4FC7D8510F9E", 0, 0, 1 );
    level.showenemydeathloc = scripts\mp\utility\dvars::dvarintvalue( "_encstr_9F3F0ECACDCA6BCB882B16A30D89DE6C", 0, 0, 3 );

    if ( level.dogtagsenabled )
        _encstr_BA6A24A3FA037340A3CBEF73D05DB0CFC732DB6A33B7B6823DB26D1FECB5680D9F8A1851ABF7::init();

    level.mpingamelootdrop = scripts\mp\utility\game::getgametype() == "_encstr_9C1904FCDC01" || scripts\mp\utility\dvars::respawn_players_into_plane( "_encstr_A61805573F9318" + scripts\mp\utility\game::getgametype() + "_encstr_B3470CA054EA87296D6F91905FAC", "_encstr_B60C140BBE1A91DC62CF4B37377A04B8AD9754ED2564" );

    if ( level.mpingamelootdrop )
        _encstr_BD2C2137D839B438E8E6CBDA0EBCCE586B2BD15E1C956E5E0EB15DCD462B9C5CB3CD8D::init();
}

oncommonnormaldeath( var_0, var_1, var_2, var_3, var_4, var_5 )
{
    var_6 = 0;

    if ( scripts\mp\utility\game::isteamreviveenabled() && scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) )
        level thread scripts\mp\teamrevive::spawnrevivetrigger( var_0, var_1, "_encstr_877414C8EA637F4B03B9646C8D3B16EF0A328830027F", var_3 );

    if ( isbot( self ) && isdefined( self.tutorial_lead_collected ) )
        self.tutorial_lead_collected = undefined;

    if ( istrue( level.flashpointactive ) )
        scripts\mp\flashpoint::flashpoint_processnewevent( var_1, var_0, gettime(), "_encstr_9DD509AC58101C99569327" + var_1.team );

    var_7 = scripts\mp\utility\game::islaststandenabled() && istrue( var_0._id_125B9 );

    if ( !var_7 && var_1.team != self.team )
    {
        var_8 = level.scoremod["_encstr_A3750609A5E61883"] * -1;

        if ( var_8 != 0 )
        {
            if ( level.teambased )
                level scripts\mp\gamescore::giveteamscoreforobjective( var_0.pers["_encstr_89EF05D46BA8FD"], var_8, 0 );
            else
                var_1 scripts\mp\gamescore::giveplayerscore( "_encstr_97D70583536853", var_8 );
        }

        var_6 = level.scoremod["_encstr_97D70583536853"];

        if ( istrue( var_5 ) )
            var_6 = var_6 + level.scoremod["_encstr_A45207289A234B7992"];

        if ( var_3 == "_encstr_8F280E35E759A9A325A5D069CF8B87D3" )
            var_6 = var_6 + level.scoremod["_encstr_818909A1591632E6D0EDD1"];

        if ( level.dogtagsenabled && scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) )
            level thread _encstr_BA6A24A3FA037340A3CBEF73D05DB0CFC732DB6A33B7B6823DB26D1FECB5680D9F8A1851ABF7::spawndogtags( var_0, var_1, "_encstr_8F1E10E5E23FE6AB42A16F9F70C14F76974A", var_3 );

        if ( level.mpingamelootdrop )
            level thread _encstr_BD2C2137D839B438E8E6CBDA0EBCCE586B2BD15E1C956E5E0EB15DCD462B9C5CB3CD8D::dropplayerstags( var_0, var_1 );
    }

    if ( istrue( level.supportcranked ) )
    {
        if ( scripts\mp\utility\game::matchmakinggame() && isdefined( var_1.cranked ) )
        {
            if ( !var_7 && var_6 != 0 )
            {
                var_6 = var_6 + 1;
                var_1 thread scripts\mp\rank::scoreeventpopup( "_encstr_B6B012E859C2D6B9B1DE27ACFADC7B472D33BC7D" + var_6 );
            }
        }

        var_1 scripts\mp\cranked::oncranked( var_0, var_1, var_2 );
    }

    if ( var_6 != 0 )
    {
        if ( level.teambased )
            level scripts\mp\gamescore::giveteamscoreforobjective( var_1.pers["_encstr_89EF05D46BA8FD"], var_6, 0 );
        else
            var_1 scripts\mp\gamescore::giveplayerscore( "_encstr_97D70583536853", var_6, var_0 );
    }
}

oncommonsuicidedeath( var_0 )
{
    if ( istrue( level.supportcranked ) )
        var_0 scripts\mp\cranked::cleanupcrankedplayertimer();

    if ( isdefined( level.scoremod ) )
    {
        var_1 = level.scoremod["_encstr_A3750609A5E61883"] * -1;

        if ( var_1 != 0 )
        {
            if ( level.teambased )
                level scripts\mp\gamescore::giveteamscoreforobjective( var_0.pers["_encstr_89EF05D46BA8FD"], var_1, 0 );
        }
    }

    if ( scripts\mp\utility\game::isteamreviveenabled() && scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) )
    {
        if ( level.teambased )
            level thread scripts\mp\teamrevive::spawnrevivetrigger( var_0, var_0, "_encstr_877414C8EA637F4B03B9646C8D3B16EF0A328830027F", "_encstr_97590CFD0825D7720BD1A018A1F3" );
    }

    if ( level.mpingamelootdrop )
        level thread _encstr_BD2C2137D839B438E8E6CBDA0EBCCE586B2BD15E1C956E5E0EB15DCD462B9C5CB3CD8D::dropplayerstags( var_0, undefined );

    if ( isdefined( level.modeonsuicidedeath ) )
        [[ level.modeonsuicidedeath ]]( var_0 );
}

oncommonteamchangedeath( var_0 )
{
    if ( istrue( level.supportcranked ) )
        var_0 scripts\mp\cranked::cleanupcrankedplayertimer();

    if ( isdefined( level.modeonteamchangedeath ) )
        [[ level.modeonteamchangedeath ]]( var_0 );
}

dogtagcommonallyonusecb( var_0 )
{

}

dogtagcommonenemyonusecb( var_0 )
{

}

onspawnplayercommon()
{
    if ( istrue( game["_encstr_9E810CC8F04D83308F7B40264A13"] ) )
    {
        var_0 = istrue( level.allowprematchdamage ) && istrue( level.spawnprotectiontimer );
        thread managespawnprotection( var_0 );
    }
    else if ( istrue( level.spawnprotectiontimer ) )
    {
        if ( isdefined( level._id_1368D ) )
        {
            if ( [[ level._id_1368D ]]() )
                thread managespawnprotection( 1 );
        }
        else
            thread managespawnprotection( 1 );
    }

    if ( scripts\mp\utility\game::isteamreviveenabled() )
        thread scripts\mp\teamrevive::updaterevivetriggerspawnposition();

    if ( istrue( level.disablesupersprint ) )
        self allowsupersprint( 0 );

    if ( istrue( level.loadout_updateammo ) )
    {
        self allowmountside( 0 );
        self allowmounttop( 0 );
    }

    if ( isdefined( level.modeonspawnplayer ) )
        [[ level.modeonspawnplayer ]]();
    else
        thread updatematchstatushintonspawncommon();

    if ( scripts\mp\utility\game::getgametypenumlives() != 0 )
        updatealiveomnvars();

    if ( istrue( game["_encstr_A4A90E389CC28D1DA5C6AC49B75D9B32"] ) )
    {
        if ( istrue( level._id_1343F ) )
            thread _id_13440();
        else
            self sethudtutorialmessage( "_encstr_880D1E80329FC1A4C7C5139DE728CC21D8AF505F2703F71C88702F5B97C3B071" );
    }
    else if ( !isagent( self ) )
        self clearhudtutorialmessage();

    if ( istrue( level.set_systems_init_flag ) )
        thread _id_1438C();

    if ( istrue( level.setplayerselfrevivingextrainfo ) )
    {
        self.spawnloot = 0;

        if ( scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) )
            thread _id_1439B();

        if ( getdvarint( "_encstr_A9E818B9D8E4D71CC6C2BC954E7DB23BCA37D1D7D6BDC8B263CD", 1 ) == 2 )
            thread _id_136B2();
    }
}

nvghintnotify( var_0 )
{
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self notify( "_encstr_A93613DC3BECBE370E8577B97D3AAE8EB74E4BC28D" );
    self endon( "_encstr_A93613DC3BECBE370E8577B97D3AAE8EB74E4BC28D" );
    var_1 = 1;

    if ( !isdefined( var_0 ) )
        var_0 = 0;

    for (;;)
    {
        if ( var_1 )
            self waittill( "_encstr_B8030CCE4B3B2B627B8523DEBAD1" );
        else
            self waittill( "_encstr_983508635BE787C548A1" );

        if ( var_0 < 2 )
        {
            if ( self usinggamepad() )
                var_2 = 32;
            else
                var_2 = 33;

            if ( scripts\mp\flags::gameflag( "_encstr_B87F0F4428EDB244C6889FF328BE123BA5" ) && !scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) )
            {
                level waittill( "_encstr_989F0E38272BD6161DB143F532BDDC2B" );
                wait 5;
                scripts\mp\utility\lower_message::setlowermessageomnvar( var_2 );
                wait 5;
                scripts\mp\utility\lower_message::setlowermessageomnvar( 0 );
            }
            else
            {
                if ( !var_0 )
                    wait 5;

                scripts\mp\utility\lower_message::setlowermessageomnvar( var_2 );
                wait 5;
                scripts\mp\utility\lower_message::setlowermessageomnvar( 0 );
            }

            var_0++;
            continue;
        }

        break;
    }
}

onplayerkilledcommon( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10 )
{
    if ( scripts\mp\utility\game::getgametypenumlives() != 0 )
        updatealiveomnvars();

    if ( scripts\mp\utility\game::islaststandenabled() && istrue( self.inlaststand ) && scripts\mp\utility\game::getgametype() != "_encstr_9507034B25" )
        oncommonnormaldeath( self, var_1, var_9, var_3, var_4, var_10 );

    if ( isdefined( level.onplayerkilled ) )
        [[ level.onplayerkilled ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 );

    if ( isdefined( level._id_12037 ) )
        [[ level._id_12037 ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 );

    if ( isdefined( level._id_12070 ) )
        [[ level._id_12070 ]]( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 );
}

onplayerconnectcommon()
{
    for (;;)
    {
        level waittill( "_encstr_87940A7F075A88E8ABD37951", var_0 );

        if ( isdefined( level.onplayerconnect ) )
            level thread [[ level.onplayerconnect ]]( var_0 );

        if ( scripts\cp_mp\utility\game_utility::isnightmap() )
            var_0 thread nvghintnotify();

        if ( level.set_systems_init_flag > 0 )
        {
            var_0.pers["_encstr_9E95066E81471B5F"] = "_encstr_9D0B0D0E6D3F9B87C980674F78817D";
            var_0.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"] = level.gun_loadouts["_encstr_BA840579D3F7F6"];

            if ( !isdefined( var_0.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"] ) )
            {
                var_0.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"] = 0;
                var_0.gungamegunindex = 0;
            }
            else
                var_0.gungamegunindex = var_0.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"];

            if ( !isdefined( var_0.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"] ) )
            {
                var_0.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"] = 0;
                var_0.gungameprevgunindex = 0;
            }
            else
                var_0.gungameprevgunindex = var_0.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"];

            scripts\mp\flags::gameflagwait( "_encstr_89200C9DBAE6B385AD59AFCD5947" );
            var_0 thread _encstr_985F1DF3C16B20334C5F96F07B506920155F2B538AAF177AA0B7EA0841624B::keepweaponsloaded();
        }
    }
}

onplayerdisconnectcommon( var_0 )
{
    if ( scripts\mp\utility\game::getgametypenumlives() != 0 )
        var_0 updatealiveomnvars();

    if ( isdefined( level.onplayerdisconnect ) )
        var_0 thread [[ level.onplayerdisconnect ]]( var_0 );
}

onplayerjointeamcommon( var_0 )
{
    if ( isdefined( level.onplayerjointeam ) )
        [[ level.onplayerjointeam ]]( self );

    if ( istrue( level.dogtagsenabled ) )
        _encstr_BA6A24A3FA037340A3CBEF73D05DB0CFC732DB6A33B7B6823DB26D1FECB5680D9F8A1851ABF7::onplayerjoinedteam( var_0 );

    if ( istrue( level.usezonecapture ) )
        _encstr_A3AF295A720B1BB083470E19BA8DA05741F2A5115190082D0F02834652F7680DBEFA53FC28F3477A6757D8::onplayerjoinedteam( var_0 );

    if ( scripts\cp_mp\utility\game_utility::isnightmap() )
        var_0 thread nvghintnotify( 1 );
}

managespawnprotection( var_0 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self endon( "_encstr_9D09184A65032A9649113F3B08E376D1D1069543DD47D3C150A0" );
    thread applyspawnprotection();

    if ( !istrue( level.allowprematchdamage ) )
        scripts\mp\flags::gameflagwait( "_encstr_989F0E38272BD6161DB143F532BDDC2B" );

    if ( var_0 )
        wait( level.spawnprotectiontimer );

    thread removespawnprotection();
}

applyspawnprotection()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self endon( "_encstr_9D09184A65032A9649113F3B08E376D1D1069543DD47D3C150A0" );
    self waittill( "_encstr_9B6F0FDC8316DDE62B8CF507C616CB599C" );
    self.spawnprotection = 1;
    scripts\mp\lightarmor::setlightarmorvalue( self, 1000, undefined, 0 );
}

removespawnprotection()
{
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );

    if ( isdefined( self ) )
        self.spawnprotection = 0;

    scripts\mp\lightarmor::lightarmor_unset( self );
    self notify( "_encstr_9D09184A65032A9649113F3B08E376D1D1069543DD47D3C150A0" );
}

updatealiveomnvars()
{
    if ( scripts\mp\utility\game::getgametype() == "_encstr_9507034B25" )
    {
        var_0 = 0;

        foreach ( var_2 in level.teamnamelist )
            var_0 = var_0 + scripts\mp\utility\teams::getteamdata( var_2, "_encstr_892A0BA3D3F25C4033ADD34893" );

        setomnvar( "_encstr_B39810F55379DE3BB9B8CA93460773946823", 0 );
        setomnvar( "_encstr_B48A0E8F8BF842284B2BE96EA0686E5A", var_0 );
    }
    else
    {
        setomnvar( "_encstr_B39810F55379DE3BB9B8CA93460773946823", scripts\mp\utility\teams::getteamdata( "_encstr_BC850785638DA59537", "_encstr_892A0BA3D3F25C4033ADD34893" ) );
        setomnvar( "_encstr_B48A0E8F8BF842284B2BE96EA0686E5A", scripts\mp\utility\teams::getteamdata( "_encstr_BA840579D3F7F6", "_encstr_892A0BA3D3F25C4033ADD34893" ) );
    }
}

updatematchstatushintonspawncommon()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self setclientomnvar( "_encstr_AD061ACF50F64D32C19E2CE9FEB94A1CDB18EF03F808AC19E9A5305B", 0 );
}

ffmessageonspawn()
{
    wait 1;

    if ( isdefined( self ) )
        scripts\mp\hud_message::showerrormessage( "_encstr_B9E51A6AA05E19254A159C4413CAD78C4A2554F5D5A4C462D7939E8A" );
}

_id_13440()
{
    self endon( "_encstr_A3750609A5E61883" );

    if ( !scripts\mp\flags::gameflag( "_encstr_989F0E38272BD6161DB143F532BDDC2B" ) )
    {
        thread scripts\mp\utility\print::tutorialprint( "_encstr_880D1E80329FC1A4C7C5139DE728CC21D8AF505F2703F71C88702F5B97C3B071", 5 );
        wait 6;
        scripts\mp\flags::gameflagwait( "_encstr_989F0E38272BD6161DB143F532BDDC2B" );
        thread scripts\mp\utility\print::tutorialprint( "_encstr_B74E1EA605AFA4E4A3A035A2F53D9C316579A993A7EA24823126F5C892748415", 5 );
    }
    else
        thread scripts\mp\utility\print::tutorialprint( "_encstr_B74E1EA605AFA4E4A3A035A2F53D9C316579A993A7EA24823126F5C892748415", 5 );
}

bearsred()
{
    game["_encstr_B8DA073D799798C7C7"]["_encstr_AD4F1277590582D9A02883C86638194B6B9BC7A3"] = "_encstr_A1610BE056E4D6F516B683B232";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_A32215B98395D8B41663A397EB1DB0C6D74EACE6D29B47"] = "_encstr_A1610BE056E4D6F516B683B232";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_BA0E15DC0756C6A585B18EBCD7C6F63B2B4EA3F5B71C37"] = "_encstr_BA241183B24EDAF56CF6638C268DBDDE8C5923";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_B43D118F2B59675826E2B148E9B84D67ABF167"] = "_encstr_9EDC10BBB59380AFFF509D6A2CDAB367D2FD";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_BC360EE63856D84B0B63A3BC7DCA7B23"] = "_encstr_BD9109409D6387F1EB6052";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_9D4E14E607B26CB458363ABCD73B5D564E93B48DB116"] = "_encstr_81BB0BFBDA4B97DFA42802C0CD";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_AA811767A3C79A4747D4BB1869B82B8AB8B8833BB21F80D97D"] = "_encstr_BA910F38594ED67D342D3B43B0B12B93A3";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_A68F165803A5D16BA2B59D23410A4B591EBFB150BF6C2929"] = "_encstr_82C90F07B2C9D6BEB55A63B16CA12C9637";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_B44616371C59B1D22C363A5EF55BAEB95A475A7BCD377D23"] = "_encstr_93AE0E333BD65AB798138F52A8F0DC62";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_A95715DB68233E47F1E1A4B110DB7B025320221218A733"] = "_encstr_880B0E08C53BDFB98918CAB2E89B6E93";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_B7D6147FC8B8EF4B2128597090FBD510AF1B71337C58"] = "_encstr_B6070E50824A0F36279D5B466B9338D1";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_B3EC126BD8938EF761713441806B8FD2E988D262"] = "_encstr_A27F0D07B29CB6EB4E2BCD3ABD8DD6";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_8082197F31EA6760263573F241524B61B4472B9097C27038F40D8B"] = "_encstr_810A0F6117A33271E34EB16BF7D6F87DFB";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_9FB51977590582D9A02883C866A8782B66933FFFF136EA98A011BD"] = "_encstr_8FA80E586F9A82998E02E2BBDBBB4A88";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_A8F51B2EE80FF173FE6A1070311239497F69BF29598FDBD7E662D868EB"] = "_encstr_ABA215F25D1542A793809F9F50095CAAAF6DFEADB0739B";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_BE67193783AC36A50B1BA3F2EBD185B1475A1BB036F539CA6CB79B"] = "_encstr_88790D10ABF0BC17D67B8AC303256B";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_9D8E15DC38CA8D2D851B1DE5F543D5B9E8D6C2DC3A2B39"] = "_encstr_A84F0D38CA27B6EBD1C92C1B5B5939";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_9D2512D3A2A5D873DA63311397B345787DF19B4B"] = "_encstr_A9260C1C56E4DABEA3ABDC2BBA07";
}

_id_12070( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    if ( scripts\mp\utility\game::getgametype() == "_encstr_87E507D23766566CD1" && isdefined( var_1 ) && isdefined( var_1.team ) && var_1.team == "_encstr_BA840579D3F7F6" )
        return;

    self setscriptablepartstate( "_encstr_AA9108994991F173B8B9", "_encstr_9BA4080D39CFFB5AB7C1", 0 );

    if ( !isplayer( var_1 ) || var_1.team == self.team )
        return;

    if ( var_1 == self )
        return;

    if ( istrue( var_1.isjuggernaut ) )
        return;

    self.spawnloot = 0;

    if ( isdefined( var_1 ) && istrue( var_1.iszombie ) )
        return;

    if ( !var_1 scripts\mp\riotshield::riotshield_hasweapon() )
    {
        if ( !isdefined( var_1.spawnloot ) )
            var_1.spawnloot = 1;
        else
        {
            var_1.spawnloot++;

            if ( var_1.spawnloot == level.spawnoffsettacinsertmin )
            {
                var_10 = var_1 getcustomizationbody();
                var_11 = var_1 getcustomizationhead();
                var_12 = var_1 getcustomizationviewmodel();
                var_1 detachall();
                var_1 setmodel( var_10 );
                var_1 setviewmodel( var_12 );
                var_13 = scripts\engine\utility::ter_op( var_1.team == "_encstr_BC850785638DA59537", "_encstr_ADCD27708F638987D5C8AFB1058F8A7310312B38F330183DB705E7A032B5B07E8E4BF3F2DAF05637A7", "_encstr_80CD278C3998F479316107D383E94226C1234355F3B0B122AF4D07E78780DA61904BFF1AA8B913094F" );
                var_1 attach( var_13, "_encstr_A40101", 1 );
                var_1.headmodel = var_13;
            }
            else if ( var_1.spawnloot == level.spawnoutofboundstrigger )
                var_1 setscriptablepartstate( "_encstr_AA9108994991F173B8B9", "_encstr_810E079AA3E7E5C573", 0 );
        }
    }
}

_id_1439B()
{
    waitframe();
    self setscriptablepartstate( "_encstr_AA9108994991F173B8B9", "_encstr_9BA4080D39CFFB5AB7C1", 0 );
}

_id_136B2()
{
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    self waittill( "_encstr_9B6F0FDC8316DDE62B8CF507C616CB599C" );

    if ( scripts\mp\riotshield::riotshield_hasweapon() )
        return;

    var_0 = self getcustomizationbody();
    var_1 = self getcustomizationhead();
    var_2 = self getcustomizationviewmodel();
    self detachall();
    self setmodel( var_0 );
    self setviewmodel( var_2 );
    var_3 = scripts\engine\utility::ter_op( self.team == "_encstr_BC850785638DA59537", "_encstr_ADCD27708F638987D5C8AFB1058F8A7310312B38F330183DB705E7A032B5B07E8E4BF3F2DAF05637A7", "_encstr_80CD278C3998F479316107D383E94226C1234355F3B0B122AF4D07E78780DA61904BFF1AA8B913094F" );
    self attach( var_3, "_encstr_A40101", 1 );
    self.headmodel = var_3;
}

_id_1439C()
{
    scripts\mp\flags::initgameflags();
    scripts\mp\flags::gameflaginit( "_encstr_89200C9DBAE6B385AD59AFCD5947", 0 );

    while ( !isdefined( level.weaponmapdata ) )
        waitframe();

    wait 0.1;
    level.blockweapondrops = 1;
    level.setback = 1;
    level.setbackstreak = 0;
    level.killsperweapon = 1;
    level.ladderindex = level.set_systems_init_flag;
    _encstr_985F1DF3C16B20334C5F96F07B506920155F2B538AAF177AA0B7EA0841624B::setgunladder();
    _encstr_985F1DF3C16B20334C5F96F07B506920155F2B538AAF177AA0B7EA0841624B::setgunsfinal();

    if ( turret_enemy_watcher_internal() )
        level._id_12037 = ::_id_12038;
    else
        level._id_12037 = ::_id_12037;

    scripts\mp\flags::gameflagset( "_encstr_89200C9DBAE6B385AD59AFCD5947" );
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_87C30FC410893345733089A330AB3E9362"] = getnextgun( 0 );
}

_id_12037( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    if ( isdefined( var_1 ) && isplayer( var_1 ) )
    {
        if ( isdefined( self.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] ) && self.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"].size > 0 )
            self.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] = [];

        if ( isdefined( var_1.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] ) && var_1.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"].size > 0 )
            var_1.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] = [];
    }

    if ( scripts\mp\utility\weapon::iskillstreakweapon( var_4 ) && var_1 != self )
        return;

    if ( var_3 == "_encstr_8FA10CBC37F487A99F9C0DE438C7" || isdefined( var_1 ) && isplayer( var_1 ) )
    {
        var_10 = scripts\mp\riotshield::isriotshield( var_4.basename );
        var_11 = scripts\mp\utility\weapon::isknifeonly( var_4.basename ) || scripts\mp\utility\weapon::turret_aimed_at_last_known( var_4.basename ) || scripts\mp\utility\weapon::isaxeweapon( var_4.basename ) || scripts\mp\utility\weapon::update_health_bar_to_player( var_4 );
        var_12 = isdefined( var_3 ) && var_3 == "_encstr_87230ED5301DEFDF39A94821C9F38573";

        if ( !isdefined( self.ladderdeathsthisweapon ) )
            self.ladderdeathsthisweapon = 1;
        else
            self.ladderdeathsthisweapon++;

        if ( var_3 == "_encstr_8FA10CBC37F487A99F9C0DE438C7" || var_1 == self || var_3 == "_encstr_8AED0A5719ED37B8FB512FD7" && var_11 || self.ladderdeathsthisweapon == level.setbackstreak || var_12 )
        {
            self.ladderdeathsthisweapon = 0;
            self playlocalsound( "_encstr_9B6F165B83F5DD1693EBF626A6561B1D5ACE2BEBB1B7E6A3" );
            self notify( "_encstr_9E4813C79099795BEB8835ED8F81230541F8372330" );
            self.gungameprevgunindex = self.gungamegunindex;
            self.gungamegunindex = int( max( 0, self.gungamegunindex - level.setback ) );

            if ( self.gungameprevgunindex > self.gungamegunindex )
            {
                if ( level.teambased )
                    scripts\mp\gamescore::giveplayerscore( "_encstr_A9DB117723101863ED912FD7AB37D95218C82C", 0 );
                else
                    scripts\mp\gamescore::giveplayerscore( "_encstr_A9DB117723101863ED912FD7AB37D95218C82C", 0 );

                thread scripts\mp\rank::scoreeventpopup( "_encstr_A9DB117723101863ED912FD7AB37D95218C82C" );
                var_13 = getnextgun();
                var_13 = scripts\mp\weapons::updatesavedaltstate( var_13 );
                self.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"]["_encstr_87C30FC410893345733089A330AB3E9362"] = var_13;
                self.preloadedclassstruct = undefined;
            }

            if ( var_3 == "_encstr_8AED0A5719ED37B8FB512FD7" )
            {
                if ( self.gungameprevgunindex )
                    var_1 thread scripts\mp\utility\points::giveunifiedpoints( "_encstr_A6A217A11ABDE067CF12A6E9DAA791D0D9671B3D8F22A0A02F" );

                var_1 scripts\mp\awards::givemidmatchaward( "_encstr_9E8A0FF93FC3F9E787331889AADF49313F" );
            }

            if ( var_1 == self )
                return;
        }

        if ( var_1 != self && var_3 == "_encstr_9E0A12A801F1A13344CE341769AE337BB97150B1" || var_3 == "_encstr_A88211C92CA36712F335C480B96EE5B4143049" || var_3 == "_encstr_8F280E35E759A9A325A5D069CF8B87D3" || var_3 == "_encstr_81670F602F2B4957763C758D38D1FF6C3B" || var_3 == "_encstr_BA3916099077D7673B375A25D3CB8C29EF394169385E873C" || var_3 == "_encstr_A9ED0B35F488AF94A9A0A00D8A" || var_3 == "_encstr_A11B0CBD04C9B790F653EBCF4915" || var_3 == "_encstr_9E0B13A801F1A16F27C52E196DED47FA817110C1A1" || var_3 == "_encstr_A45C0E4B9FDF3165A3B93C4491BFA4A9" || var_3 == "_encstr_AD0D0935D0FD0FFFFBF108" || var_3 == "_encstr_8AED0A5719ED37B8FB512FD7" && var_1 update_readings() && ( var_11 || var_10 || var_12 ) || var_3 == "_encstr_8AED0A5719ED37B8FB512FD7" && !var_11 || var_12 )
        {
            var_14 = getweaponbasename( var_1.primaryweapon );

            if ( !var_1 get_available_unique_id( var_4, var_14, var_12, var_10, var_11 ) )
                return;

            if ( !isdefined( var_1.ladderkillsthisweapon ) )
                var_1.ladderkillsthisweapon = 1;
            else
                var_1.ladderkillsthisweapon++;

            if ( var_1.ladderkillsthisweapon != level.killsperweapon )
                return;

            var_1.ladderkillsthisweapon = 0;
            var_1.ladderdeathsthisweapon = 0;
            var_1.gungameprevgunindex = var_1.gungamegunindex;
            var_1.gungamegunindex++;
            var_1.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"] = var_1.gungamegunindex;
            var_1.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"]++;
            var_1 notify( "_encstr_9E4813C79099795BEB8835ED8F81230541F8372330" );

            if ( level.teambased )
                var_1 scripts\mp\gamescore::giveplayerscore( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5", 0 );
            else
                var_1 scripts\mp\gamescore::giveplayerscore( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5", 0 );

            if ( var_1.gungamegunindex < level.gun_guns.size )
            {
                var_15 = scripts\mp\rank::getscoreinfovalue( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
                var_1 thread scripts\mp\rank::scorepointspopup( var_15 );
                var_1 thread scripts\mp\rank::scoreeventpopup( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
                var_1 playlocalsound( "_encstr_8FED17AD1CEBDD169CBEBD26A695C63A5A9DACAF3A0B5BB2E6" );
                var_13 = var_1 getnextgun();
                var_13 = scripts\mp\weapons::updatesavedaltstate( var_13 );
                var_1.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"]["_encstr_87C30FC410893345733089A330AB3E9362"] = var_13;
                var_1.preloadedclassstruct = undefined;
                var_1 thread givenextgun( 0 );
            }
            else if ( var_1.gungamegunindex >= level.gun_guns.size )
            {
                var_1.gungamegunindex = 0;
                var_1.gungameprevgunindex = 0;
                var_1.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"] = 0;
                var_1.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"] = 0;
                var_15 = scripts\mp\rank::getscoreinfovalue( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
                var_1 thread scripts\mp\rank::scorepointspopup( var_15 );
                var_1 thread scripts\mp\rank::scoreeventpopup( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
                var_1 playlocalsound( "_encstr_8FED17AD1CEBDD169CBEBD26A695C63A5A9DACAF3A0B5BB2E6" );
                var_13 = var_1 getnextgun();
                var_13 = scripts\mp\weapons::updatesavedaltstate( var_13 );
                var_1.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"]["_encstr_87C30FC410893345733089A330AB3E9362"] = var_13;
                var_1.preloadedclassstruct = undefined;
                var_1 thread givenextgun( 0 );
            }

            var_1.lastgunrankincreasetime = gettime();
        }
    }
}

get_available_unique_id( var_0, var_1, var_2, var_3, var_4 )
{
    if ( var_0.basename == var_1 )
        return 1;

    if ( var_1 == "_encstr_80AC13B4DD707D9B9BF51BE4DE37B998DBBBD7ADE0" )
    {
        if ( issubstr( var_0.basename, "_encstr_A89B05EEC0A13B" ) )
            return 1;
    }

    if ( var_0.basename == "_encstr_974511E14BEFD418C52B95AD256E882B6FD2FB" )
        return 1;

    if ( update_readings() )
    {
        if ( var_2 || var_3 || var_4 )
            return 1;
    }

    return 0;
}

update_readings()
{
    return self.gungamegunindex == level.gun_guns.size - 1;
}

_id_12038( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9 )
{
    if ( isdefined( var_1 ) && isplayer( var_1 ) )
    {
        if ( isdefined( self.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] ) && self.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"].size > 0 )
            self.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] = [];

        if ( isdefined( var_1.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] ) && var_1.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"].size > 0 )
            var_1.pers["_encstr_A9B90BD8C6C29BB9862C8D8695"] = [];
    }

    var_10 = isdefined( var_3 ) && var_3 == "_encstr_87230ED5301DEFDF39A94821C9F38573";

    if ( var_3 == "_encstr_8FA10CBC37F487A99F9C0DE438C7" || isdefined( var_1 ) && isplayer( var_1 ) )
    {
        if ( !isdefined( self.ladderdeathsthisweapon ) )
            self.ladderdeathsthisweapon = 1;
        else
            self.ladderdeathsthisweapon++;

        if ( var_3 == "_encstr_8FA10CBC37F487A99F9C0DE438C7" || var_1 == self || var_3 == "_encstr_8AED0A5719ED37B8FB512FD7" || self.ladderdeathsthisweapon == level.setbackstreak || var_10 )
        {
            self.ladderdeathsthisweapon = 0;
            self playlocalsound( "_encstr_9B6F165B83F5DD1693EBF626A6561B1D5ACE2BEBB1B7E6A3" );
            self notify( "_encstr_9E4813C79099795BEB8835ED8F81230541F8372330" );
            self.gungameprevgunindex = self.gungamegunindex;
            self.gungamegunindex = int( max( 0, self.gungamegunindex - level.setback ) );

            if ( self.gungameprevgunindex > self.gungamegunindex )
            {
                if ( level.teambased )
                    scripts\mp\gamescore::giveplayerscore( "_encstr_A9DB117723101863ED912FD7AB37D95218C82C", 0 );
                else
                    scripts\mp\gamescore::giveplayerscore( "_encstr_A9DB117723101863ED912FD7AB37D95218C82C", 0 );

                thread scripts\mp\rank::scoreeventpopup( "_encstr_A9DB117723101863ED912FD7AB37D95218C82C" );
                var_11 = getnextgun();
                var_11 = scripts\mp\weapons::updatesavedaltstate( var_11 );
                self.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"]["_encstr_87C30FC410893345733089A330AB3E9362"] = var_11;
                self.preloadedclassstruct = undefined;
            }

            if ( var_3 == "_encstr_8AED0A5719ED37B8FB512FD7" )
            {
                if ( self.gungameprevgunindex )
                    var_1 thread scripts\mp\utility\points::giveunifiedpoints( "_encstr_A6A217A11ABDE067CF12A6E9DAA791D0D9671B3D8F22A0A02F" );

                var_1 scripts\mp\awards::givemidmatchaward( "_encstr_9E8A0FF93FC3F9E787331889AADF49313F" );
            }

            if ( var_1 == self )
                return;
        }

        if ( isdefined( var_1.lastgunrankincreasetime ) && var_1.lastgunrankincreasetime + 500 > gettime() )
            return;

        if ( !isdefined( var_1.ladderkillsthisweapon ) )
            var_1.ladderkillsthisweapon = 1;
        else
            var_1.ladderkillsthisweapon++;

        if ( var_1.ladderkillsthisweapon != level.killsperweapon )
            return;

        var_1.ladderkillsthisweapon = 0;
        var_1.ladderdeathsthisweapon = 0;
        var_1.gungameprevgunindex = var_1.gungamegunindex;
        var_1.gungamegunindex++;
        var_1.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"] = var_1.gungamegunindex;
        var_1.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"]++;
        var_1 notify( "_encstr_9E4813C79099795BEB8835ED8F81230541F8372330" );

        if ( level.teambased )
            var_1 scripts\mp\gamescore::giveplayerscore( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5", 0 );
        else
            var_1 scripts\mp\gamescore::giveplayerscore( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5", 0 );

        if ( var_1.gungamegunindex < level.gun_guns.size )
        {
            var_12 = scripts\mp\rank::getscoreinfovalue( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
            var_1 thread scripts\mp\rank::scorepointspopup( var_12 );
            var_1 thread scripts\mp\rank::scoreeventpopup( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
            var_1 playlocalsound( "_encstr_8FED17AD1CEBDD169CBEBD26A695C63A5A9DACAF3A0B5BB2E6" );
            var_11 = var_1 getnextgun();
            var_11 = scripts\mp\weapons::updatesavedaltstate( var_11 );
            var_1.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"]["_encstr_87C30FC410893345733089A330AB3E9362"] = var_11;
            var_1.preloadedclassstruct = undefined;
            var_1 thread givenextgun( 0, undefined, var_1 scripts\cp_mp\utility\player_utility::isusingremote() );
        }
        else if ( var_1.gungamegunindex >= level.gun_guns.size )
        {
            var_1.gungamegunindex = 0;
            var_1.gungameprevgunindex = 0;
            var_1.pers["_encstr_9D8A14D9BADC1D2CB55914C956B31DD5DC94DC19B2C3"] = 0;
            var_1.pers["_encstr_BE671076ABCD74856B593AEACD25B932561E"] = 0;
            var_12 = scripts\mp\rank::getscoreinfovalue( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
            var_1 thread scripts\mp\rank::scorepointspopup( var_12 );
            var_1 thread scripts\mp\rank::scoreeventpopup( "_encstr_8175107616D2732BC8EBD9EAB9D73916B9B5" );
            var_1 playlocalsound( "_encstr_8FED17AD1CEBDD169CBEBD26A695C63A5A9DACAF3A0B5BB2E6" );
            var_11 = var_1 getnextgun();
            var_11 = scripts\mp\weapons::updatesavedaltstate( var_11 );
            var_1.pers["_encstr_A2FB10AFE391259857B908783F59C26F5BEB"]["_encstr_87C30FC410893345733089A330AB3E9362"] = var_11;
            var_1.preloadedclassstruct = undefined;
            var_1 thread givenextgun( 0, undefined, var_1 scripts\cp_mp\utility\player_utility::isusingremote() );
        }

        var_1.lastgunrankincreasetime = gettime();
    }
}

_id_1438C()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self endon( "_encstr_8A820B4696CDB1ED3737AC1B3A" );
    self waittill( "_encstr_9B6F0FDC8316DDE62B8CF507C616CB599C" );

    if ( self.gungamegunindex == level.gun_guns.size )
        self.gungamegunindex = self.gungameprevgunindex;

    thread givenextgun( 1 );
}

givenextgun( var_0, var_1, var_2 )
{
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    self notify( "_encstr_878C12CEB4CEB2E85DDCA316DA955DAC0B38DEE6" );
    self endon( "_encstr_878C12CEB4CEB2E85DDCA316DA955DAC0B38DEE6" );

    if ( isdefined( self.infil ) )
        scripts\mp\flags::gameflagwait( "_encstr_989F0E38272BD6161DB143F532BDDC2B" );

    if ( istrue( var_2 ) )
    {
        while ( scripts\cp_mp\utility\player_utility::isusingremote() )
            wait 0.05;

        wait 1;
    }

    if ( !var_0 )
        scripts\common\utility::allow_weapon_switch( 0 );

    var_3 = getnextgun();
    var_3 = scripts\mp\weapons::updatesavedaltstate( var_3 );

    if ( !var_0 && !istrue( var_1 ) || isbot( self ) )
        scripts\cp_mp\utility\inventory_utility::_giveweapon( var_3, undefined, undefined, 1 );

    if ( var_0 && isbot( self ) )
    {
        self setspawnweapon( var_3 );

        foreach ( var_5 in self.weaponlist )
        {
            if ( var_5 != var_3 )
                thread scripts\cp_mp\utility\inventory_utility::takeweaponwhensafe( var_5 );
        }
    }

    if ( !var_0 && !istrue( var_1 ) || isbot( self ) )
    {
        self.pers["_encstr_BE310E8339B4B60B272FEA591607BD9B"] = var_3.basename;
        self.primaryweapon = var_3.basename;
        self.primaryweaponobj = var_3;
        scripts\cp_mp\utility\inventory_utility::_switchtoweapon( var_3 );
    }

    if ( !var_0 && !istrue( var_1 ) )
    {
        var_7 = self.lastdroppableweaponobj;
        thread takeweaponwhensafegungame( var_7, 1 );
    }

    scripts\mp\weapons::updatetogglescopestate( var_3 );
    self.gungameprevgunindex = self.gungamegunindex;

    if ( !isdefined( self.lastgunpromotiontime ) )
        self.lastgunpromotiontime = gettime();

    var_8 = ( gettime() - self.lastgunpromotiontime ) / 1000;
    self.lastgunpromotiontime = gettime();

    if ( isdefined( self.pers["_encstr_8927198CCF65B829D8CC4B51481DEFABB0B051F08849E0FFE852A6"] ) && var_8 > self.pers["_encstr_8927198CCF65B829D8CC4B51481DEFABB0B051F08849E0FFE852A6"] )
        self.pers["_encstr_8927198CCF65B829D8CC4B51481DEFABB0B051F08849E0FFE852A6"] = var_8;
}

takeweaponwhensafegungame( var_0, var_1 )
{
    self endon( "_encstr_87DC14B3C0C903B191786B89AC8373FA90A51D5742F3" );

    for (;;)
    {
        if ( !scripts\cp_mp\utility\inventory_utility::iscurrentweapon( var_0 ) )
            break;

        waitframe();
    }

    scripts\cp_mp\utility\inventory_utility::_takeweapon( var_0 );

    if ( var_1 )
        scripts\common\utility::allow_weapon_switch( 1 );
}

getnextgun( var_0 )
{
    var_1 = self.gungamegunindex;

    if ( isdefined( var_0 ) )
        var_1 = var_0;

    var_2 = level.gun_guns[var_1];
    return var_2;
}

_id_131C1()
{
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_87C30FC410893345733089A330AB3E9362"] = "_encstr_8A900D2DEEE0EB83A5AF6CE0C238B0";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_B44319C6DB5832DEAE3A289C965B2CC95E141DA32C36A1D65673A3"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_A9651AE2C897BBF598D1103A83303EBBC3A5DBEB917E43AD20FD4C62"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_9B651AD8DE0B23B7EA4705E4B46B58E4CBA0E8D10B8DA15BB2E6A366"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_AF651A79955A81A835EBB1B8877521E563B6EDFDEE9241D00DEB9882"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_B3651A1BB70B32B7EA1DA0E4A5B51639E5823A47B0D80DB5AC37476A"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_B66C1363F658327BD53A419396B558E49786B0B5DB"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_B4312136DB1646B7D5A328E4B46B164E9734F69BDAAC1D5A1B828ED185D8A1ADCA9B8E"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_8702161410EA292F7BB321E36172F3866033F7BCB96F09A9"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_95FC16036F1FEAC708138212A8101143EBEFEB8FDFB2A292"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_A1D217D4B799237543A399B3C05B2EA372E63459AE606F7AB3"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_BAD217D16F6051D890ECCB0238A133125B5703FBFEB70DD38A"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_BDD217B17BB023B7D58E0A4EB4ADC2935EA6E85AD8B5B2C9CC"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_B35A181BDE2C91B7BAE814932D6B0B39F2AC2C9C9616CD47A488"] = 0;
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_A14E11D520C0AC320551FF3F67206AE4782B08"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_9D6F1B6C48D16B2D1B48D18AC817252389AEF1395DDBC7F6C968BA3218"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_BDDB1C6590701C82D5812FCF97F0DA54285B58A66B70A19AA35BFFEBD106"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_A2EA151BD081D44253851297663F0A9C2980C73F48F807"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_82B618ABEA2661705BBB2A415B6D7332AB2AD71F9D3880AE324D"] = "_encstr_AABA05236DC831";
    level.gun_loadouts["_encstr_BA840579D3F7F6"]["_encstr_80531AE430A913A593D05932408FDDAB012669565F936FEE7D28E018"] = 0;
    level.gun_loadouts["_encstr_BC850785638DA59537"] = level.gun_loadouts["_encstr_BA840579D3F7F6"];
}

tv_station_infil_enemy_combat_logic()
{
    return level.set_systems_init_flag == 1;
}

tv_station_infil_enemies_attack_logic()
{
    return level.set_systems_init_flag == 2;
}

tv_station_global_stealth_broken()
{
    return level.set_systems_init_flag == 3;
}

turret_enemy_watcher_internal()
{
    return level.set_systems_init_flag == 7 || level.set_systems_init_flag == 8 || level.set_systems_init_flag == 9 || level.set_systems_init_flag == 10;
}

_id_1326E()
{
    level._id_1346D = [];
    var_0 = [];
    var_1 = undefined;

    if ( scripts\mp\utility\game::getgametype() == "_encstr_9DB606854E567385" )
    {
        var_2 = getentarray( "_encstr_BE220B0F544A08E8D6334DB5BF", "_encstr_B8CE0BE43FC317DF690862BA48" );
        var_1 = var_2[0].origin + ( 0, 0, 30 );
    }
    else
    {
        var_0 = [];
        var_3 = getentarray( "_encstr_93170DA48D825F66F84B3018EF127A", "_encstr_B8CE0BE43FC317DF690862BA48" );

        foreach ( var_5 in var_3 )
        {
            if ( var_5.script_label == "_encstr_A40703FA31" )
            {
                var_0[var_0.size] = var_5.origin;
                break;
            }
        }

        if ( var_0.size == 0 )
            return;

        var_0 = scripts\engine\utility::array_randomize( var_0 );
        var_1 = var_0[0];

        if ( getdvar( "_encstr_BC050B8321978C816169428DCF" ) == "_encstr_AF930F218A615DA0FA270848A30198876A" )
            var_1 = ( -194, -858, 90 );
    }

    var_7 = [];
    var_8 = getentarray( "_encstr_BE8D161BBC895639FAB26B83BE835AD8D6D538AF8E394BCE", "_encstr_B8CE0BE43FC317DF690862BA48" );

    foreach ( var_10 in var_8 )
        var_7[var_7.size] = var_10.origin;

    level._id_11E00 = var_7;
    var_12 = undefined;

    if ( getdvarint( "_encstr_89271A93D75D79EB38DB865DABAF6B89E8B567D2613BC0A71860A77F", 0 ) == 1 && var_7.size > 0 )
    {
        var_12 = 1;
        var_0 = scripts\engine\utility::array_combine( var_0, var_7 );
        var_0 = scripts\engine\utility::array_randomize( var_0 );
        var_1 = var_0[0];
    }

    level thread init_reach_exhaust_waste( var_1, 1 );
}

init_reach_exhaust_waste( var_0, var_1 )
{
    if ( isdefined( var_1 ) )
        wait( var_1 );

    var_2 = var_0 + ( 0, 0, 64 );
    var_3 = var_0 + ( 0, 0, -64 );
    var_4 = scripts\engine\trace::ray_trace( var_2, var_3, undefined, scripts\engine\trace::create_default_contents( 1 ) );
    var_0 = var_4["_encstr_B7260923C89E8F3378E72E"] + ( 0, 0, 30 );
    var_5 = spawnstruct();
    var_5.angles = ( 0, 0, 0 );
    var_5.visuals = spawn( "_encstr_93DC0DCD1B272D3847AF5BED23B2C6", var_0 );
    var_5.visuals setmodel( "_encstr_B3381117931BC7AB4917B7EC05132182C198BB" );
    var_5.visuals dontinterpolate();
    var_5._id_12C7B = var_0;
    var_5.usemilestonephases = 1;
    var_5.onreset = ::_id_1208B;
    var_5._id_1203A = ::_id_1203A;
    var_5._id_13472 = ::_id_13789;
    var_6 = ( 0, 30, 0 );
    var_7 = anglestoup( var_6 );
    var_8 = anglestoforward( var_6 );

    if ( getdvar( "_encstr_BC050B8321978C816169428DCF" ) == "_encstr_9D0A0D8DEF670ABF8B48776B48A375" )
        var_9 = var_7 * 500 + ( 0, 0, 80 );
    else
        var_9 = var_7 * 50 + ( 0, 0, 80 );

    waittillframeend;
    scripts\mp\flags::gameflagwait( "_encstr_989F0E38272BD6161DB143F532BDDC2B" );
    var_5.visuals physicslaunchserver( var_5.visuals.origin, var_9 );
    var_5 thread _id_12167();
    var_5 thread _id_12168();

    if ( getdvarint( "_encstr_A3F2148F229B96DFE73B18E1CB5779E1FF38E7AFA9E3", 1 ) == 1 )
        var_5 thread _id_13470();

    if ( isdefined( var_5._id_13472 ) )
        var_5 [[ var_5._id_13472 ]]();

    level._id_1346D[level._id_1346D.size] = var_5;
}

_id_13789()
{
    self.visuals thread scripts\mp\utility\entity::register_physics_collisions();
    self.visuals physics_registerforcollisioncallback();
    scripts\mp\utility\entity::register_physics_collision_func( self.visuals, ::ball_impact_sounds );
}

ball_impact_sounds( var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8 )
{
    var_9 = var_0 physics_getbodyid( 0 );
    var_10 = physics_getbodylinvel( var_9 );
    var_11 = length( var_10 );

    if ( isdefined( var_0.playing_sound ) || var_11 < 70 )
        return;

    var_0 endon( "_encstr_A3750609A5E61883" );
    var_0.playing_sound = 1;
    var_12 = physics_getsurfacetypefromflags( var_4 );
    var_13 = getsubstr( var_12["_encstr_81BA051A9AA88B"], 9 );

    if ( var_13 == "_encstr_A9140E55C708BA5715991B6361E3DB22" )
        var_0 playsound( "_encstr_9E4616E6DE36BE260B361BF589DEAE376CCAEB9BAD58D8C6" );
    else if ( var_11 < 180 )
        var_0 playsurfacesound( "_encstr_9E4616E6DE36BE260B361BF589DEAE376CCAEB9BAD58D8C6", var_13 );
    else if ( var_11 < 260 )
        var_0 playsurfacesound( "_encstr_970214AA98682F4AD7B9EB2F8D8863461BA129B571E8", var_13 );
    else
        var_0 playsurfacesound( "_encstr_87BD16DF57EEC91EAFE290FE2ABF4D9806B57F69C11240D5", var_13 );

    wait 0.1;
    var_0.playing_sound = undefined;
}

_id_1208B( var_0 )
{
    self.stage3accradius = 1;

    if ( !istrue( var_0 ) )
    {
        wait 0.5;
        self.visuals playsound( "_encstr_97E01022278741735FA968510C6055205268" );
        playfx( level._id_1346C["_encstr_AAE007D90BB9A5E61A"], self.visuals.origin );
    }
    else
    {
        wait 0.1;
        playfx( level._id_1346C["_encstr_AAE007D90BB9A5E61A"], self.visuals.origin );
    }

    self.visuals hide();
    wait 1;
    self.visuals.origin = self._id_12C7B;
    var_1 = ( 0, 30, 0 );
    var_2 = anglestoup( var_1 );
    var_3 = anglestoforward( var_1 );

    if ( level.mapname == "_encstr_9D0A0D8DEF670ABF8B48776B48A375" )
        var_4 = var_2 * 500 + ( 0, 0, 80 );
    else
        var_4 = var_2 * 50 + ( 0, 0, 80 );

    self.visuals show();
    self.visuals physicslaunchserver( self.visuals.origin, var_4 );
    self.stage3accradius = 0;

    if ( isdefined( self._id_13472 ) )
        self [[ self._id_13472 ]]();
}

_id_1203A( var_0 )
{
    if ( istrue( self.stage3accradius ) )
    {
        self.stage3accradius = 0;
        return;
    }

    if ( game["_encstr_A6D60EE09BF413B9945185CB4797C583"] )
    {
        var_1 = scripts\mp\utility\game::getotherteam( var_0.team )[0];

        if ( var_1 == "_encstr_BC850785638DA59537" )
        {
            game["_encstr_824E0A581EA5CD1DF6C21BCD"]++;
            var_2 = "_encstr_80A707F738A13B51E3";
        }
        else
        {
            game["_encstr_8FF20C6F886099A21F5CDD5621C7"]++;
            var_2 = "_encstr_B2A707C84F916057C7";
        }
    }
    else
    {
        var_1 = var_0.team;

        if ( var_1 == "_encstr_BC850785638DA59537" )
        {
            game["_encstr_8FF20C6F886099A21F5CDD5621C7"]++;
            var_2 = "_encstr_B2A707C84F916057C7";
        }
        else
        {
            game["_encstr_824E0A581EA5CD1DF6C21BCD"]++;
            var_2 = "_encstr_80A707F738A13B51E3";
        }
    }

    if ( isdefined( var_2 ) )
        scripts\engine\utility::exploder( var_2 );

    var_3 = "_encstr_BDB30883934F28A00A93";

    if ( isdefined( var_3 ) )
        scripts\engine\utility::exploder( var_3 );

    var_0.select_low_roof_spawners++;
    level _id_14017( var_0 );
    var_0 thread select_lobby_door_two_spawners();

    if ( scripts\mp\utility\game::getgametype() == "_encstr_9DB606854E567385" )
    {
        foreach ( var_5 in level.players )
        {
            if ( var_5.team == var_1 )
            {
                if ( var_5.team == "_encstr_BC850785638DA59537" )
                    var_5 thread _id_12736( "_encstr_BAFD1DC8E1AFDA070BBE935DE81BFADCD5D6B5AC93FA7658DA597D3BF6588D" + scripts\engine\utility::random( level.select_lobby_door_one_spawners ), "_encstr_9DD111A0EF5598FB0BF1ACA7555247018F57A0", 2, "_encstr_8B0A11A6C52ADFB9627738807784363942EF11" );
                else
                    var_5 thread _id_12736( "_encstr_97741D916BD878282F6173823BB4F96ED30D0A63064EFAEFCD6BF1A7D806D1" + scripts\engine\utility::random( level.select_lobby_door_one_spawners ), "_encstr_9DD111A0EF5598FB0BF1ACA7555247018F57A0", 2, "_encstr_8B0A11A6C52ADFB9627738807784363942EF11" );

                continue;
            }

            if ( var_5.team == "_encstr_BC850785638DA59537" )
            {
                var_5 thread _id_12736( "_encstr_97741D916BD878282F6173823BB4F96ED30D0A63064EFAEFCD6BF1A7D806D1" + scripts\engine\utility::random( level.select_lobby_door_one_spawners ), "_encstr_9DD111A0EF5598FB0BF1ACA7555247018F57A0", 2, "_encstr_8A400F7B5003B3ED7A60F19039D1E01738" );
                continue;
            }

            var_5 thread _id_12736( "_encstr_BAFD1DC8E1AFDA070BBE935DE81BFADCD5D6B5AC93FA7658DA597D3BF6588D" + scripts\engine\utility::random( level.select_lobby_door_one_spawners ), "_encstr_9DD111A0EF5598FB0BF1ACA7555247018F57A0", 2, "_encstr_8A400F7B5003B3ED7A60F19039D1E01738" );
        }
    }
    else
    {
        foreach ( var_5 in level.players )
        {
            if ( var_5.team == "_encstr_BC850785638DA59537" )
            {
                var_5 thread _id_12736( "_encstr_97741D916BD878282F6173823BB4F96ED30D0A63064EFAEFCD6BF1A7D806D1" + scripts\engine\utility::random( level.select_lobby_door_one_spawners ), "_encstr_9DD111A0EF5598FB0BF1ACA7555247018F57A0", 2, "_encstr_8A400F7B5003B3ED7A60F19039D1E01738" );
                continue;
            }

            var_5 thread _id_12736( "_encstr_BAFD1DC8E1AFDA070BBE935DE81BFADCD5D6B5AC93FA7658DA597D3BF6588D" + scripts\engine\utility::random( level.select_lobby_door_one_spawners ), "_encstr_9DD111A0EF5598FB0BF1ACA7555247018F57A0", 2, "_encstr_8A400F7B5003B3ED7A60F19039D1E01738" );
        }
    }

    self.visuals thread _id_12737();
    var_9 = self.visuals getlinkedchildren();

    foreach ( var_11 in var_9 )
    {
        if ( isdefined( var_11 ) )
            var_11 unlink( 1 );
    }

    if ( isdefined( self.onreset ) )
        self thread [[ self.onreset ]]( 1 );

    if ( var_0.select_low_roof_spawners >= 10 && isdefined( game["_encstr_BC4D0A9FC31163490939151D"] ) && !game["_encstr_BC4D0A9FC31163490939151D"] || getdvarint( "_encstr_9C131833861299D47AC7B33F1362A6B0DD9D7B68EB61089F82EB", 0 ) == 1 && isdefined( game["_encstr_BC4D0A9FC31163490939151D"] ) && !game["_encstr_BC4D0A9FC31163490939151D"] )
    {
        game["_encstr_BC4D0A9FC31163490939151D"] = 1;

        foreach ( var_5 in level.players )
            var_5 thread scripts\mp\hud_message::showsplash( "_encstr_A456115B10AFBEF713F83D3D09BB8F86D36032" );

        if ( level._id_11E00.size > 0 )
        {
            var_15 = getdvarint( "_encstr_8B5D1907D0838FA21B69BF394EDF3A7B89A0F78763FBE1BA73F1C5", 3 );

            for ( var_16 = 0; var_16 < var_15; var_16++ )
                init_reach_exhaust_waste( level._id_11E00[var_16] );
        }
    }
}

_id_12737()
{
    self playsound( "_encstr_A4E5119BDB36AF13B0D8D8BECA0FE08DBD3256" );
    wait 1.5;
    self playsound( "_encstr_B78014C318C1D73E63F85279B8A736D3BEF14D5BA369" );
}

select_lobby_door_two_spawners( var_0, var_1 )
{
    for ( var_2 = 0; var_2 < min( self.select_low_roof_spawners, 10 ); var_2++ )
    {
        playfx( level.select_stairway_spawners["_encstr_B7BA0E3FD8CBF7CA638EE71B783D5283"], self.trigger.origin + ( randomintrange( -100, 100 ), randomintrange( -100, 100 ), randomintrange( -25, 60 ) ), anglestoforward( self.trigger.angles + ( randomintrange( int( max( clamp( 0 - var_2 * 5, -19, 0 ), -20 ) ), int( min( 20, 1 + var_2 * 5 ) ) ), randomintrange( int( max( clamp( 0 - var_2 * 5, -19, 0 ), -20 ) ), int( min( 20, 1 + var_2 * 5 ) ) ), 0 ) ), anglestoup( self.trigger.angles + ( randomintrange( int( max( clamp( 0 - var_2 * 5, -19, 0 ), -20 ) ), int( min( 20, 1 + var_2 * 5 ) ) ), randomintrange( int( max( clamp( 0 - var_2 * 5, -19, 0 ), -20 ) ), int( min( 20, 1 + var_2 * 5 ) ) ), 0 ) ) );

        if ( istrue( var_0 ) )
            level thread _id_14397( self.trigger.origin );

        if ( isdefined( var_1 ) )
            wait( var_1 );
    }
}

_id_14017( var_0 )
{
    foreach ( var_2 in level.brking_playerwelcomesplashes )
    {
        if ( var_2._id_12F11 == var_0.team )
        {
            if ( var_0.select_low_roof_spawners >= 10 )
            {
                var_2.scriptable setscriptablepartstate( "_encstr_93FB06DC6CBDE4CA", "_encstr_A607030FA8" );
                continue;
            }

            var_2.scriptable setscriptablepartstate( "_encstr_93FB06DC6CBDE4CA", "_encstr_B34C0233" + scripts\engine\utility::string( var_0.select_low_roof_spawners ) );
        }
    }
}

_id_12167()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );

    for (;;)
    {
        wait 0.5;

        if ( istrue( self.stage3accradius ) )
            continue;

        if ( isdefined( self.resetnow ) )
        {
            self.resetnow = undefined;

            if ( isdefined( self.onreset ) )
                self thread [[ self.onreset ]]();

            continue;
        }

        for ( var_0 = 0; var_0 < level.radtriggers.size; var_0++ )
        {
            if ( !self.visuals istouching( level.radtriggers[var_0] ) )
                continue;

            if ( isdefined( self.onreset ) )
                self thread [[ self.onreset ]]();

            continue;
        }

        for ( var_0 = 0; var_0 < level.minetriggers.size; var_0++ )
        {
            if ( !self.visuals istouching( level.minetriggers[var_0] ) )
                continue;

            if ( isdefined( self.onreset ) )
                self thread [[ self.onreset ]]();

            continue;
        }

        for ( var_0 = 0; var_0 < level.hurttriggers.size; var_0++ )
        {
            if ( !self.visuals istouching( level.hurttriggers[var_0] ) )
                continue;

            if ( isdefined( self.onreset ) )
                self thread [[ self.onreset ]]();

            continue;
        }

        if ( istrue( level.ballallowedtriggers.size ) )
        {
            self.allowedintrigger = 0;

            foreach ( var_2 in level.ballallowedtriggers )
            {
                if ( self.visuals istouching( var_2 ) )
                {
                    self.allowedintrigger = 1;
                    break;
                }
            }
        }

        if ( isdefined( level.outofboundstriggers ) )
        {
            foreach ( var_2 in level.outofboundstriggers )
            {
                if ( istrue( self.allowedintrigger ) )
                    break;

                if ( !self.visuals istouching( var_2 ) )
                    continue;

                if ( isdefined( self.onreset ) )
                    self thread [[ self.onreset ]]();

                continue;
            }
        }

        if ( isdefined( self.autoresettime ) )
        {
            wait( self.autoresettime );

            if ( !isdefined( self.carrier ) )
            {
                if ( isdefined( self.onreset ) )
                    self thread [[ self.onreset ]]();
            }
        }
    }
}

_id_12168()
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );

    for (;;)
    {
        wait 0.25;

        if ( istrue( self.stage3accradius ) )
            continue;

        if ( distancesquared( self.visuals.origin, self._id_12C7B ) > 9000000 )
        {
            if ( isdefined( self.onreset ) )
                self thread [[ self.onreset ]]();
        }
    }
}

_id_13471()
{
    var_0 = getentarray( "_encstr_A2720C0B63B14BCAE6F5CE7B16D8", "_encstr_B8CE0BE43FC317DF690862BA48" );
    var_1 = getentarray( "_encstr_B6B80A8F38E72BF797A25063", "_encstr_B8CE0BE43FC317DF690862BA48" );

    if ( var_0.size > 0 && var_1.size > 0 )
    {
        level.briotshieldinitialized = spawnstruct();
        level.briotshieldinitialized.team = "_encstr_BC850785638DA59537";
        level.briotshieldinitialized.trigger = var_0[0];
        level.briotshieldinitialized.entsinside = [];
        level.chooseanim_vehicleturretdeath = spawnstruct();
        level.chooseanim_vehicleturretdeath.team = "_encstr_BA840579D3F7F6";
        level.chooseanim_vehicleturretdeath.trigger = var_1[0];
        level.chooseanim_vehicleturretdeath.entsinside = [];
        level.chooseanim_vehicleturretdeath.select_low_roof_spawners = 0;

        if ( !isdefined( game["_encstr_8AC30D9CDEBA73466E41B1585E568C"] ) || isdefined( game["_encstr_8AC30D9CDEBA73466E41B1585E568C"] ) && game["_encstr_8AC30D9CDEBA73466E41B1585E568C"] == 0 )
        {
            game["_encstr_8FF20C6F886099A21F5CDD5621C7"] = 0;
            level.briotshieldinitialized.select_low_roof_spawners = 0;
            game["_encstr_824E0A581EA5CD1DF6C21BCD"] = 0;
            level.chooseanim_vehicleturretdeath.select_low_roof_spawners = 0;
        }
        else if ( game["_encstr_A6D60EE09BF413B9945185CB4797C583"] )
        {
            level.chooseanim_vehicleturretdeath.select_low_roof_spawners = game["_encstr_8FF20C6F886099A21F5CDD5621C7"];
            level.briotshieldinitialized.select_low_roof_spawners = game["_encstr_824E0A581EA5CD1DF6C21BCD"];
        }
        else
        {
            level.briotshieldinitialized.select_low_roof_spawners = game["_encstr_8FF20C6F886099A21F5CDD5621C7"];
            level.chooseanim_vehicleturretdeath.select_low_roof_spawners = game["_encstr_824E0A581EA5CD1DF6C21BCD"];
        }

        level._id_1346E = [ level.chooseanim_vehicleturretdeath, level.briotshieldinitialized ];
        level thread _id_1439A();
    }
    else
        level notify( "_encstr_ADF511CD47DE38FAE6BDC68D5993FAD9BD0B63" );
}

_id_1439A()
{
    wait 1;
    level.brjugg_dropfunc = scripts\engine\utility::getstructarray( "_encstr_97CC0534B7D6B2", "_encstr_B8CE0BE43FC317DF690862BA48" );
    level.choosedropbagmodel = scripts\engine\utility::getstructarray( "_encstr_8C840551DF3868", "_encstr_B8CE0BE43FC317DF690862BA48" );
    level.brking_playerwelcomesplashes = scripts\engine\utility::array_combine( level.brjugg_dropfunc, level.choosedropbagmodel );

    foreach ( var_1 in level.brjugg_dropfunc )
    {
        var_1.scriptable = spawn( "_encstr_93DC0DCD1B272D3847AF5BED23B2C6", var_1.origin );
        var_1.scriptable.angles = var_1.angles;
        var_1.scriptable setmodel( "_encstr_9790223B991EFACD471623D25DB6BECD1BDB93CA89DB0BE446D7378D4E2D383A16C436B2" );
        var_1._id_12F11 = "_encstr_BC850785638DA59537";
    }

    foreach ( var_1 in level.choosedropbagmodel )
    {
        var_1.scriptable = spawn( "_encstr_93DC0DCD1B272D3847AF5BED23B2C6", var_1.origin );
        var_1.scriptable.angles = var_1.angles;
        var_1.scriptable setmodel( "_encstr_9790223B991EFACD471623D25DB6BECD1BDB93CA89DB0BE446D7378D4E2D383A16C436B2" );
        var_1._id_12F11 = "_encstr_BA840579D3F7F6";
    }

    level _id_14017( level.briotshieldinitialized );
    level _id_14017( level.chooseanim_vehicleturretdeath );
}

_id_13470( var_0 )
{
    level endon( "_encstr_AD1D0BEF9161A06F1F684ADA39" );
    level endon( "_encstr_ADF511CD47DE38FAE6BDC68D5993FAD9BD0B63" );

    while ( !isdefined( level._id_1346E ) )
        waitframe();

    for (;;)
    {
        wait 0.05;

        if ( istrue( self.stage3accradius ) )
            continue;

        for ( var_1 = 0; var_1 < level._id_1346E.size; var_1++ )
        {
            if ( !validatefunc( level._id_1346E[var_1], self.visuals ) )
                continue;

            if ( !_id_132E7( level._id_1346E[var_1], self.visuals ) )
                continue;

            var_2 = self.visuals getentitynumber();
            level._id_1346E[var_1].entsinside[var_2] = self.visuals;
            self.visuals._id_1346F = level._id_1346E[var_1];

            if ( isdefined( self._id_1203A ) )
                [[ self._id_1203A ]]( level._id_1346E[var_1] );

            continue;
        }
    }
}

_id_132E7( var_0, var_1 )
{
    var_2 = var_1 getentitynumber();

    if ( isdefined( var_0.entsinside[var_2] ) )
        return 0;

    return 1;
}

validatefunc( var_0, var_1 )
{
    if ( !var_1 istouching( var_0.trigger ) )
    {
        var_2 = var_1 getentitynumber();
        var_0.entsinside[var_2] = undefined;

        if ( isdefined( var_1._id_1346F ) && var_1._id_1346F == var_0 )
            var_1._id_1346F = undefined;

        return 0;
    }

    return 1;
}

_id_14397( var_0 )
{
    var_1 = "_encstr_A4BF183BB79BBE99A5E495BBDB4E5B7DB98DE4B2166BF5B9330F";
    playsoundatpos( var_0, var_1 );
    var_2 = lookupsoundlength( var_1 );
    wait 1.5;
    playsoundatpos( var_0 + ( 0, 0, 600 ), "_encstr_8189179DDB37AFCCD24E95DDB79C5B7DCA87831BEDAF6E33F0" );
}

_id_11962()
{
    level.select_stairway_spawners["_encstr_B7BA0E3FD8CBF7CA638EE71B783D5283"] = loadfx( "_encstr_B2CE294D58199AA467928105997F7793C5B1175A3872C6ABCFCB0F84DF9380E649EDB7504FF36A557D6A78" );
    level._id_1346C["_encstr_AAE007D90BB9A5E61A"] = loadfx( "_encstr_821B2EBE050805776CDA113AFB68974E48FB2D3FA9584D439CCA29C3E096CF07E827DAB92178E9EB3DE3E3BBE074E3B8" );
    level._id_1346C["_encstr_A81709D613CF3BB3A9870A"] = loadfx( "_encstr_BE3E2FC3699B16F408C99FA531A2FD67C4A1DADE5375E76FC04BD5FF05301E47EEFB82F23E4E97E5F043EFE8615ACB1B93" );
    level._id_1346C["_encstr_B817091A56309820993FC1"] = loadfx( "_encstr_A4332FE3F50BC6599022C94D037A94BAE41B730E47B56A0C18937DC53BE8B8513E81CFBBB75EF2CFE8F9F90AFBC2FE3A13" );
    level._id_1346C["_encstr_A4170950FA153579A7D0FE"] = loadfx( "_encstr_B9452FE3B1B857E2D4191FEFB1D0FA5590B91D3D8B70A1EA236BDFEED52C83B75023D677A6B06B1286530F8A45E0ABC6B0" );
    level._id_1346C["_encstr_9517091B33773391E85A42"] = loadfx( "_encstr_97232FA072084730FF10808130F6D8ABF32AE8E29BA313695F6591A82EEB82171AA30823B1BA4F401B9DB05F43220B3D1E" );
    level._id_1346C["_encstr_B61709208A652569B7E0CD"] = loadfx( "_encstr_B43C2F8573FAFF58A3A7E7E81B50C13F2BE3253FA0517979708372EA852510E80F839F113E5866FF8B97D7D13D10D31B93" );
    level._id_1346C["_encstr_A31709208A652569B7E04D"] = loadfx( "_encstr_87492F53547B5730DBB059E7380FE8595372F24037139E71702B9DEF43B8F2797B15F9E8FFD86AAAF24A070B9D92202228" );
    level._id_1346C["_encstr_8117094FCB7D302DE7974B"] = loadfx( "_encstr_9B622FECCCC379B4EE83F5DA38791BCAB3B2D8BC9BD18519B4576BE5D9CCE1D76E3A0B23D79BD8B7E42B7DC06C17D9CC87" );
    level._id_1346C["_encstr_891709870385C8E52F4FA3"] = loadfx( "_encstr_98452F9DCCF0E54BEE83F5DAC1E5C6CAB3AC8D79B9A38523A55DB5BC9D663CF5378EC232D76ED8DBC995EB0CB98BB3333C" );
    level._id_1346C["_encstr_A21709DFA95D6B9B316FF7"] = loadfx( "_encstr_8B0C2FE3E2D2C7B0E02AA9255112247563916255FE5BFB714C8B6592E882C868D2A350DFA13852F51ABD59272242960FA3" );
    level._id_1346C["_encstr_9D17096E1BEDC959F5C0C9"] = loadfx( "_encstr_8BEE2F6766F05ED2BB0EAFD60ECBC656CE2BB1E56ED1588C2DBA5B97CE99C3BE9B8E2C8CAFB91BED9C567D18C917CE9987" );
    level._id_1346C["_encstr_9817092BE6B89B17F7CA3F"] = loadfx( "_encstr_BC232F15637B68487F0EFEB03A1F58F533F7A9DF5FE307E889ABA0C0A33EB0209B1B2BC1577BDEE8CA87EE0B5AAE18E483" );
}

_id_13237()
{
    game["_encstr_B8DA073D799798C7C7"]["_encstr_A204130A7BB8BD9AFE7F2737732D61EF7B4145991B"] = "_encstr_A204130A7BB8BD9AFE7F2737732D61EF7B4145991B";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_9D041323BB380DCF668E1A62D035EF47D07BA4878D"] = "_encstr_9D041323BB380DCF668E1A62D035EF47D07BA4878D";
    game["_encstr_B8DA073D799798C7C7"]["_encstr_980413E6AED6DA2B39FAD958B62BBECEED2CD8EB33"] = "_encstr_980413E6AED6DA2B39FAD958B62BBECEED2CD8EB33";
    level.select_lobby_door_one_spawners = [ "_encstr_9C07037FB7", "_encstr_A20703D0F2", "_encstr_9D0703014E" ];
}

_id_12736( var_0, var_1, var_2, var_3 )
{
    self notify( "_encstr_9BED0CBF1F3608C8AF6AB80312AB" );
    self endon( "_encstr_9BED0CBF1F3608C8AF6AB80312AB" );

    if ( !isdefined( level.lastteamstatustime["_encstr_BC850785638DA59537"][var_1] ) )
        level.lastteamstatustime["_encstr_BC850785638DA59537"][var_1] = 0;

    if ( gettime() < level.lastteamstatustime["_encstr_BC850785638DA59537"][var_1] + var_2 * 1000 )
        return;

    self queuedialogforplayer( var_0, var_1, var_2 );
    level.lastteamstatustime["_encstr_BC850785638DA59537"][var_1] = gettime();
    thread scripts\mp\hud_message::showsplash( var_3 );
}
