// IW8 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool

scriptable_mpglobalcallback()
{
    scripts\engine\scriptable::scriptable_setinitcallback( ::scriptable_mpcallback );
}

scriptable_mpcallback()
{
    scripts\mp\flags::levelflagset( "_encstr_97EC123360481CB793B883EB058A0FFBA2C91DF3" );
}
